(in-package :cl-cc/type)

;;; ─── Backward-compat: type-qualified-type alias ─────────────────────────
;;;
;;; representation.lisp uses `type-qualified-body`; old tests use
;;; `type-qualified-type`.  make-type-qualified is defined there and accepts
;;; both :body and :type keywords — no shadowing needed here.

(defun type-qualified-type (q)
  "Backward-compat: alias for type-qualified-body."
  (type-qualified-body q))

;;; ─── Backward-compat: type-effect struct ─────────────────────────────────
;;;
;;; Old package had `type-effect` with a single :name slot.
;;; representation.lisp has `type-effect-op` with :name and :args.
;;; Tests do:
;;;   (make-type-effect :name 'IO)
;;;   (type-effect-p e)
;;;   (type-effect-name e)
;;;
;;; We define a thin struct, then define a polymorphic type-effect-name
;;; that works on BOTH type-effect and type-effect-op.
;;; The defstruct auto-generates type-effect-name as a slot accessor;
;;; we shadow it afterward with a function that handles both types.

(defstruct (type-effect (:constructor make-type-effect)
                        ;; Suppress the auto-generated type-effect-name
                        ;; so we can define a more general version below.
                        (:conc-name %type-effect-))
  "Backward-compat effect label node (old API).
New code should use type-effect-op."
  (name nil :type symbol))

;;; Polymorphic accessor: works on type-effect (old) and type-effect-op (new).
(defun type-effect-name (e)
  "Return the effect name symbol for E, which may be a type-effect or type-effect-op."
  (cond
    ((type-effect-p e)    (%type-effect-name e))
    ((type-effect-op-p e) (type-effect-op-name e))
    (t (error "type-effect-name: not an effect node: ~S" e))))

;;; ─── Backward-compat: type-effectful-function struct ─────────────────────
;;;
;;; Old package had `type-effectful-function` with slots: params, return, effects.
;;; Tests do:
;;;   (make-type-effectful-function :params ... :return ... :effects ...)
;;;   (typep fn 'type-effectful-function)
;;;   (type-effectful-function-effects fn)
;;;   (type-function-params fn)
;;;   (type-function-return fn)
;;;
;;; We define it as a struct that also satisfies `type-function-p` via
;;; :include type-arrow, so that type-function-params / type-function-return
;;; work on it.

(defstruct (type-effectful-function
            (:include type-arrow)
            (:constructor make-type-effectful-function
                          (&key params return effects mult
                           &aux (params params) (return return)
                                (effects effects) (mult (or mult :omega)))))
  "A function type annotated with an explicit effect row.
Extends type-arrow; the :effects slot is from type-arrow itself.")

;;; The effects slot is inherited from type-arrow; its accessor type-arrow-effects
;;; is also accessible as type-effectful-function-effects via the :include
;;; conc-name expansion generated by defstruct above.

;;; ─── Backward-compat: type-forall-type alias ────────────────────────────
;;;
;;; representation.lisp uses `type-forall-body`; old tests use `type-forall-type`.
;;; make-type-forall is defined there and accepts both :body and :type keywords.

(defun type-forall-type (fa)
  "Backward-compat: alias for type-forall-body."
  (type-forall-body fa))

;;; ─── Backward-compat: type-skolem ────────────────────────────────────────
;;;
;;; The old code had a `type-skolem` distinct from `type-rigid`.
;;; The new representation uses type-rigid for skolems.
;;; We build a thin compatibility layer so `make-type-skolem`,
;;; `type-skolem-p`, `type-skolem-id`, `type-skolem-name`, and
;;; `type-skolem-equal-p` all work.

(defvar *skolem-counter* 0
  "Counter for unique skolem IDs.")

(defstruct (type-skolem (:constructor %make-type-skolem))
  "Backward-compat skolem / rigid variable (old API).
Maps to type-rigid semantics."
  (id   0   :type fixnum)
  (name nil))

(defun make-type-skolem (&optional (name "a"))
  "Create a fresh skolem constant with NAME."
  (incf *skolem-counter*)
  (%make-type-skolem :id *skolem-counter* :name name))

(defun type-skolem-equal-p (s1 s2)
  "True iff S1 and S2 are the same skolem (by ID)."
  (and (type-skolem-p s1) (type-skolem-p s2)
       (= (type-skolem-id s1) (type-skolem-id s2))))

;;; NOTE: type-to-string handling for backward-compat nodes now lives in
;;; printer.lisp as proper defgeneric methods. This file keeps only the
;;; compatibility data/struct layer.
