;;;; optimizer-dae.lisp --- FR-606 Dead Argument Elimination

(in-package :cl-cc/optimize)

(defparameter *opt-dae-specialized-label-fragment* ".DAE."
  "Substring used in labels generated by FR-606 specialized functions.")

(defun %opt-dae-specialized-label-p (label)
  "Return T when LABEL names a dead-argument-elimination specialization."
  (and (stringp label)
       (search *opt-dae-specialized-label-fragment* label :test #'char=)))

(defun %opt-dae-copy-inst (inst)
  "Return a structural copy of INST."
  (handler-case
      (sexp->instruction (instruction->sexp inst))
    (error () inst)))

(defun %opt-dae-remove-indexes (values indexes)
  "Return VALUES with zero-based INDEXES removed."
  (loop for value in values
        for index from 0
        unless (member index indexes :test #'eql)
          collect value))

(defun %opt-dae-captures-param-p (inst params)
  "Return T when INST captures one of PARAMS, making that parameter live indirectly."
  (and (typep inst 'vm-closure)
       (intersection (or (vm-captured-vars inst) nil) params :test #'eq)))

(defun %opt-dae-unsafe-function-shape-p (closure)
  "Return T when CLOSURE has non-positional calling convention metadata."
  (or (vm-closure-optional-params closure)
      (vm-closure-rest-param closure)
      (vm-closure-key-params closure)))

(defun %opt-dae-absent-param-indexes (params body)
  "Return indexes of PARAMS that are never read by BODY and not captured."
  (let ((read (make-hash-table :test #'eq)))
    (dolist (inst body)
      (dolist (reg (opt-inst-read-regs inst))
        (when (member reg params :test #'eq)
          (setf (gethash reg read) t)))
      (when (%opt-dae-captures-param-p inst params)
        (dolist (param (intersection (vm-captured-vars inst) params :test #'eq))
          (setf (gethash param read) t))))
    (loop for param in params
          for index from 0
          unless (gethash param read)
            collect index)))

(defun %opt-dae-build-specializations (instructions)
  "Return label -> specialization metadata for functions with absent parameters."
  (let ((defs (opt-collect-function-defs instructions))
        (counter 0)
        (specializations (make-hash-table :test #'equal)))
    (maphash
     (lambda (label def)
       (let* ((closure (getf def :closure))
              (params (copy-list (getf def :params)))
              (body (getf def :body)))
         (unless (or (%opt-dae-specialized-label-p label)
                     (null params)
                     (%opt-dae-unsafe-function-shape-p closure))
           (let ((drop-indexes (%opt-dae-absent-param-indexes params body)))
             (when drop-indexes
               (let ((new-label (format nil "~A~A~D" label
                                        *opt-dae-specialized-label-fragment*
                                        (incf counter))))
                 (setf (gethash label specializations)
                       (list :old-label label
                             :new-label new-label
                             :old-params params
                             :new-params (%opt-dae-remove-indexes params drop-indexes)
                             :drop-indexes drop-indexes
                             :body body))))))))
     defs)
    specializations))

(defun %opt-dae-known-label-track (inst name-to-label reg->label)
  "Track simple register-to-function-label facts through INST."
  (typecase inst
    ((or vm-closure vm-func-ref)
     (setf (gethash (vm-dst inst) reg->label) (vm-label-name inst)))
    (vm-const
     (let ((label (and (symbolp (vm-value inst))
                       (gethash (vm-value inst) name-to-label))))
       (if label
           (setf (gethash (vm-dst inst) reg->label) label)
           (remhash (vm-dst inst) reg->label))))
    (vm-move
     (multiple-value-bind (label found-p) (gethash (vm-src inst) reg->label)
       (if found-p
           (setf (gethash (vm-dst inst) reg->label) label)
           (remhash (vm-dst inst) reg->label))))
    (t
     (let ((dst (opt-inst-dst inst)))
       (when dst (remhash dst reg->label))))))

(defun %opt-dae-rewrite-call (inst specialization)
  "Return rewritten call INST and the dropped argument registers."
  (let* ((drop-indexes (getf specialization :drop-indexes))
         (args (copy-list (vm-args inst)))
         (new-args (%opt-dae-remove-indexes args drop-indexes))
         (dropped-args (loop for arg in args
                             for index from 0
                             when (member index drop-indexes :test #'eql)
                               collect arg)))
    (values (typecase inst
              (vm-tail-call (make-vm-tail-call :dst (vm-dst inst)
                                               :func (vm-func-reg inst)
                                               :args new-args))
              (t (make-vm-call :dst (vm-dst inst)
                               :func (vm-func-reg inst)
                               :args new-args)))
            dropped-args)))

(defun %opt-dae-drop-trailing-arg-sets (out dropped-args)
  "Drop immediately preceding pure argument moves for DROPPED-ARGS from reversed OUT."
  (loop while (and out
                   (typep (first out) 'vm-move)
                   (member (vm-dst (first out)) dropped-args :test #'eq))
        do (pop out))
  out)

(defun %opt-dae-append-specialized-bodies (instructions specializations)
  "Append specialized function bodies described by SPECIALIZATIONS."
  (let ((bodies nil))
    (maphash (lambda (label spec)
               (declare (ignore label))
               (push (make-vm-label :name (getf spec :new-label)) bodies)
               (dolist (inst (getf spec :body))
                 (push (%opt-dae-copy-inst inst) bodies)))
             specializations)
    (append instructions (nreverse bodies))))

(defun opt-pass-dead-argument-elimination (instructions)
  "FR-606: create specialized functions with unused positional parameters removed.

This pass is closed-world within the current instruction stream.  Calls whose
callee register is statically known are rewritten to a generated specialized
label and receive a shorter argument list.  Original functions are retained for
unknown call sites and future cross-module/LTO use.  Parameters captured by an
inner closure are treated as used and are never removed."
  (let ((specializations (%opt-dae-build-specializations instructions)))
    (if (zerop (hash-table-count specializations))
        instructions
        (let ((name-to-label (opt-build-function-name-map instructions))
              (reg->label (make-hash-table :test #'eq))
              (out nil)
              (changed nil))
          (dolist (inst instructions)
            (cond
              ((typep inst '(or vm-call vm-tail-call))
               (let* ((label (gethash (vm-func-reg inst) reg->label))
                      (spec (and label (gethash label specializations))))
                 (if (and spec (= (length (vm-args inst))
                                  (length (getf spec :old-params))))
                     (multiple-value-bind (new-call dropped-args)
                         (%opt-dae-rewrite-call inst spec)
                       (setf out (%opt-dae-drop-trailing-arg-sets out dropped-args))
                       (push (make-vm-func-ref :dst (vm-func-reg inst)
                                               :label (getf spec :new-label)
                                               :params (copy-list (getf spec :new-params)))
                             out)
                       (push new-call out)
                       (setf changed t))
                     (push inst out)))
               (%opt-dae-known-label-track inst name-to-label reg->label))
              (t
               (%opt-dae-known-label-track inst name-to-label reg->label)
               (push inst out))))
          (let ((rewritten (nreverse out)))
            (if changed
                (%opt-dae-append-specialized-bodies rewritten specializations)
                instructions))))))
