(in-package :cl-cc/optimize)
;;; ─── Software Pipelining (FR-200) ────────────────────────────────────────

(defparameter *opt-software-pipeline-label-prefix* "__clcc_swp_"
  "Prefix for labels generated by FR-200 software pipelining.")

(defun %opt-swp-loop-cmp-p (inst)
  "Return T when INST is a comparison supported by software pipelining."
  (typep inst '(or vm-lt vm-le vm-gt vm-ge vm-eq vm-num-eq)))

(defun %opt-swp-generated-p (instructions)
  "Return T when INSTRUCTIONS already contain FR-200 generated labels."
  (%opt-generated-label-present-p instructions *opt-software-pipeline-label-prefix*))

(defun %opt-swp-parse-loop-at (vec i)
  "Parse the canonical counted-loop shape used by loop optimizers.

Expected shape:
  Lh: cmp/jz body step jump Lh Lexit:
The returned value is a plist to avoid depending on later roadmap structs."
  (when (and (< (+ i 5) (length vec))
             (typep (aref vec i) 'vm-label)
             (%opt-swp-loop-cmp-p (aref vec (1+ i)))
             (typep (aref vec (+ i 2)) 'vm-jump-zero))
    (let* ((header (aref vec i))
           (cmp (aref vec (1+ i)))
           (jz (aref vec (+ i 2)))
           (header-name (vm-name header))
           (exit-name (vm-label-name jz))
           (exit-index (cfg-find-label-position vec (length vec) exit-name)))
      (when (and exit-index (> exit-index (+ i 4)))
        (let* ((back-index (1- exit-index))
               (back (aref vec back-index))
               (body (loop for k from (+ i 3) below back-index collect (aref vec k)))
               (step (car (last body))))
          (when (and (typep back 'vm-jump)
                     (equal (vm-label-name back) header-name)
                     (typep step 'vm-add)
                     (eq (vm-dst step) (vm-lhs step))
                     (eq (vm-dst step) (vm-lhs cmp))
                     (eq (vm-reg jz) (vm-dst cmp))
                     (not (%opt-has-external-jump-to-label-p vec header-name i exit-index)))
            (list :head-index i
                  :cmp-index (1+ i)
                  :jz-index (+ i 2)
                  :back-index back-index
                  :exit-index exit-index
                  :head-label header-name
                  :exit-label exit-name
                  :body body)))))))

(defun %opt-swp-safe-core-p (core)
  "Return T when CORE can be modulo-scheduled without semantic risk."
  (and (>= (length core) 2)
       (every (lambda (inst)
                (and (opt-inst-cse-eligible-p inst)
                     (member (vm-inst-effect-kind inst) '(:pure :read-only) :test #'eq)
                     (not (%opt-control-or-label-p inst))))
              core)))

(defun opt-modulo-schedule-loop-body (body &key (issue-width 1))
  "Build the DDG for BODY, compute MII, and return a modulo schedule.

Values are (scheduled-core ddg mii).  BODY may include the induction update as
its final instruction; the scheduler excludes that update and lets callers emit
it at the end of the kernel."
  (let ((core (butlast body)))
    (if (not (%opt-swp-safe-core-p core))
        (values core (cfg-build-ddg core :latency-fn #'%opt-inst-latency) 1)
        (let* ((ddg (cfg-build-ddg core :latency-fn #'%opt-inst-latency))
               (mii (cfg-compute-mii ddg :issue-width issue-width))
               (scheduled
                 (sort (loop for node across ddg
                             collect (list :inst (opt-ddg-node-inst node)
                                           :index (opt-ddg-node-index node)
                                           :slot (mod (opt-ddg-node-index node) mii)
                                           :latency (opt-ddg-node-latency node)))
                       (lambda (a b)
                         (or (< (getf a :slot) (getf b :slot))
                             (and (= (getf a :slot) (getf b :slot))
                                  (> (getf a :latency) (getf b :latency)))
                             (and (= (getf a :slot) (getf b :slot))
                                  (= (getf a :latency) (getf b :latency))
                                  (< (getf a :index) (getf b :index))))))))
          (values (mapcar (lambda (entry) (getf entry :inst)) scheduled) ddg mii)))))

(defun %opt-swp-loop-sequence (vec lp)
  "Return original instruction sequence for LP from VEC."
  (loop for k from (getf lp :head-index) to (getf lp :exit-index)
        collect (aref vec k)))

(defun %opt-swp-rewrite-loop (vec lp counter)
  "Generate prologue/kernel/epilogue layout for one scheduled loop."
  (let* ((body (getf lp :body))
         (step (car (last body))))
    (multiple-value-bind (scheduled-core ddg mii)
        (opt-modulo-schedule-loop-body body)
      (declare (ignore ddg mii))
      (if (or (null scheduled-core)
              (not (%opt-swp-safe-core-p (butlast body))))
          (values (%opt-swp-loop-sequence vec lp) nil)
          (let* ((base (format nil "~A~D" *opt-software-pipeline-label-prefix* counter))
                 (prologue-label (format nil "~A_prologue" base))
                 (kernel-label (format nil "~A_kernel" base))
                 (epilogue-label (format nil "~A_epilogue" base))
                 (jz (aref vec (getf lp :jz-index))))
            (values (append (list (aref vec (getf lp :head-index))
                                  (aref vec (getf lp :cmp-index))
                                  (make-vm-jump-zero :reg (vm-reg jz) :label epilogue-label)
                                  (make-vm-label :name prologue-label))
                            ;; Prime the pipeline for the current iteration.
                            (subseq scheduled-core 0 1)
                            (list (make-vm-label :name kernel-label))
                            ;; Kernel carries the remaining modulo slots, then the IV update.
                            (append (rest scheduled-core) (list step))
                            (list (aref vec (getf lp :back-index))
                                  (make-vm-label :name epilogue-label)
                                  (aref vec (getf lp :exit-index))))
                    t))))))

(defun opt-pass-software-pipelining (instructions)
  "FR-200: modulo-schedule canonical loop bodies.

The pass builds a DDG for each pure counted-loop body, computes MII, and emits a
prologue/kernel/epilogue layout.  It is intentionally conservative: side-effecting
or non-canonical loops are preserved, and generated labels make the pass
idempotent in the convergence pipeline."
  (if (%opt-swp-generated-p instructions)
      instructions
      (let* ((vec (coerce instructions 'vector))
             (n (length vec))
             (out nil)
             (changed nil)
             (counter 0)
             (i 0))
        (loop while (< i n)
              do (let ((lp (%opt-swp-parse-loop-at vec i)))
                   (if (null lp)
                       (progn
                         (push (aref vec i) out)
                         (incf i))
                       (multiple-value-bind (seq rewritten-p)
                           (%opt-swp-rewrite-loop vec lp counter)
                         (dolist (inst seq)
                           (push inst out))
                         (when rewritten-p
                           (incf counter)
                           (setf changed t))
                         (setf i (1+ (getf lp :exit-index)))))))
        (if changed (nreverse out) instructions))))
