(in-package :cl-cc/emit)

;;;; RV64GC instruction emitter.
;;;; This file is intentionally an ISA-level encoder: it lowers compact symbolic
;;;; instruction forms to little-endian RISC-V bytes and provides a small
;;;; assembler state used by tests and future target integration.

(defconstant +rv-zero+ 0)
(defconstant +rv-ra+ 1)
(defconstant +rv-sp+ 2)
(defconstant +rv-gp+ 3)
(defconstant +rv-tp+ 4)
(defconstant +rv-t0+ 5)
(defconstant +rv-t1+ 6)
(defconstant +rv-t2+ 7)
(defconstant +rv-s0+ 8)
(defconstant +rv-fp+ 8)
(defconstant +rv-s1+ 9)
(defconstant +rv-a0+ 10)
(defconstant +rv-a1+ 11)
(defconstant +rv-a2+ 12)
(defconstant +rv-a3+ 13)
(defconstant +rv-a4+ 14)
(defconstant +rv-a5+ 15)
(defconstant +rv-a6+ 16)
(defconstant +rv-a7+ 17)
(defconstant +rv-s2+ 18)
(defconstant +rv-s3+ 19)
(defconstant +rv-s4+ 20)
(defconstant +rv-s5+ 21)
(defconstant +rv-s6+ 22)
(defconstant +rv-s7+ 23)
(defconstant +rv-s8+ 24)
(defconstant +rv-s9+ 25)
(defconstant +rv-s10+ 26)
(defconstant +rv-s11+ 27)
(defconstant +rv-t3+ 28)
(defconstant +rv-t4+ 29)
(defconstant +rv-t5+ 30)
(defconstant +rv-t6+ 31)

(defparameter *riscv64-registers*
  '((:zero . 0) (:x0 . 0) (:ra . 1) (:x1 . 1) (:sp . 2) (:x2 . 2)
    (:gp . 3) (:x3 . 3) (:tp . 4) (:x4 . 4)
    (:t0 . 5) (:x5 . 5) (:t1 . 6) (:x6 . 6) (:t2 . 7) (:x7 . 7)
    (:s0 . 8) (:fp . 8) (:x8 . 8) (:s1 . 9) (:x9 . 9)
    (:a0 . 10) (:x10 . 10) (:a1 . 11) (:x11 . 11)
    (:a2 . 12) (:x12 . 12) (:a3 . 13) (:x13 . 13)
    (:a4 . 14) (:x14 . 14) (:a5 . 15) (:x15 . 15)
    (:a6 . 16) (:x16 . 16) (:a7 . 17) (:x17 . 17)
    (:s2 . 18) (:x18 . 18) (:s3 . 19) (:x19 . 19)
    (:s4 . 20) (:x20 . 20) (:s5 . 21) (:x21 . 21)
    (:s6 . 22) (:x22 . 22) (:s7 . 23) (:x23 . 23)
    (:s8 . 24) (:x24 . 24) (:s9 . 25) (:x25 . 25)
    (:s10 . 26) (:x26 . 26) (:s11 . 27) (:x27 . 27)
    (:t3 . 28) (:x28 . 28) (:t4 . 29) (:x29 . 29)
    (:t5 . 30) (:x30 . 30) (:t6 . 31) (:x31 . 31))
  "RV64 integer register and ABI alias map.")

(defparameter *riscv64-fp-registers*
  '((:ft0 . 0) (:f0 . 0) (:ft1 . 1) (:f1 . 1) (:ft2 . 2) (:f2 . 2)
    (:ft3 . 3) (:f3 . 3) (:ft4 . 4) (:f4 . 4) (:ft5 . 5) (:f5 . 5)
    (:ft6 . 6) (:f6 . 6) (:ft7 . 7) (:f7 . 7)
    (:fs0 . 8) (:f8 . 8) (:fs1 . 9) (:f9 . 9)
    (:fa0 . 10) (:f10 . 10) (:fa1 . 11) (:f11 . 11)
    (:fa2 . 12) (:f12 . 12) (:fa3 . 13) (:f13 . 13)
    (:fa4 . 14) (:f14 . 14) (:fa5 . 15) (:f15 . 15)
    (:fa6 . 16) (:f16 . 16) (:fa7 . 17) (:f17 . 17)
    (:fs2 . 18) (:f18 . 18) (:fs3 . 19) (:f19 . 19)
    (:fs4 . 20) (:f20 . 20) (:fs5 . 21) (:f21 . 21)
    (:fs6 . 22) (:f22 . 22) (:fs7 . 23) (:f23 . 23)
    (:fs8 . 24) (:f24 . 24) (:fs9 . 25) (:f25 . 25)
    (:fs10 . 26) (:f26 . 26) (:fs11 . 27) (:f27 . 27)
    (:ft8 . 28) (:f28 . 28) (:ft9 . 29) (:f29 . 29)
    (:ft10 . 30) (:f30 . 30) (:ft11 . 31) (:f31 . 31))
  "RV64D floating-point register and ABI alias map.  fa0-fa7 carry NaN-boxed doubles.")

(defconstant +rv-op+ #x33)
(defconstant +rv-op-imm+ #x13)
(defconstant +rv-load+ #x03)
(defconstant +rv-store+ #x23)
(defconstant +rv-branch+ #x63)
(defconstant +rv-jalr+ #x67)
(defconstant +rv-jal+ #x6f)
(defconstant +rv-lui+ #x37)
(defconstant +rv-auipc+ #x17)
(defconstant +rv-load-fp+ #x07)
(defconstant +rv-store-fp+ #x27)
(defconstant +rv-op-fp+ #x53)
(defconstant +rv-zicond-funct7+ #b0000111)

(defstruct (riscv64-assembler (:constructor %make-riscv64-assembler))
  (target (cl-cc/target:find-target :riscv64))
  (buffer (make-array 0 :element-type '(unsigned-byte 8)
                        :adjustable t :fill-pointer 0))
  (position 0 :type fixnum))

(defun make-riscv64-assembler (&key (target (cl-cc/target:find-target :riscv64)))
  "Create an RV64GC assembler state."
  (%make-riscv64-assembler :target target))

(defun %mask (value bits) (logand value (1- (ash 1 bits))))

(defun %reg (reg)
  (cond ((and (integerp reg) (<= 0 reg 31)) reg)
        ((cl:assoc reg *riscv64-registers*)
         (cdr (cl:assoc reg *riscv64-registers*)))
        (t (error "Unknown RISC-V register: ~S" reg))))

(defun %freg (reg)
  (cond ((and (integerp reg) (<= 0 reg 31)) reg)
        ((cl:assoc reg *riscv64-fp-registers*)
         (cdr (cl:assoc reg *riscv64-fp-registers*)))
        (t (error "Unknown RISC-V floating-point register: ~S" reg))))

(defun %check-signed (value bits context)
  (unless (<= (- (ash 1 (1- bits))) value (1- (ash 1 (1- bits))))
    (error "~A immediate ~D does not fit signed ~D-bit field" context value bits))
  value)

(defun %check-unsigned (value bits context)
  (unless (<= 0 value (1- (ash 1 bits)))
    (error "~A immediate ~D does not fit unsigned ~D-bit field" context value bits))
  value)

(defun %check-halfword-offset (offset context)
  (unless (zerop (logand offset 1))
    (error "~A offset must be 2-byte aligned: ~D" context offset))
  offset)

(defun %push-byte (asm byte)
  (vector-push-extend (%u8 byte) (riscv64-assembler-buffer asm))
  (incf (riscv64-assembler-position asm)))

(defun riscv64-emit-u16 (asm halfword)
  "Append HALFWORD in little-endian order."
  (%push-byte asm halfword)
  (%push-byte asm (ash halfword -8))
  halfword)

(defun riscv64-emit-u32 (asm word)
  "Append WORD in little-endian order."
  (%push-byte asm word)
  (%push-byte asm (ash word -8))
  (%push-byte asm (ash word -16))
  (%push-byte asm (ash word -24))
  word)

(defun riscv64-emit-bytes (asm)
  "Return the assembled byte buffer as a simple vector."
  (coerce (riscv64-assembler-buffer asm) '(simple-array (unsigned-byte 8) (*))))

(defun encode-rv-r (opcode rd funct3 rs1 rs2 funct7)
  (logior opcode (ash (%mask rd 5) 7) (ash (%mask funct3 3) 12)
          (ash (%mask rs1 5) 15) (ash (%mask rs2 5) 20)
          (ash (%mask funct7 7) 25)))

(defun encode-rv-i (opcode rd funct3 rs1 imm)
  (%check-signed imm 12 "I-type")
  (logior opcode (ash (%mask rd 5) 7) (ash (%mask funct3 3) 12)
          (ash (%mask rs1 5) 15) (ash (%mask imm 12) 20)))

(defun encode-rv-shift-i (rd funct3 rs1 shamt funct6)
  (%check-unsigned shamt 6 "RV64 shift")
  (logior +rv-op-imm+ (ash (%mask rd 5) 7) (ash (%mask funct3 3) 12)
          (ash (%mask rs1 5) 15) (ash (%mask shamt 6) 20)
          (ash (%mask funct6 6) 26)))

(defun encode-rv-s (opcode funct3 rs1 rs2 imm)
  (%check-signed imm 12 "S-type")
  (let ((uimm (%mask imm 12)))
    (logior opcode (ash (ldb (byte 5 0) uimm) 7) (ash (%mask funct3 3) 12)
            (ash (%mask rs1 5) 15) (ash (%mask rs2 5) 20)
            (ash (ldb (byte 7 5) uimm) 25))))

(defun encode-rv-b (opcode funct3 rs1 rs2 offset)
  (%check-halfword-offset offset "B-type")
  (%check-signed offset 13 "B-type")
  (let ((uimm (%mask offset 13)))
    (logior opcode
            (ash (ldb (byte 1 11) uimm) 7)
            (ash (ldb (byte 4 1) uimm) 8)
            (ash (%mask funct3 3) 12)
            (ash (%mask rs1 5) 15)
            (ash (%mask rs2 5) 20)
            (ash (ldb (byte 6 5) uimm) 25)
            (ash (ldb (byte 1 12) uimm) 31))))

(defun encode-rv-u (opcode rd imm)
  (logior opcode (ash (%mask rd 5) 7) (logand imm #xfffff000)))

(defun encode-rv-j (opcode rd offset)
  (%check-halfword-offset offset "J-type")
  (%check-signed offset 21 "J-type")
  (let ((uimm (%mask offset 21)))
    (logior opcode (ash (%mask rd 5) 7)
            (ash (ldb (byte 8 12) uimm) 12)
            (ash (ldb (byte 1 11) uimm) 20)
            (ash (ldb (byte 10 1) uimm) 21)
            (ash (ldb (byte 1 20) uimm) 31))))

(defun encode-rv-add (rd rs1 rs2) (encode-rv-r +rv-op+ rd 0 rs1 rs2 0))
(defun encode-rv-sub (rd rs1 rs2) (encode-rv-r +rv-op+ rd 0 rs1 rs2 #x20))
(defun encode-rv-sll (rd rs1 rs2) (encode-rv-r +rv-op+ rd 1 rs1 rs2 0))
(defun encode-rv-srl (rd rs1 rs2) (encode-rv-r +rv-op+ rd 5 rs1 rs2 0))
(defun encode-rv-sra (rd rs1 rs2) (encode-rv-r +rv-op+ rd 5 rs1 rs2 #x20))
(defun encode-rv-xor (rd rs1 rs2) (encode-rv-r +rv-op+ rd 4 rs1 rs2 0))
(defun encode-rv-or (rd rs1 rs2) (encode-rv-r +rv-op+ rd 6 rs1 rs2 0))
(defun encode-rv-and (rd rs1 rs2) (encode-rv-r +rv-op+ rd 7 rs1 rs2 0))
(defun encode-rv-mul (rd rs1 rs2) (encode-rv-r +rv-op+ rd 0 rs1 rs2 1))
(defun encode-rv-div (rd rs1 rs2) (encode-rv-r +rv-op+ rd 4 rs1 rs2 1))
(defun encode-rv-rem (rd rs1 rs2) (encode-rv-r +rv-op+ rd 6 rs1 rs2 1))
(defun encode-rv-czero-eqz (rd rs1 rs2)
  "Encode Zicond CZERO.EQZ rd, rs1, rs2."
  (encode-rv-r +rv-op+ rd #b101 rs1 rs2 +rv-zicond-funct7+))
(defun encode-rv-czero-nez (rd rs1 rs2)
  "Encode Zicond CZERO.NEZ rd, rs1, rs2."
  (encode-rv-r +rv-op+ rd #b111 rs1 rs2 +rv-zicond-funct7+))

(defun encode-rv-addi (rd rs1 imm) (encode-rv-i +rv-op-imm+ rd 0 rs1 imm))
(defun encode-rv-slli (rd rs1 shamt) (encode-rv-shift-i rd 1 rs1 shamt 0))
(defun encode-rv-srli (rd rs1 shamt) (encode-rv-shift-i rd 5 rs1 shamt 0))
(defun encode-rv-srai (rd rs1 shamt) (encode-rv-shift-i rd 5 rs1 shamt #x10))
(defun encode-rv-xori (rd rs1 imm) (encode-rv-i +rv-op-imm+ rd 4 rs1 imm))
(defun encode-rv-ori (rd rs1 imm) (encode-rv-i +rv-op-imm+ rd 6 rs1 imm))
(defun encode-rv-andi (rd rs1 imm) (encode-rv-i +rv-op-imm+ rd 7 rs1 imm))
(defun encode-rv-lb (rd rs1 imm) (encode-rv-i +rv-load+ rd 0 rs1 imm))
(defun encode-rv-lh (rd rs1 imm) (encode-rv-i +rv-load+ rd 1 rs1 imm))
(defun encode-rv-lw (rd rs1 imm) (encode-rv-i +rv-load+ rd 2 rs1 imm))
(defun encode-rv-ld (rd rs1 imm) (encode-rv-i +rv-load+ rd 3 rs1 imm))
(defun encode-rv-sb (rs2 rs1 imm) (encode-rv-s +rv-store+ 0 rs1 rs2 imm))
(defun encode-rv-sh (rs2 rs1 imm) (encode-rv-s +rv-store+ 1 rs1 rs2 imm))
(defun encode-rv-sw (rs2 rs1 imm) (encode-rv-s +rv-store+ 2 rs1 rs2 imm))
(defun encode-rv-sd (rs2 rs1 imm) (encode-rv-s +rv-store+ 3 rs1 rs2 imm))
(defun encode-rv-beq (rs1 rs2 offset) (encode-rv-b +rv-branch+ 0 rs1 rs2 offset))
(defun encode-rv-bne (rs1 rs2 offset) (encode-rv-b +rv-branch+ 1 rs1 rs2 offset))
(defun encode-rv-blt (rs1 rs2 offset) (encode-rv-b +rv-branch+ 4 rs1 rs2 offset))
(defun encode-rv-bge (rs1 rs2 offset) (encode-rv-b +rv-branch+ 5 rs1 rs2 offset))
(defun encode-rv-bltu (rs1 rs2 offset) (encode-rv-b +rv-branch+ 6 rs1 rs2 offset))
(defun encode-rv-bgeu (rs1 rs2 offset) (encode-rv-b +rv-branch+ 7 rs1 rs2 offset))
(defun encode-rv-lui (rd imm) (encode-rv-u +rv-lui+ rd imm))
(defun encode-rv-auipc (rd imm) (encode-rv-u +rv-auipc+ rd imm))
(defun encode-rv-jal (rd offset) (encode-rv-j +rv-jal+ rd offset))
(defun encode-rv-jalr (rd rs1 imm) (encode-rv-i +rv-jalr+ rd 0 rs1 imm))
(defun encode-rv-ret () (encode-rv-jalr +rv-zero+ +rv-ra+ 0))

(defun encode-rv-fld (rd rs1 imm) (encode-rv-i +rv-load-fp+ rd 3 rs1 imm))
(defun encode-rv-fsd (rs2 rs1 imm) (encode-rv-s +rv-store-fp+ 3 rs1 rs2 imm))
(defun encode-rv-fadd-d (rd rs1 rs2 &optional (rm 0)) (encode-rv-r +rv-op-fp+ rd rm rs1 rs2 #x01))
(defun encode-rv-fsub-d (rd rs1 rs2 &optional (rm 0)) (encode-rv-r +rv-op-fp+ rd rm rs1 rs2 #x05))
(defun encode-rv-fmul-d (rd rs1 rs2 &optional (rm 0)) (encode-rv-r +rv-op-fp+ rd rm rs1 rs2 #x09))
(defun encode-rv-fdiv-d (rd rs1 rs2 &optional (rm 0)) (encode-rv-r +rv-op-fp+ rd rm rs1 rs2 #x0d))
(defun encode-rv-fmv-d-x (rd rs1) (encode-rv-r +rv-op-fp+ rd 0 rs1 0 #x79))
(defun encode-rv-fmv-x-d (rd rs1) (encode-rv-r +rv-op-fp+ rd 0 rs1 0 #x71))

(defun %rvc-reg3 (reg)
  (unless (<= 8 reg 15)
    (error "Compressed register must be x8..x15, got x~D" reg))
  (- reg 8))

(defun encode-rvc-addi (rd imm)
  (%check-signed imm 6 "C.ADDI")
  (let ((uimm (%mask imm 6)))
    (logior #b01 (ash #b000 13) (ash (ldb (byte 1 5) uimm) 12)
            (ash (%mask rd 5) 7) (ash (ldb (byte 5 0) uimm) 2))))

(defun encode-rvc-ld (rd rs1 offset)
  (%check-unsigned offset 8 "C.LD")
  (unless (zerop (mod offset 8)) (error "C.LD offset must be 8-byte aligned: ~D" offset))
  (let ((imm (ash offset -3)))
    (logior #b00 (ash #b011 13) (ash (ldb (byte 3 0) imm) 10)
            (ash (%rvc-reg3 rs1) 7) (ash (ldb (byte 2 3) imm) 5)
            (ash (%rvc-reg3 rd) 2))))

(defun encode-rvc-sd (rs2 rs1 offset)
  (%check-unsigned offset 8 "C.SD")
  (unless (zerop (mod offset 8)) (error "C.SD offset must be 8-byte aligned: ~D" offset))
  (let ((imm (ash offset -3)))
    (logior #b00 (ash #b111 13) (ash (ldb (byte 3 0) imm) 10)
            (ash (%rvc-reg3 rs1) 7) (ash (ldb (byte 2 3) imm) 5)
            (ash (%rvc-reg3 rs2) 2))))

(defun encode-rvc-j (offset)
  (%check-halfword-offset offset "C.J")
  (%check-signed offset 12 "C.J")
  (let ((imm (%mask offset 12)))
    (logior #b01 (ash #b101 13)
            (ash (ldb (byte 1 11) imm) 12) (ash (ldb (byte 1 4) imm) 11)
            (ash (ldb (byte 2 8) imm) 9) (ash (ldb (byte 1 10) imm) 8)
            (ash (ldb (byte 1 6) imm) 7) (ash (ldb (byte 1 7) imm) 6)
            (ash (ldb (byte 3 1) imm) 3) (ash (ldb (byte 1 5) imm) 2))))

(defun encode-rvc-jr (rs1)
  (when (zerop rs1) (error "C.JR requires rs1 != x0"))
  (logior #b10 (ash #b1000 12) (ash (%mask rs1 5) 7)))

(defun %encode-rvc-b (funct3 rs1 offset)
  (%check-halfword-offset offset "C.B")
  (%check-signed offset 9 "C.B")
  (let ((imm (%mask offset 9)))
    (logior #b01 (ash funct3 13)
            (ash (ldb (byte 1 8) imm) 12)   ; offset[8]  → bit 12
            (ash (ldb (byte 2 3) imm) 10)   ; offset[4:3] → bits 11:10
            (ash (%rvc-reg3 rs1) 7)          ; rs1'        → bits 9:7
            (ash (ldb (byte 2 6) imm) 5)    ; offset[7:6] → bits 6:5
            (ash (ldb (byte 2 1) imm) 3)    ; offset[2:1] → bits 4:3
            (ash (ldb (byte 1 5) imm) 2))))

(defun encode-rvc-beqz (rs1 offset) (%encode-rvc-b #b110 rs1 offset))
(defun encode-rvc-bnez (rs1 offset) (%encode-rvc-b #b111 rs1 offset))

(defun encode-rvc-ldsp (rd offset)
  "Encode C.LDSP rd, offset(sp). RD must be non-zero; offset unsigned multiple of 8."
  (unless (and (plusp rd) (not (minusp offset)) (zerop (mod offset 8)) (< offset 512))
    (error "C.LDSP requires rd!=x0 and unsigned 8-byte offset <512, got rd=~D offset=~D" rd offset))
  (let ((imm (ash offset -3)))
    (logior #b10 (ash #b011 13) (ash (ldb (byte 1 5) imm) 12)
            (ash rd 7) (ash (ldb (byte 2 3) imm) 5) (ash (ldb (byte 3 0) imm) 2))))

(defparameter *riscv64-r-encoders*
    `((:add . ,#'encode-rv-add) (:sub . ,#'encode-rv-sub) (:and . ,#'encode-rv-and)
     (:or . ,#'encode-rv-or) (:xor . ,#'encode-rv-xor) (:sll . ,#'encode-rv-sll)
     (:srl . ,#'encode-rv-srl) (:sra . ,#'encode-rv-sra) (:mul . ,#'encode-rv-mul)
    (:div . ,#'encode-rv-div) (:rem . ,#'encode-rv-rem)
    (:czero.eqz . ,#'encode-rv-czero-eqz) (:czero.nez . ,#'encode-rv-czero-nez)))

(defparameter *riscv64-i-encoders*
  `((:addi . ,#'encode-rv-addi) (:andi . ,#'encode-rv-andi) (:ori . ,#'encode-rv-ori)
    (:xori . ,#'encode-rv-xori) (:slli . ,#'encode-rv-slli) (:srli . ,#'encode-rv-srli)
    (:srai . ,#'encode-rv-srai) (:ld . ,#'encode-rv-ld) (:lw . ,#'encode-rv-lw)
    (:lh . ,#'encode-rv-lh) (:lb . ,#'encode-rv-lb) (:jalr . ,#'encode-rv-jalr)))

(defparameter *riscv64-s-encoders*
  `((:sd . ,#'encode-rv-sd) (:sw . ,#'encode-rv-sw) (:sh . ,#'encode-rv-sh) (:sb . ,#'encode-rv-sb)))

(defparameter *riscv64-b-encoders*
  `((:beq . ,#'encode-rv-beq) (:bne . ,#'encode-rv-bne) (:blt . ,#'encode-rv-blt)
    (:bge . ,#'encode-rv-bge) (:bltu . ,#'encode-rv-bltu) (:bgeu . ,#'encode-rv-bgeu)))

(defun riscv64-emit-load-immediate (asm rd value)
  "Emit LI lowering.  Signed 32-bit constants use LUI+ADDI when needed."
  (let ((rd (%reg rd)))
    (cond ((<= -2048 value 2047)
           (riscv64-emit-u32 asm (encode-rv-addi rd +rv-zero+ value)))
          ((typep value '(signed-byte 32))
           (let* ((upper (ash (+ value #x800) -12))
                  (lower (- value (ash upper 12))))
             (riscv64-emit-u32 asm (encode-rv-lui rd (ash upper 12)))
             (riscv64-emit-u32 asm (encode-rv-addi rd rd lower))))
          (t (error "RISC-V LI currently supports signed 32-bit constants, got ~D" value)))))

(defun riscv64-emit-pic-call (asm rd symbol-offset &key (scratch :t0))
  "Emit AUIPC+JALR for a PC-relative target offset.  SYMBOL-OFFSET is byte relative."
  (let* ((rd (%reg rd))
         (tmp (%reg scratch))
         (upper (ash (+ symbol-offset #x800) -12))
         (lower (- symbol-offset (ash upper 12))))
    (riscv64-emit-u32 asm (encode-rv-auipc tmp (ash upper 12)))
    (riscv64-emit-u32 asm (encode-rv-jalr rd tmp lower))))

(defun riscv64-emit-prologue (asm &key (save-regs nil) (stack-size 0) (save-ra t))
  "Emit psABI prologue: allocate frame and save RA plus requested saved registers."
  (let* ((regs (append (when save-ra (list :ra)) save-regs))
         (save-bytes (* 8 (length regs)))
         (frame-size (* 16 (ceiling (+ stack-size save-bytes) 16))))
    (when (plusp frame-size)
      (riscv64-emit-u32 asm (encode-rv-addi +rv-sp+ +rv-sp+ (- frame-size))))
    (loop for reg in regs
          for offset from 0 by 8
          do (riscv64-emit-u32 asm (encode-rv-sd (%reg reg) +rv-sp+ offset)))
    frame-size))

(defun riscv64-emit-epilogue (asm &key (save-regs nil) (stack-size 0) (save-ra t))
  "Emit psABI epilogue: restore saved registers, deallocate frame, return.
RA is restored with a full LD; callee-saved regs use compressed C.LDSP where possible."
  (let* ((regs (append (when save-ra (list :ra)) save-regs))
         (save-bytes (* 8 (length regs)))
         (frame-size (* 16 (ceiling (+ stack-size save-bytes) 16))))
    (loop for reg in regs
          for offset from 0 by 8
          do (if (eq reg :ra)
                 (riscv64-emit-u32 asm (encode-rv-ld (%reg reg) +rv-sp+ offset))
                 (riscv64-emit-u16 asm (encode-rvc-ldsp (%reg reg) offset))))
    (when (plusp frame-size)
      (riscv64-emit-u32 asm (encode-rv-addi +rv-sp+ +rv-sp+ frame-size)))
    (riscv64-emit-u32 asm (encode-rv-ret))
    frame-size))

(defun riscv64-emit-instruction (asm inst)
  "Dispatch one symbolic instruction into ASM.

Supported examples: (:add :a0 :a1 :a2), (:ld :a0 :sp 8), (:sd :ra :sp 0),
(:jal :ra 16), (:ret), (:c.addi :sp -16), (:fadd.d :fa0 :fa1 :fa2)."
  (unless (consp inst) (error "Invalid RISC-V instruction: ~S" inst))
  (let ((op (car inst)))
    (cond
      ((cl:assoc op *riscv64-r-encoders*)
       (destructuring-bind (_ rd rs1 rs2) inst
         (declare (ignore _))
         (riscv64-emit-u32 asm (funcall (cdr (cl:assoc op *riscv64-r-encoders*))
                                        (%reg rd) (%reg rs1) (%reg rs2)))))
      ((cl:assoc op *riscv64-i-encoders*)
       (destructuring-bind (_ rd rs1 imm) inst
         (declare (ignore _))
         (riscv64-emit-u32 asm (funcall (cdr (cl:assoc op *riscv64-i-encoders*))
                                        (%reg rd) (%reg rs1) imm))))
      ((cl:assoc op *riscv64-s-encoders*)
       (destructuring-bind (_ rs2 rs1 imm) inst
         (declare (ignore _))
         (riscv64-emit-u32 asm (funcall (cdr (cl:assoc op *riscv64-s-encoders*))
                                        (%reg rs2) (%reg rs1) imm))))
      ((cl:assoc op *riscv64-b-encoders*)
       (destructuring-bind (_ rs1 rs2 offset) inst
         (declare (ignore _))
         (riscv64-emit-u32 asm (funcall (cdr (cl:assoc op *riscv64-b-encoders*))
                                        (%reg rs1) (%reg rs2) offset))))
      ((eq op :lui)   (destructuring-bind (_ rd imm) inst (declare (ignore _))
                       (riscv64-emit-u32 asm (encode-rv-lui (%reg rd) imm))))
      ((eq op :auipc) (destructuring-bind (_ rd imm) inst (declare (ignore _))
                       (riscv64-emit-u32 asm (encode-rv-auipc (%reg rd) imm))))
      ((eq op :jal)   (destructuring-bind (_ rd off) inst (declare (ignore _))
                       (riscv64-emit-u32 asm (encode-rv-jal (%reg rd) off))))
      ((eq op :ret)   (riscv64-emit-u32 asm (encode-rv-ret)))
      ((eq op :li)    (destructuring-bind (_ rd value) inst (declare (ignore _))
                       (riscv64-emit-load-immediate asm rd value)))
      ((eq op :pic-call) (destructuring-bind (_ rd off &optional (scratch :t0)) inst
                          (declare (ignore _)) (riscv64-emit-pic-call asm rd off :scratch scratch)))
      ((eq op :fld)   (destructuring-bind (_ rd rs1 imm) inst (declare (ignore _))
                       (riscv64-emit-u32 asm (encode-rv-fld (%freg rd) (%reg rs1) imm))))
      ((eq op :fsd)   (destructuring-bind (_ rs2 rs1 imm) inst (declare (ignore _))
                       (riscv64-emit-u32 asm (encode-rv-fsd (%freg rs2) (%reg rs1) imm))))
      ((member op '(:fadd.d :fsub.d :fmul.d :fdiv.d))
       (destructuring-bind (_ rd rs1 rs2) inst
         (declare (ignore _))
         (riscv64-emit-u32 asm
                           (funcall (ecase op
                                      (:fadd.d #'encode-rv-fadd-d)
                                      (:fsub.d #'encode-rv-fsub-d)
                                      (:fmul.d #'encode-rv-fmul-d)
                                      (:fdiv.d #'encode-rv-fdiv-d))
                                    (%freg rd) (%freg rs1) (%freg rs2)))))
      ((eq op :fmv.d.x) (destructuring-bind (_ rd rs1) inst (declare (ignore _))
                         (riscv64-emit-u32 asm (encode-rv-fmv-d-x (%freg rd) (%reg rs1)))))
      ((eq op :fmv.x.d) (destructuring-bind (_ rd rs1) inst (declare (ignore _))
                         (riscv64-emit-u32 asm (encode-rv-fmv-x-d (%reg rd) (%freg rs1)))))
      ((eq op :c.addi) (destructuring-bind (_ rd imm) inst (declare (ignore _))
                        (riscv64-emit-u16 asm (encode-rvc-addi (%reg rd) imm))))
      ((eq op :c.ld) (destructuring-bind (_ rd rs1 offset) inst (declare (ignore _))
                      (riscv64-emit-u16 asm (encode-rvc-ld (%reg rd) (%reg rs1) offset))))
      ((eq op :c.sd) (destructuring-bind (_ rs2 rs1 offset) inst (declare (ignore _))
                      (riscv64-emit-u16 asm (encode-rvc-sd (%reg rs2) (%reg rs1) offset))))
      ((eq op :c.j) (destructuring-bind (_ off) inst (declare (ignore _))
                     (riscv64-emit-u16 asm (encode-rvc-j off))))
      ((eq op :c.jr) (destructuring-bind (_ rs1) inst (declare (ignore _))
                      (riscv64-emit-u16 asm (encode-rvc-jr (%reg rs1)))))
      ((eq op :c.beqz) (destructuring-bind (_ rs1 off) inst (declare (ignore _))
                        (riscv64-emit-u16 asm (encode-rvc-beqz (%reg rs1) off))))
      ((eq op :c.bnez) (destructuring-bind (_ rs1 off) inst (declare (ignore _))
                        (riscv64-emit-u16 asm (encode-rvc-bnez (%reg rs1) off))))
      (t (error "Unsupported RISC-V instruction form: ~S" inst)))))

(defun riscv64-emit-function (name instructions &key (save-regs nil) (stack-size 0) (save-ra t))
  "Emit a complete function with prologue, body, epilogue and return bytes.
NAME is stored for API clarity and future symbol-table integration."
  (declare (ignore name))
  (let ((asm (make-riscv64-assembler)))
    (riscv64-emit-prologue asm :save-regs save-regs :stack-size stack-size :save-ra save-ra)
    (dolist (inst instructions)
      (riscv64-emit-instruction asm inst))
    (riscv64-emit-epilogue asm :save-regs save-regs :stack-size stack-size :save-ra save-ra)
    (riscv64-emit-bytes asm)))
