;;;; packages/emit/src/wasm-trampoline.lisp — facade for codegen trampoline builder
;;;;
;;;; The PC-dispatch trampoline implementation lives in
;;;; packages/codegen/src/wasm-trampoline.lisp.  This file intentionally contains
;;;; no lowering logic; it re-exports the trampoline construction helpers through
;;;; CL-CC/EMIT for documentation and compatibility with the spec path.

(in-package :cl-cc/emit)

(eval-when (:compile-toplevel :load-toplevel :execute)
  (%emit-reexport-codegen-symbols
   '("WASM-BASIC-BLOCK" "MAKE-WASM-BASIC-BLOCK" "WASM-BASIC-BLOCK-P"
     "WASM-BB-LABEL" "WASM-BB-PC-INDEX" "WASM-BB-INSTRUCTIONS"
     "GROUP-INTO-BASIC-BLOCKS" "BUILD-LABEL-PC-MAP" "*WASM-LABEL-TO-TABLE-IDX*"
     "REG-LOCAL-REF" "REG-LOCAL-SET" "REG-RECORD-TYPE" "REG-KNOWN-TYPE"
     "REG-CLEAR-TYPE" "WASM-NORMALIZE-ARRAY-ELEMENT-KIND" "WASM-ARRAY-TYPE-NAME"
     "WASM-ARRAY-TYPE-REF" "WASM-ARRAY-REG-RECORD-KIND" "WASM-ARRAY-REG-KIND"
     "WASM-ARRAY-REG-COPY-KIND" "WASM-VECTOR-LITERAL-KIND"
     "WASM-VALUE-TO-ARRAY-ELEMENT-WAT" "WASM-ARRAY-DEFAULT-WAT"
     "WASM-REG-TO-ARRAY-ELEMENT-WAT" "WASM-ARRAY-ELEMENT-TO-EQREF-WAT"
     "WASM-ARRAY-CAST-WAT" "WASM-VECTOR-LITERAL-WAT" "WASM-ARRAY-NEW-WAT"
     "WASM-ARRAY-GET-EQREF-WAT" "WASM-ARRAY-SET-WAT" "WASM-ARRAY-LEN-WAT"
     "WASM-ARRAY-COPY-WAT" "+WASM-I31-MIN+" "+WASM-I31-MAX+" "WASM-I31-RANGE-P"
     "REG-RECORD-FIXNUM-RANGE" "REG-KNOWN-FIXNUM-RANGE" "WASM-RANGE-BINOP"
     "WASM-RANGE-UNARY" "WASM-RANGE-I31-OR-UNKNOWN" "WASM-I64-CONST-WAT-VALUE"
     "WASM-I64-EXTENDED-I31-SOURCE" "WASM-REF-CAST-MAYBE" "WASM-FIXNUM-UNBOX"
     "WASM-FIXNUM-BOX" "WASM-BOOL-TO-I31" "EMIT-WASM-CLOSURE-ALLOCATION"
     "WASM-CLOSURE-REF-WAT" "WASM-I64-BINOP" "WASM-I64-CMP"
     "EMIT-TRAMPOLINE-JUMP-TO-LABEL" "*WASM-BULK-MEMORY-ENABLED*"
     "WASM-MEMORY-COPY-WAT" "WASM-MEMORY-FILL-WAT" "WASM-COPYSIGN-WAT"
     "*WASM-MEMORY-GROW-OOM-CHECK-ENABLED*" "WASM-MEMORY-GROW-CHECKED-WAT"
     "WASM-TRUNC-SAT-F64-I64-WAT" "WASM-TRUNC-SAT-F64-I32-WAT"
     "WASM-SIGN-EXTEND-32-8-WAT" "WASM-SIGN-EXTEND-32-16-WAT"
     "WASM-SIGN-EXTEND-64-32-WAT" "WASM-I64-CLZ-WAT" "WASM-I64-CTZ-WAT"
     "EMIT-TRAMPOLINE-INSTRUCTION" "BUILD-WASM-FUNCTION-WAT"
     "BUILD-ALL-WASM-FUNCTIONS")))
