;;;; packages/emit/src/wasm.lisp — facade for canonical codegen WASM emitter
;;;;
;;;; The implementation of the WebAssembly WAT/binary backend lives in
;;;; packages/codegen/src/wasm.lisp and its companion files.  This bridge exists
;;;; so spec documentation paths under packages/emit/src/ resolve to a loadable
;;;; file while CL-CC/CODEGEN remains the single source of implementation truth.

(in-package :cl-cc/emit)

(eval-when (:compile-toplevel :load-toplevel :execute)
  (%emit-reexport-codegen-symbols
   '("WASM-TARGET" "WASM-TARGET-MODULE" "WASM-TARGET-REG-MAP"
     "WASM-TARGET-KNOWN-FUNC-LABELS" "WASM-TARGET-KNOWN-SLOT-INDEXES"
     "WASM-TARGET-CLASS-SLOT-LAYOUTS" "WASM-TARGET-CLASS-SLOT-ORDERS"
     "WASM-TARGET-KNOWN-CLASS-BY-REG" "WASM-TARGET-KNOWN-OBJECT-CLASS-BY-REG"
     "WASM-TARGET-TRY-STACK" "WASM-TARGET-TRY-DEPTH"
     "EMIT-WAT-TYPE-SECTION" "EMIT-WAT-GLOBALS" "ENSURE-WASM-CONDITION-TAG!"
     "EMIT-WAT-TAGS" "EMIT-WAT-EXCEPTION-HELPER" "EMIT-WAT-TABLE"
     "EMIT-WAT-ELEM" "+WASM-MAX-CALL-ARGS+" "EMIT-WAT-CALL-GLOBALS"
     "EMIT-WAT-FUNCTION-LOCALS" "EMIT-WAT-FUNCTION" "EMIT-WAT-IMPORTS"
     "EMIT-WASM-MODULE" "WASM-BINARY-WRITE-U8" "WASM-BINARY-WRITE-BYTES"
     "WASM-ENCODE-UNSIGNED-LEB128" "WASM-ENCODE-SIGNED-LEB128"
     "WASM-BINARY-WRITE-ULEB128" "WASM-BINARY-SECTION-BUFFER"
     "WASM-BINARY-SECTION-BYTES" "WASM-BINARY-WRITE-SECTION"
     "WASM-BINARY-WRITE-NAME" "WASM-BINARY-VALUE-TYPE-BYTE"
     "WASM-BINARY-WRITE-VALTYPE-VECTOR" "WASM-BINARY-WRITE-FUNC-TYPE"
     "WASM-ENCODE-VM-INSTRUCTION-OPCODE" "WASM-BINARY-MODULE-FUNCTIONS"
     "WASM-BINARY-WRITE-TYPE-SECTION" "WASM-BINARY-WRITE-FUNCTION-SECTION"
     "WASM-BINARY-EXPORT-NAME-FOR-FUNCTION" "WASM-BINARY-WRITE-EXPORT-SECTION"
     "WASM-BINARY-WRITE-LOCAL-DECLS" "WASM-BINARY-FUNCTION-BODY-BYTES"
     "WASM-BINARY-WRITE-CODE-SECTION" "EMIT-WASM-BINARY-MODULE"
     "COMPILE-TO-WASM-BINARY" "EMIT-WASM-BRANCH-HINTS-SECTION"
     "EMIT-WASM-DWARF-SECTIONS" "WASM-SOURCE-MAP-ENABLED-P"
     "EMIT-WASM-SOURCE-MAP-REFERENCE" "WASM-PROFILES-FEATURE-ENABLED-P"
     "EMIT-WASM-PROFILES-SECTION" "WASM-AOT-OPTIMIZE-ENABLED-P"
     "WASM-RUN-BINARYEN-OPTIMIZE" "COMPILE-TO-WASM-WAT")))
