;;;; packages/vm/src/atomics.lisp — VM Atomic Operations (FR-345, FR-346)
(in-package :cl-cc/vm)

(define-vm-instruction vm-atomic-cas (vm-instruction)
  (dst nil :reader vm-dst) (addr-reg nil :reader vm-acas-addr)
  (expected-reg nil :reader vm-acas-expected) (newval-reg nil :reader vm-acas-newval)
  (:sexp-tag :atomic-cas) (:sexp-slots dst addr-reg expected-reg newval-reg))
(defmethod execute-instruction ((inst vm-atomic-cas) state pc labels)
  (declare (ignore labels))
  (let ((addr (vm-reg-get state (vm-acas-addr inst)))
        (expected (vm-reg-get state (vm-acas-expected inst)))
        (newval (vm-reg-get state (vm-acas-newval inst))))
    (vm-reg-set state (vm-dst inst)
                (if (eql addr expected) (progn (vm-reg-set state (vm-acas-addr inst) newval) expected) addr))
    (values (1+ pc) nil nil)))

(define-vm-instruction vm-atomic-swap (vm-instruction)
  (dst nil :reader vm-dst) (addr-reg nil :reader vm-aswap-addr)
  (newval-reg nil :reader vm-aswap-newval)
  (:sexp-tag :atomic-swap) (:sexp-slots dst addr-reg newval-reg))
(defmethod execute-instruction ((inst vm-atomic-swap) state pc labels)
  (declare (ignore labels))
  (let ((addr (vm-reg-get state (vm-aswap-addr inst)))
        (newval (vm-reg-get state (vm-aswap-newval inst))))
    (vm-reg-set state (vm-dst inst) addr)
    (vm-reg-set state (vm-aswap-addr inst) newval)
    (values (1+ pc) nil nil)))

(define-vm-instruction vm-atomic-load (vm-instruction)
  (dst nil :reader vm-dst) (addr-reg nil :reader vm-aload-addr)
  (:sexp-tag :atomic-load) (:sexp-slots dst addr-reg))
(defmethod execute-instruction ((inst vm-atomic-load) state pc labels)
  (declare (ignore labels))
  (vm-reg-set state (vm-dst inst) (vm-reg-get state (vm-aload-addr inst)))
  (values (1+ pc) nil nil))

(define-vm-instruction vm-atomic-store (vm-instruction)
  (addr-reg nil :reader vm-astore-addr) (val-reg nil :reader vm-astore-val)
  (:sexp-tag :atomic-store) (:sexp-slots addr-reg val-reg))
(defmethod execute-instruction ((inst vm-atomic-store) state pc labels)
  (declare (ignore labels))
  (vm-reg-set state (vm-astore-addr inst) (vm-reg-get state (vm-astore-val inst)))
  (values (1+ pc) nil nil))

(define-vm-instruction vm-atomic-incf (vm-instruction)
  (dst nil :reader vm-dst) (addr-reg nil :reader vm-aincf-addr)
  (delta-reg nil :reader vm-aincf-delta)
  (:sexp-tag :atomic-incf) (:sexp-slots dst addr-reg delta-reg))
(defmethod execute-instruction ((inst vm-atomic-incf) state pc labels)
  (declare (ignore labels))
  (let ((addr (vm-reg-get state (vm-aincf-addr inst)))
        (delta (vm-reg-get state (vm-aincf-delta inst))))
    (vm-reg-set state (vm-dst inst) addr)
    (vm-reg-set state (vm-aincf-addr inst) (+ addr delta))
    (values (1+ pc) nil nil)))

(define-vm-instruction vm-memory-barrier (vm-instruction) (:sexp-tag :memory-barrier))
(defmethod execute-instruction ((inst vm-memory-barrier) state pc labels)
  (declare (ignore inst state labels)) (values (1+ pc) nil nil))

(define-vm-instruction vm-load-fence (vm-instruction) (:sexp-tag :load-fence))
(defmethod execute-instruction ((inst vm-load-fence) state pc labels)
  (declare (ignore inst state labels)) (values (1+ pc) nil nil))

(define-vm-instruction vm-store-fence (vm-instruction) (:sexp-tag :store-fence))
(defmethod execute-instruction ((inst vm-store-fence) state pc labels)
  (declare (ignore inst state labels)) (values (1+ pc) nil nil))
