(in-package :cl-cc/vm)

;;; VM instruction exports grouped by category.
;;;
;;; The long constructor lists live in adjacent helper files so this top-level
;;; export surface keeps the high-signal symbols (instruction names, predicates,
;;; accessors, and defining macros) easy to scan.

(export
 '(vm-cons-cell-car
   vm-cons-cell-cdr
   vm-closure-object
   vm-closure-entry-label
   vm-closure-params
   vm-closure-captured-values
   vm-instruction
   vm-const
   vm-move
   vm-binop
   vm-add
   vm-integer-add
   vm-integer-sub
   vm-integer-mul
   vm-float-add
   vm-float-sub
   vm-float-mul
   vm-float-div
   vm-sub
   vm-mul
   vm-label
   vm-jump
   vm-jump-zero
   vm-print
   vm-halt
   vm-closure
   vm-call
   vm-tail-call
   vm-ret
   vm-func-ref
   vm-push
   vm-pop
   vm-values
   vm-spread-values
   vm-mv-bind
   vm-dst-regs
   vm-lcm
   vm-gcd
   vm-ash
   vm-rotate
   vm-bswap
   vm-logand
   vm-logior
   vm-logxor
   vm-logeqv
   vm-logtest
   vm-logbitp
   vm-logcount
   vm-integer-length
   vm-min
   vm-max
   vm-rem
   vm-mod
   vm-div
   vm-truncate
   vm-floor-inst
   vm-ceiling-inst
   vm-round-inst
   vm-lognot
   vm-rational
   vm-rationalize
   vm-numerator
   vm-denominator
   vm-make-array
   vm-eq
   vm-num-eq
   vm-lt
   vm-gt
   vm-le
   vm-ge
   vm-and
   vm-or
   vm-abs
   vm-inc
   vm-dec
   vm-not
   vm-concatenate
   vm-select
   vm-cons-p
   vm-symbol-p
   vm-number-p
   vm-integer-p
   vm-function-p
   vm-apply
   vm-register-function
   vm-function-registry
   vm-resolve-function
   vm-register-host-bridge
   *vm-host-bridge-functions*
   vm-generic-function-p
   vm-resolve-gf-method
   vm-set-global
   vm-get-global
   vm-global-name
   vm-global-vars
   vm-values-list
   vm-establish-handler
   vm-remove-handler
   vm-signal-error
   vm-sync-handler-regs
   vm-handler-label
   vm-handler-result-reg
   vm-error-type
   vm-error-reg
   vm-establish-catch
   vm-throw
   vm-catch-tag-reg
   vm-catch-handler-label
   vm-catch-result-reg
   vm-throw-tag-reg
   vm-throw-value-reg
   vm-handler-stack
   vm-closure-p
   vm-const-p
   vm-jump-p
   vm-label-p
   vm-ret-p
   vm-add-p
   vm-call-p
   vm-move-p
   vm-neg-p
   vm-array-adjustable-p
   vm-array-has-fill-pointer-p
   vm-input-stream-p
   vm-interactive-stream-p
   vm-next-method-p
   vm-open-stream-p
   vm-output-stream-p
   vm-alpha-char-p
   vm-digit-char-p
   vm-graphic-char-p
   vm-standard-char-p
   vm-lower-case-p
   vm-upper-case-p
   vm-both-case-p
   vm-sub-p
   vm-const-value
   vm-move-dst
   vm-move-src
   vm-lbl-name
   vm-gethash-default
   vm-make-array-fill-pointer
   vm-make-hash-table-test
   vm-typep-type-name
   vm-call-next-method-args-reg
   vm-make-string-char
   vm-closure-rest-stack-alloc-p
   vm-func-name
   vm-parts
   vm-size-reg
   vm-initial-element
   vm-fill-pointer
   vm-adjustable
   vm-make-array-adjustable
   define-vm-instruction
   define-simple-instruction
   define-vm-unary-instruction
   define-vm-binary-instruction
   define-vm-char-comparison
   rotate-right
   bswap))
