(in-package :cl-cc/vm)

;;; Object-system, dispatch, bridge, and environment exports.

(export
 '(vm-class-def
   vm-class-name-sym
   vm-superclasses
   vm-slot-names
   vm-slot-initargs
   vm-class-slots
   vm-make-obj
   vm-class-reg
   vm-initarg-regs
   vm-slot-read
   vm-obj-reg
   vm-slot-name-sym
   vm-slot-write
   vm-value-reg
   vm-register-method
   vm-gf-reg
   vm-method-specializer
   vm-method-qualifier
   vm-method-reg
   vm-generic-call
   collect-inherited-slots
   collect-inherited-initargs
   compute-class-precedence-list
   vm-class-registry
   %resolve-combination-operator
   *method-combination-operators*
   vm-classify-arg
   %eql-specializer-p
   %eql-specializer-matches-p
   %vm-extract-eql-specializer-keys
   %vm-gf-eql-methods
   %vm-resolve-single-dispatch
   %vm-gf-uses-composite-keys-p
   vm-try-dispatch-combinations
   vm-try-dispatch-sub
   vm-label-table-lookup
   vm-label-table-store
   vm-push-call-frame
   vm-save-registers
   vm-restore-registers
   vm-save-registers-subset
   vm-restore-registers-subset
   vm-adjust-sequence
   vm-sequence-elt
   vm-sequence-length
   vm-make-sequence-like
   vm-hash-cons
   vm-clear-hash-cons-table
   vm-arg-slot-name
   vm-bind-arg-slots
   vm-bind-closure-args
   vm-closure-optional-params
   vm-closure-key-params
   vm-closure-rest-param
   resolve-hash-test
   hash-table-values
   %class-slot-initargs-for-slot
   %class-slot-metadata
   %class-slot-definitions
   slot-definition-name
   slot-definition-initform
   slot-definition-initargs
   slot-definition-allocation
   generic-function-methods
   generic-function-method-combination
   %package-symbols
   %package-external-symbols
   %all-symbols
   vm-heap-object
   vm-heap-address
   make-vm-heap-address
   vm-heap-address-value
   vm-heap-address-p
   vm-cons-cell
   make-vm-program
   vm-program-p
   vm-aref
   vm-aset
   vm-array-row-major-index
   vm-call-next-method
   vm-encode-universal-time
   vm-format-inst
   vm-fresh-line-inst
   vm-listen-inst
   vm-make-string
   vm-prin1
   vm-princ
   vm-print-inst
   vm-read-byte
   vm-terpri-inst
   vm-values-to-list
   vm-write-to-string-inst
   run-compiled
   run-program-slice
   make-vm-state
   make-vm2-state
   vm2-state-p
   vm2-state-registers
   vm2-state-values-buffer
   vm2-state-output-stream
   vm2-state-global-vars
   vm-output-stream
   vm-global-vars
   vm-profile-enabled-p
   vm-profile-call-stack
   vm-profile-samples
   *instruction-constructors*
   vm-falsep
   vm-program-leaf-p
   vm-error-type-matches-p
   clone-vm-state
   %documentation-table*
   *documentation-table*
   *vm-eval-hook*
   *vm-macroexpand-1-hook*
   *vm-macroexpand-hook*
   *vm-compile-string-hook*
   *vm-parse-forms-hook*
   refine))
