;;;; exports-runtime.lisp — VM state, execution, I/O, strings, hash
;;;;
;;;; This file exports runtime-related symbols for the :cl-cc/vm package.
;;;; Object-system, dispatch, bridge, and environment exports live in
;;;; exports-runtime-objects.lisp.

(in-package :cl-cc/vm)

#-cl-cc-self-hosting
(export
 '(vm-cons
   vm-car
   vm-cdr
   vm-rplaca
   vm-rplacd
   vm-make-closure
   vm-make-closure-params
   vm-env-regs
   vm-closure-ref-idx
   vm-closure-reg
   vm-closure-index
   vm-program
   vm-program-instructions
   vm-program-result-register
   vm-state
   vm-state-registers
   vm-state-heap
   vm-heap-counter
   vm-call-stack
   vm-method-call-stack
   vm-closure-env
   vm-heap-alloc
   vm-heap-get
   vm-heap-set
   vm-reg-get
   vm-reg-set
   execute-instruction
   instruction->sexp
   sexp->instruction
   build-label-table
   vm-dst
   vm-src
   vm-lhs
   vm-rhs
   vm-name
   vm-label-name
   vm-reg
   vm-value
   vm-captured-vars
   vm-func-reg
   vm-args
   vm-var-name
   vm-null-p
   vm-select-cond-reg
   vm-select-then-reg
   vm-select-else-reg
   vm-neg
   vm-length
   vm-reverse
   vm-append
   vm-member
   vm-nth
   vm-nthcdr
   vm-first
   vm-second
   vm-third
   vm-fourth
   vm-fifth
   vm-sixth
   vm-seventh
   vm-eighth
   vm-ninth
   vm-tenth
   vm-rest
   vm-last
   vm-butlast
   vm-nbutlast
   vm-nreconc
   vm-identity
   vm-constantly
   vm-complement
   vm-list-length
   vm-endp
   vm-null
   vm-car-reg
   vm-cdr-reg
   vm-src-regs
   vm-item-reg
   vm-list-reg
   vm-index-reg
   vm-cons-reg
   vm-val-reg
   vm-io-state
   vm-open-files
   vm-file-counter
   vm-standard-input
   vm-standard-output
   vm-string-streams
   +stdin-handle+
   +stdout-handle+
   +eof-value+
   vm-get-stream
   vm-allocate-file-handle
   vm-stream-open-p
   run-compiled-with-io
   run-string-with-io
   vm-open-file
   vm-close-file
   vm-read-char
   vm-read-line
   vm-write-char
   vm-write-string
   vm-peek-char
   vm-unread-char
   vm-file-position
   vm-file-length
   vm-eof-p
   vm-make-string-stream
   vm-get-string-from-stream
   vm-file-handle
   vm-file-direction
   vm-char-reg
   vm-str-reg
   vm-position-reg
   vm-stream-direction
   vm-initial-string
   vm-read-sexp
   vm-print-sexp
   vm-prin1-sexp
   vm-princ-sexp
   vm-make-string-output-stream-inst
   vm-get-output-stream-string-inst
   vm-stream-write-string-inst
   vm-read-from-string-inst
   vm-read-sexp-inst
   vm-eval
   vm-type-of
   vm-make-list
   vm-alphanumericp
   vm-reader-read
   vm-open-file-direction
   vm-make-string-stream-direction
   vm-list-to-lisp-list
   vm-build-list
   vm-string=
   vm-string<
   vm-string>
   vm-string<=
   vm-string>=
   vm-string-equal
   vm-string-lessp
   vm-string-greaterp
   vm-string-not-equal
   vm-string-length
   vm-char
   vm-char-code
   vm-code-char
   vm-char=
   vm-char<
   vm-subseq
   vm-string-upcase
   vm-string-downcase
   vm-string-capitalize
   vm-nstring-upcase
   vm-nstring-downcase
   vm-nstring-capitalize
   vm-string-trim
   vm-string-left-trim
   vm-string-right-trim
   vm-search-string
   vm-string-set
   vm-str1
   vm-str2
   vm-string-reg
   vm-index
   vm-char1
   vm-char2
   vm-start
   vm-end
   vm-char-bag
   vm-pattern
   vm-hash-table-object
   vm-hash-table-internal
   vm-make-hash-table
   vm-gethash
   vm-sethash
   vm-remhash
   vm-clrhash
   vm-hash-table-count
   vm-hash-table-p
   vm-hash-table-keys
   vm-hash-table-values
   vm-hash-table-test
   vm-hash-table-size
   vm-hash-table-rehash-size
   vm-hash-table-rehash-threshold
   vm-hash-test
   vm-found-dst
   vm-hash-key
   vm-hash-value
   vm-hash-table-reg
   vm-hash-default
   vm-hash-fn))
