(in-package :cl-cc/vm)

;;; Constructor exports: core arithmetic, collection, character, and dispatch
;;; instruction builders.

(export
 '(make-vm-instruction
   make-vm-abs
   make-vm-acons
   make-vm-add
   make-vm-alpha-char-p
   make-vm-integer-add
   make-vm-integer-sub
   make-vm-integer-mul
   make-vm-float-add
   make-vm-float-sub
   make-vm-float-mul
   make-vm-float-div
   make-vm-alphanumericp
   make-vm-and
   make-vm-append
   make-vm-apply
   make-vm-adjust-array
   make-vm-aref
   make-vm-aref-multi
   vm-aref-multi
   make-vm-array-length
   make-vm-aset
   make-vm-assoc
   make-vm-array-adjustable-p
   make-vm-array-dimension
   make-vm-array-dimensions
   make-vm-array-displacement
   make-vm-array-has-fill-pointer-p
   make-vm-array-rank
   make-vm-array-row-major-index
   make-vm-array-total-size
   make-vm-atom
   make-vm-binop
   make-vm-bit-access
   make-vm-bit-and
   make-vm-bit-not
   make-vm-bit-or
   make-vm-bit-set
   make-vm-bit-xor
   make-vm-butlast
   make-vm-sbit
   make-vm-call
   make-vm-tail-call
   make-vm-call-next-method
   make-vm-car
   make-vm-cdr
   make-vm-ceiling-inst
   make-vm-cerror
   make-vm-char
   make-vm-char-code
   make-vm-char-downcase
   make-vm-char-not-greaterp
   make-vm-char-not-lessp
   make-vm-char-upcase
   make-vm-char<
   make-vm-char=
   make-vm-characterp
   make-vm-class-def
   make-vm-close-file
   make-vm-closure
   make-vm-closure-ref-idx
   make-vm-clrhash
   make-vm-code-char
   make-vm-coerce-to-list
   make-vm-coerce-to-string
   make-vm-coerce-to-vector
   make-vm-clear-values
   make-vm-concatenate
   make-vm-cons
   make-vm-cons-p
   make-vm-const
   make-vm-complex
   make-vm-conjugate
   make-vm-copy-list
   make-vm-copy-tree
   make-vm-dec
   make-vm-denominator
   make-vm-digit-char-p
   make-vm-digit-char
   make-vm-both-case-p
   make-vm-graphic-char-p
   make-vm-standard-char-p
   make-vm-char-name
   make-vm-name-char
   make-vm-div
   make-vm-cl-div
   vm-cl-div
   make-vm-endp
   make-vm-eof-p
   make-vm-eq
   make-vm-equal
   make-vm-establish-handler
   make-vm-establish-catch
   make-vm-ensure-values
   make-vm-eval
   make-vm-macroexpand-1-inst
   make-vm-macroexpand-inst
   vm-macroexpand-1-inst
   vm-macroexpand-inst
   make-vm-sxhash
   vm-sxhash
   make-vm-class-name-fn
   make-vm-class-of-fn
   make-vm-find-class
   vm-class-name-fn
   vm-class-of-fn
   vm-find-class
   make-vm-evenp
   make-vm-fceiling
   make-vm-ffloor
   make-vm-fifth
   make-vm-sixth
   make-vm-seventh
   make-vm-eighth
   make-vm-ninth
   make-vm-tenth
   make-vm-file-length
   make-vm-fill-pointer-inst
   make-vm-file-position
   make-vm-first
   make-vm-floor-inst
   make-vm-fdefinition
   make-vm-format-inst
   make-vm-fourth
   make-vm-fround
   make-vm-fresh-line-inst
   make-vm-ftruncate
   make-vm-func-ref
   make-vm-function-p
   make-vm-ge
   make-vm-generic-call
   make-vm-select
   make-vm-generic-add
   make-vm-generic-sub
   make-vm-generic-mul
   make-vm-generic-div
   make-vm-generic-eq
   make-vm-generic-lt
   make-vm-generic-gt
   vm-generic-add
   vm-generic-sub
   vm-generic-mul
   vm-generic-div
   vm-generic-eq
   vm-generic-lt
   vm-generic-gt
   make-vm-gensym-inst
   make-vm-get-global
   make-vm-get-output-stream-string-inst
   make-vm-get-string-from-stream
   make-vm-get-universal-time
   make-vm-get-internal-real-time
   make-vm-get-internal-run-time
   make-vm-decode-universal-time
   make-vm-encode-universal-time
   make-vm-lisp-implementation-type
   make-vm-lisp-implementation-version
   make-vm-machine-type
   make-vm-machine-version
   make-vm-machine-instance
   make-vm-software-type
   make-vm-software-version
   make-vm-short-site-name
   make-vm-long-site-name
   make-vm-gcd
   make-vm-gethash
   make-vm-gt
   make-vm-halt
   make-vm-hash-table-count
   make-vm-hash-table-keys
   make-vm-hash-table-p
   make-vm-hash-table-test
   make-vm-hash-table-values
   make-vm-hash-table-size
   make-vm-hash-table-rehash-size
   make-vm-hash-table-rehash-threshold
   make-vm-inc
   make-vm-integer-p
   make-vm-imagpart))
