(in-package :cl-cc/vm)

;;; Constructor exports: runtime, I/O, string, symbol, and stream builders.

#-cl-cc-self-hosting
(export
 '(make-vm-find-package
   make-vm-find-symbol
   make-vm-intern-symbol
   make-vm-jump
   make-vm-jump-zero
   make-vm-keywordp
   make-vm-label
   make-vm-last
   make-vm-lcm
   make-vm-le
   make-vm-length
   make-vm-list-length
   make-vm-listp
   make-vm-lower-case-p
   make-vm-lt
   make-vm-make-array
   make-vm-make-closure
   make-vm-make-hash-table
   make-vm-make-list
   make-vm-make-obj
   make-vm-make-string-output-stream-inst
   make-vm-make-string-stream
   make-vm-make-symbol
   make-vm-max
   make-vm-member
   make-vm-min
   make-vm-mod
   make-vm-move
   make-vm-mul
   make-vm-mv-bind
   make-vm-makunbound
   make-vm-nconc
   make-vm-nreconc
   make-vm-nbutlast
   make-vm-neg
   make-vm-not
   make-vm-nreverse
   make-vm-nth
   make-vm-numerator
   make-vm-identity
   make-vm-constantly
   make-vm-complement
   make-vm-next-method-p
   make-vm-nthcdr
   make-vm-null
   make-vm-null-p
   make-vm-num-eq
   make-vm-number-p
   make-vm-oddp
   make-vm-open-file
   make-vm-or
   make-vm-parse-integer
   make-vm-peek-char
   make-vm-phase
   make-vm-pop
   make-vm-progv-enter
   make-vm-progv-exit
   make-vm-prin1
   make-vm-prin1-sexp
   make-vm-princ
   make-vm-princ-sexp
   make-vm-print
   make-vm-print-inst
   make-vm-print-sexp
   make-vm-push
   make-vm-read-char
   make-vm-read-from-string-inst
   make-vm-read-from-string-rp
   make-vm-read-line
   make-vm-read-sexp
   make-vm-read-sexp-inst
   make-vm-reader-advance-rp
   make-vm-reader-peek-rp
   make-vm-reader-read
   make-vm-register-function
   make-vm-register-method
   make-vm-rational
   make-vm-rationalize
   make-vm-realpart
   make-vm-random
   make-vm-make-random-state
   make-vm-rem
   make-vm-remhash
   make-vm-remove-handler
   make-vm-remprop
   make-vm-rest
   make-vm-row-major-aref
   make-vm-ret
   make-vm-reverse
   make-vm-rplaca
   make-vm-rplacd
   make-vm-search-string
   make-vm-second
   make-vm-set-global
   make-vm-sethash
   make-vm-signal
   make-vm-signal-error
   make-vm-sleep-inst
   make-vm-slot-read
   make-vm-slot-write
   make-vm-stream-write-string-inst
   make-vm-string-capitalize
   make-vm-string-coerce
   make-vm-string-downcase
   make-vm-string-equal
   make-vm-string-greaterp
   make-vm-string-left-trim
   make-vm-string-length
   make-vm-string-lessp
   make-vm-string-not-equal
   make-vm-string-not-greaterp
   make-vm-string-not-lessp
   make-vm-string-right-trim
   make-vm-string-trim
   make-vm-string-upcase
   make-vm-nstring-upcase
   make-vm-nstring-downcase
   make-vm-nstring-capitalize
   make-vm-string<
   make-vm-string<=
   make-vm-string=
   make-vm-string>
   make-vm-string>=
   make-vm-stringp
   make-vm-string-set
   make-vm-sub
   make-vm-subseq
   make-vm-subst
   make-vm-set-fill-pointer
   make-vm-set-symbol-plist
   vm-slot-boundp
   make-vm-slot-boundp
   vm-slot-exists-p
   make-vm-slot-exists-p
   vm-slot-makunbound
   make-vm-slot-makunbound
   make-vm-svref
   make-vm-svset
   make-vm-symbol-get
   make-vm-symbol-name
   make-vm-symbol-p
   make-vm-symbol-plist
   make-vm-symbol-set
   make-vm-set-symbol-value
   make-vm-sync-handler-regs
   make-vm-terpri-inst
   make-vm-third
   make-vm-throw
   make-vm-truncate
   make-vm-type-of
   vm-typep
   make-vm-typep
   make-vm-unread-char
   make-vm-upper-case-p
   make-vm-values
   make-vm-spread-values
   make-vm-values-to-list
   make-vm-vector-pop
   make-vm-vector-push
   make-vm-vector-push-extend
   make-vm-vectorp
   vm-simple-vector-p
   make-vm-simple-vector-p
   make-vm-warn
   make-vm-write-byte
   make-vm-write-char
   make-vm-write-line
   make-vm-write-string
   make-vm-write-to-string-inst
   make-vm-write-to-string-rp
   make-vm-princ-to-string-inst
   vm-princ-to-string-inst
   make-vm-streamp
   make-vm-input-stream-p
   make-vm-output-stream-p
   make-vm-open-stream-p
   make-vm-interactive-stream-p
   make-vm-stream-element-type-inst
   make-vm-read-byte
   make-vm-listen-inst
   make-vm-force-output
   make-vm-finish-output
   make-vm-clear-input
   make-vm-clear-output
   make-vm-load-file
   make-vm-char-not-equal
   make-vm-char-lessp
   make-vm-char-greaterp
   make-vm-char>
   make-vm-char<=
   make-vm-char>=
   make-vm-char/=
   make-vm-make-string))
