;;;; exports-runtime.lisp — VM state, execution, I/O, strings, hash
;;;;
;;;; This file exports runtime-related symbols for the :cl-cc/vm package.
;;;; Object-system, dispatch, bridge, and environment exports live in
;;;; exports-runtime-objects.lisp.

(in-package :cl-cc/vm)

#-cl-cc-self-hosting
(export
 '(vm-cons
   vm-hash-cons
   vm-car
   vm-cdr
   vm-rplaca
   vm-rplacd
   vm-make-closure
   vm-make-closure-params
   vm-env-regs
   vm-closure-ref-idx
   vm-closure-reg
   vm-closure-index
    vm-program
    vm-program-instructions
    vm-program-result-register
    vm-program-calling-convention
     vm-program-function-conventions
     vm-program-deopt-info
     vm-program-osr-entry-points
     vm-program-tier1-entry-points
     vm-program-compilation-tier
     *deopt-enabled*
     *osr-enabled*
    vm-state
    make-vm-instance
    transfer-value
    vm-parent-environment
    make-vm-parent-environment
    vm-parent-environment-globals
    vm-parent-environment-functions
    vm-parent-environment-symbols
    vm-instance-parent-env
    vm-instance-lock
    with-vm-instance-lock
    vm-instance-global-value
    vm-instance-function-value
    vm-state-registers
   vm-state-heap
   vm-heap-counter
    vm-call-stack
    vm-current-deopt-frame
    vm-deopt-history
    vm-tier1-code
     vm-capture-deopt-frame
     vm-reconstruct-interpreter-frame
     vm-trigger-deopt
     vm-register-tier1-osr-entry
     vm-osr-register-map
     vm-materialize-osr-frame
     vm-compile-osr-entry-if-hot
     vm-osr-stub-enter
   vm-method-call-stack
   vm-closure-env
   vm-heap-alloc
   vm-heap-get
   vm-heap-set
   vm-reg-get
   vm-reg-set
    execute-instruction
    vm-print-backtrace
    instruction->sexp
   sexp->instruction
   build-label-table
   vm-dst
   vm-src
   vm-lhs
   vm-rhs
    vm-name
    vm-label-name
    vm-reg
   vm-value
   vm-captured-vars
    vm-func-reg
    vm-args
    vm-tail-p
    vm-var-name
   vm-null-p
   vm-select-cond-reg
   vm-select-then-reg
   vm-select-else-reg
   vm-neg
   vm-length
   vm-reverse
   vm-append
   vm-member
   vm-nth
   vm-nthcdr
   vm-first
   vm-second
   vm-third
   vm-fourth
   vm-fifth
   vm-sixth
   vm-seventh
   vm-eighth
   vm-ninth
   vm-tenth
   vm-rest
   vm-last
   vm-butlast
   vm-nbutlast
   vm-nreconc
   vm-identity
   vm-constantly
   vm-complement
   vm-list-length
   vm-endp
   vm-null
   vm-car-reg
   vm-cdr-reg
   vm-src-regs
   vm-item-reg
   vm-list-reg
   vm-index-reg
   vm-cons-reg
   vm-val-reg
   vm-io-state
   vm-open-files
   vm-file-counter
   vm-standard-input
   vm-standard-output
   vm-string-streams
   +stdin-handle+
   +stdout-handle+
    +eof-value+
    vm-socket
    vm-socket-p
    make-tcp-socket
    make-udp-socket
    socket-connect
    socket-bind
    socket-listen
    socket-accept
    socket-send
    socket-receive
    socket-close
    with-socket
    make-socket-stream
    socket-local-address
    dns-resolve
    dns-reverse-resolve
    getaddrinfo
    dns-resolve-async
    dns-async-result
    dns-async-result-p
    dns-async-result-done-p
    dns-async-result-result
    dns-async-result-error
    make-tls-context
    tls-server-context
    tls-wrap-socket
    tls-socket-stream
    tls-unsupported
    mmap-file
    mmap-array
    mmap-close
    with-mmap
    mmap-sync
    mmap-advice
    vm-get-stream
   vm-allocate-file-handle
   vm-stream-open-p
   run-compiled-with-io
   run-string-with-io
   vm-open-file
   vm-close-file
   vm-read-char
   vm-read-line
   vm-write-char
   vm-write-string
   vm-peek-char
   vm-unread-char
   vm-file-position
   vm-file-length
   vm-eof-p
    vm-make-string-stream
    vm-get-string-from-stream
    fundamental-stream
    fundamental-character-input-stream
    fundamental-character-output-stream
    fundamental-binary-input-stream
    fundamental-binary-output-stream
    fundamental-character-stream
    fundamental-binary-stream
    stream-read-char
    stream-unread-char
    stream-read-char-no-hang
    stream-peek-char
    stream-listen
    stream-read-line
    stream-clear-input
    stream-write-char
    stream-write-string
    stream-terpri
    stream-fresh-line
    stream-finish-output
    stream-force-output
    stream-clear-output
    stream-advance-to-column
    stream-line-column
    stream-start-line-p
    stream-read-byte
    stream-write-byte
    vm-file-handle
   vm-file-direction
   vm-char-reg
   vm-str-reg
   vm-position-reg
   vm-stream-direction
   vm-initial-string
   vm-read-sexp
   vm-print-sexp
   vm-prin1-sexp
   vm-princ-sexp
   vm-make-string-output-stream-inst
   vm-get-output-stream-string-inst
    vm-stream-write-string-inst
    vm-read-from-string-inst
     vm-read-sexp-inst
     *print-base*
     *print-radix*
     *print-circle*
     *print-pretty*
     *print-level*
     *print-length*
     *print-readably*
     *print-pprint-dispatch*
     with-standard-io-syntax
     pprint-logical-block
     pprint-indent
     pprint-newline
     pprint-tab
     pprint-dispatch-table
     make-pprint-dispatch-table
     pprint-dispatch-table-p
     copy-pprint-dispatch
     set-pprint-dispatch
     get-pprint-dispatch
     *readtable*
     make-readtable
     copy-readtable
     set-macro-character
     get-macro-character
     set-dispatch-macro-character
     get-dispatch-macro-character
     readtable-case
     vm-eval
    vm-type-of
    vm-type-rep
    vm-type-rep-p
    make-vm-type-rep
    vm-type-rep-specifier
    vm-type-rep-equal
    vm-type-rep-of
    vm-runtime-type-of
    vm-dynamic
    vm-dynamic-p
    make-vm-dynamic
    vm-dynamic-type-rep
    vm-dynamic-value
    vm-wrap-dynamic
    vm-unwrap-dynamic
    vm-cast-with-type-rep
    vm-make-list
    vm-alphanumericp
    vm-reader-read
   vm-open-file-direction
   vm-make-string-stream-direction
   vm-list-to-lisp-list
   vm-build-list
   vm-string=
   vm-string<
   vm-string>
   vm-string<=
   vm-string>=
   vm-string-equal
   vm-string-lessp
   vm-string-greaterp
   vm-string-not-equal
   vm-string-length
   vm-char
   vm-char-code
   vm-code-char
   vm-char=
   vm-char<
   vm-subseq
   vm-string-upcase
   vm-string-downcase
   vm-string-capitalize
   vm-nstring-upcase
   vm-nstring-downcase
   vm-nstring-capitalize
   vm-string-trim
   vm-string-left-trim
   vm-string-right-trim
   vm-search-string
    vm-string-set
     *runtime-string-table*
     *rt-string-dedup-table*
    rt-string-dedup
    rt-string-intern
   vm-str1
   vm-str2
   vm-string-reg
   vm-index
   vm-char1
   vm-char2
   vm-start
   vm-end
   vm-char-bag
   vm-pattern
    vm-hash-table-object
    vm-hash-table-internal
    vm-hash-table-weakness
    rt-hash-table-weakness
    rt-make-hash-table
   vm-make-hash-table
   vm-gethash
   vm-sethash
   vm-remhash
   vm-clrhash
   vm-hash-table-count
   vm-hash-table-p
   vm-hash-table-keys
   vm-hash-table-values
   vm-hash-table-test
   vm-hash-table-size
    vm-hash-table-rehash-size
    vm-hash-table-rehash-threshold
     vm-hash-test
     vm-hash-weakness
    vm-found-dst
    vm-hash-key
    vm-hash-value
    vm-hash-table-reg
    vm-hash-default
    vm-hash-fn
     string-to-octets
     octets-to-string
     unicode-general-category
     unicode-alpha-char-p
     unicode-digit-char-p
     unicode-upper-case-p
     unicode-lower-case-p
     unicode-alphanumericp
     unicode-char-code
     unicode-code-char
     unicode-char-upcase
     unicode-char-downcase
     unicode-normalize-string
     unicode-normalize-nfc
     unicode-normalize-nfd
     unicode-normalize-nfkc
     unicode-normalize-nfkd
     string-to-utf8-bytes
     utf8-bytes-to-string
     unicode-syntax-class))
