(in-package :cl-cc/vm)
(defvar *json-null* :null)
(defun json-parse (s) (with-input-from-string (in s) (json-parse-stream in)))
(defun json-parse-stream (stream)
  (labels ((ws () (loop for ch = (peek-char nil stream nil :eof)
                        while (and (not (eq ch :eof)) (member ch '(#\Space #\Tab #\Newline #\Return)))
                        do (read-char stream)))
           (val ()
             (ws)
             (case (peek-char nil stream nil :eof)
               (#\{ (obj)) (#\[ (arr)) (#\" (str)) (#\t (lit t "true")) (#\f (lit nil "false"))
               (#\n (lit :null "null")) (:eof (error "EOF")) (t (num)))))
           (obj ()
             (read-char stream) (ws)
             (let ((h (make-hash-table :test #'equal)))
               (unless (char= (peek-char nil stream) #\})
                 (loop (ws) (let ((k (str))) (ws) (read-char stream) (ws)
                             (setf (gethash k h) (val)) (ws)
                             (let ((n (peek-char nil stream)))
                               (when (char= n #\}) (return))
                               (when (char= n #\,) (read-char stream))))))
               (read-char stream) h))
           (arr ()
             (read-char stream) (ws)
             (let ((v nil))
               (unless (char= (peek-char nil stream) #\])
                 (loop (ws) (push (val) v) (ws)
                       (let ((n (peek-char nil stream)))
                         (when (char= n #\]) (return))
                         (when (char= n #\,) (read-char stream)))))
               (read-char stream) (coerce (nreverse v) 'vector)))
           (str ()
             (read-char stream)
             (with-output-to-string (o)
               (loop for ch = (read-char stream)
                     when (char= ch #\") do (return)
                     when (char= ch #\\)
                     do (let ((e (read-char stream)))
                          (write-char (case e (#\" #\") (#\\ #\\) (#\/ #\/) (#\b #\Backspace) (#\f #\Page) (#\n #\Newline) (#\r #\Return) (#\t #\Tab) (t e)) o))
                     else do (write-char ch o))))
           (num ()
             (let ((c nil))
               (loop for ch = (peek-char nil stream nil :eof)
                     while (and ch (or (digit-char-p ch) (member ch '(#\- #\+ #\. #\e #\E))))
                     do (push (read-char stream) c))
               (read-from-string (coerce (nreverse c) 'string))))
           (lit (val s) (dotimes (i (- (length s) 1)) (read-char stream)) (read-char stream) val))
    (val)))
(defun json-stringify (o) (with-output-to-string (s) (json-stringify-stream o s)))
(defun json-stringify-stream (o stream)
  (flet ((wstr (s) (write-char #\" stream) (loop for c across s do (case c (#\" (write-string "\\\"" stream)) (#\\ (write-string "\\\\" stream)) (#\Newline (write-string "\\n" stream)) (#\Return (write-string "\\r" stream)) (#\Tab (write-string "\\t" stream)) (t (write-char c stream)))) (write-char #\" stream)))
    (cond ((null o) (write-string "null" stream)) ((eq o t) (write-string "true" stream)) ((eq o *json-null*) (write-string "null" stream)) ((stringp o) (wstr o)) ((hash-table-p o) (write-char #\{ stream) (let ((f t)) (maphash (lambda (k v) (unless f (write-char #\, stream)) (setf f nil) (wstr (string k)) (write-char #\: stream) (json-stringify-stream v stream)) o)) (write-char #\} stream)) ((numberp o) (princ o stream)) ((vectorp o) (write-char #\[ stream) (loop for i from 0 below (length o) do (unless (zerop i) (write-char #\, stream)) (json-stringify-stream (aref o i) stream)) (write-char #\] stream)) (t (wstr (format nil "~S" o))))))
