(in-package :cl-cc/vm)

(eval-when (:compile-toplevel :load-toplevel :execute)
  (defpackage :json
    (:use :cl)
    (:export
     #:*json-null*
     #:parse
     #:parse-stream
     #:stringify
     #:stringify-stream)))

(defvar *json-null* :null)
(defun json-parse (s) (with-input-from-string (in s) (json-parse-stream in)))
(defun json-parse-stream (stream)
  (labels ((ws ()
             (loop for ch = (peek-char nil stream nil :eof)
                   while (and (not (eq ch :eof))
                              (member ch '(#\Space #\Tab #\Newline #\Return)))
                   do (read-char stream)))
           (val ()
             (ws)
             (case (peek-char nil stream nil :eof)
               (#\{ (obj))
               (#\[ (arr))
               (#\" (str))
               (#\t (lit t "true"))
               (#\f (lit nil "false"))
               (#\n (lit *json-null* "null"))
               (:eof (error "EOF"))
               (t (num))))
           (obj ()
             (read-char stream)
             (ws)
             (let ((table (make-hash-table :test #'equal)))
               (unless (char= (peek-char nil stream) #\})
                 (loop
                   (ws)
                   (let ((key (str)))
                     (ws)
                     (read-char stream)
                     (ws)
                     (setf (gethash key table) (val))
                     (ws)
                     (let ((next (peek-char nil stream)))
                       (when (char= next #\})
                         (return))
                       (when (char= next #\,)
                         (read-char stream))))))
               (read-char stream)
               table))
           (arr ()
             (read-char stream)
             (ws)
             (let ((values nil))
               (unless (char= (peek-char nil stream) #\])
                 (loop
                   (ws)
                   (push (val) values)
                   (ws)
                   (let ((next (peek-char nil stream)))
                     (when (char= next #\])
                       (return))
                     (when (char= next #\,)
                       (read-char stream)))))
               (read-char stream)
               (coerce (nreverse values) 'vector)))
           (str ()
             (read-char stream)
             (with-output-to-string (out)
               (loop for ch = (read-char stream)
                     when (char= ch #\")
                       do (return)
                     when (char= ch #\\)
                       do (let ((escaped (read-char stream)))
                            (write-char
                             (case escaped
                               (#\" #\")
                               (#\\ #\\)
                               (#\/ #\/)
                               (#\b #\Backspace)
                               (#\f #\Page)
                               (#\n #\Newline)
                               (#\r #\Return)
                               (#\t #\Tab)
                               (t escaped))
                             out))
                     else
                       do (write-char ch out))))
           (num ()
             (let ((chars nil))
               (loop for ch = (peek-char nil stream nil :eof)
                     while (and (not (eq ch :eof))
                                (or (digit-char-p ch)
                                    (member ch '(#\- #\+ #\. #\e #\E))))
                     do (push (read-char stream) chars))
               (read-from-string (coerce (nreverse chars) 'string))))
           (lit (literal-value spelling)
             (loop repeat (length spelling)
                   do
               (read-char stream))
             literal-value))
    (val)))
(defun json-stringify (o) (with-output-to-string (s) (json-stringify-stream o s)))
(defun json-stringify-stream (o stream)
  (flet ((write-json-string (s)
           (write-char #\" stream)
           (loop for c across s
                 do (case c
                      (#\" (write-string "\\\"" stream))
                      (#\\ (write-string "\\\\" stream))
                      (#\Newline (write-string "\\n" stream))
                      (#\Return (write-string "\\r" stream))
                      (#\Tab (write-string "\\t" stream))
                      (t (write-char c stream))))
           (write-char #\" stream)))
    (cond
      ((null o)
       (write-string "null" stream))
      ((eq o t)
       (write-string "true" stream))
      ((eq o *json-null*)
       (write-string "null" stream))
      ((stringp o)
       (write-json-string o))
      ((hash-table-p o)
       (write-char #\{ stream)
       (let ((first-p t))
         (maphash
          (lambda (k v)
            (unless first-p
              (write-char #\, stream))
            (setf first-p nil)
            (write-json-string (string k))
            (write-char #\: stream)
            (json-stringify-stream v stream))
          o))
       (write-char #\} stream))
      ((numberp o)
       (princ o stream))
      ((vectorp o)
       (write-char #\[ stream)
       (loop for i from 0 below (length o)
             do (unless (zerop i)
                  (write-char #\, stream))
                (json-stringify-stream (aref o i) stream))
       (write-char #\] stream))
      ((listp o)
       (write-char #\[ stream)
       (loop for item in o
             for i from 0
             do (unless (zerop i)
                  (write-char #\, stream))
                (json-stringify-stream item stream))
       (write-char #\] stream))
      (t
       (write-json-string (format nil "~S" o))))))

(in-package :json)

(defvar *json-null* :null)

(defun parse (string)
  (let ((cl-cc/vm::*json-null* *json-null*))
    (cl-cc/vm::json-parse string)))

(defun parse-stream (stream)
  (let ((cl-cc/vm::*json-null* *json-null*))
    (cl-cc/vm::json-parse-stream stream)))

(defun stringify (object)
  (let ((cl-cc/vm::*json-null* *json-null*))
    (cl-cc/vm::json-stringify object)))

(defun stringify-stream (object stream)
  (let ((cl-cc/vm::*json-null* *json-null*))
    (cl-cc/vm::json-stringify-stream object stream)))
