(in-package :cl-cc/vm)
(defstruct phm-node (bitmap 0 :type integer) (children (make-array 0) :type simple-vector) (key nil) (value nil))
(defun phm-empty () (make-phm-node))
(defun %phm-hash (k) (abs (sxhash k)))
(defun %phm-idx (h sh) (ldb (byte 5 sh) h))
(defun %phm-bit (i) (ash 1 i))
(defun %phm-pop (bm i) (logcount (logand bm (1- (ash 1 i)))))
(defun %phm-clone (n) (make-phm-node :bitmap (phm-node-bitmap n) :children (copy-seq (phm-node-children n)) :key (phm-node-key n) :value (phm-node-value n)))
(defun %phm-assoc (node key val hash shift)
  (let* ((idx (%phm-idx hash shift)) (bit (%phm-bit idx)))
    (if (logtest (phm-node-bitmap node) bit)
        (let* ((pos (%phm-pop (phm-node-bitmap node) idx)) (child (aref (phm-node-children node) pos)) (nn (%phm-clone node)))
          (if (plusp shift) (setf (aref (phm-node-children nn) pos) (%phm-assoc child key val hash (- shift 5)))
              (if (equal (phm-node-key child) key)
                  (setf (aref (phm-node-children nn) pos) (make-phm-node :key key :value val))
                  (let ((bkt (make-phm-node :children (vector child (make-phm-node :key key :value val))))) (setf (aref (phm-node-children nn) pos) bkt))))
          nn)
        (let ((nn (%phm-clone node)) (ch (%phm-assoc (phm-empty) key val hash (if (plusp shift) (- shift 5) 0))))
          (setf (phm-node-bitmap nn) (logior (phm-node-bitmap node) bit))
          (let ((pos (%phm-pop (phm-node-bitmap node) idx)) (old (phm-node-children node)))
            (setf (phm-node-children nn) (let ((new (make-array (1+ (length old))))) (dotimes (i pos) (setf (aref new i) (aref old i))) (setf (aref new pos) (if (plusp shift) ch (make-phm-node :key key :value val))) (loop for i from pos below (length old) do (setf (aref new (1+ i)) (aref old i))) new))
            nn)))))
(defun persistent-map (&rest kvs) (let ((m (phm-empty))) (loop for (k v) on kvs by #'cddr do (setf m (%phm-assoc m k v (%phm-hash k) 0))) m))
(defun assoc (m k v) (%phm-assoc m k v (%phm-hash k) 0))
(defun dissoc (m k) (%phm-assoc m k :__phm-removed (%phm-hash k) 0))
(defun pget (m k &optional d)
  (let ((h (%phm-hash k)))
    (labels ((lk (n sh)
               (when n (let* ((idx (%phm-idx h sh)) (bit (%phm-bit idx)))
                         (if (logtest (phm-node-bitmap n) bit)
                             (let* ((pos (%phm-pop (phm-node-bitmap n) idx)) (ch (aref (phm-node-children n) pos)))
                               (if (plusp sh) (lk ch (- sh 5))
                                   (if (and (phm-node-key ch) (equal (phm-node-key ch) k))
                                       (let ((v (phm-node-value ch))) (if (eq v :__phm-removed) d v))
                                       d)))
                             d)))))
      (lk m 0))))
(defstruct pvec-node (children (make-array 32 :initial-element nil) :type simple-vector) (leaf nil :type list))
(defun pvec (&rest elts)
  (labels ((build (elts)
             (if (<= (length elts) 32) (make-pvec-node :leaf elts)
                 (let* ((step (ceiling (length elts) 32)) (n (make-pvec-node)))
                   (dotimes (i 32) (let ((s (* i step)) (e (min (length elts) (* (1+ i) step)))) (when (< s e) (setf (aref (pvec-node-children n) i) (build (subseq elts s e)))))) n))))
    (values (build elts) (length elts))))
(defun pvec-get (v i) (labels ((lk (n i) (if (pvec-node-leaf n) (nth i (pvec-node-leaf n)) (lk (aref (pvec-node-children n) (floor i 32)) (mod i 32))))) (lk (car v) i)))
(defun pvec-count (v) (cdr v))
(defun pvec->list (v) (loop for i below (pvec-count v) collect (pvec-get v i)))
(defstruct lazy-seq (thunk nil :type function) (realized nil) (cached-first nil) (cached-rest nil))
(defun lazy-seq (thunk) (make-lazy-seq :thunk thunk))
(defun force (ls)
  (when ls (unless (lazy-seq-realized ls) (let ((r (funcall (lazy-seq-thunk ls)))) (if (consp r) (setf (lazy-seq-cached-first ls) (car r) (lazy-seq-cached-rest ls) (cdr r)) (setf (lazy-seq-cached-first ls) nil (lazy-seq-cached-rest ls) nil)) (setf (lazy-seq-realized ls) t))) (if (lazy-seq-cached-first ls) (cons (lazy-seq-cached-first ls) (lazy-seq-cached-rest ls)) nil)))
(defun take (n ls) (loop repeat n for p = (force ls) while p collect (car p) do (setf ls (cdr p))))
(defun lazy-map (f ls) (lazy-seq (lambda () (let ((p (force ls))) (when p (cons (funcall f (car p)) (lazy-map f (cdr p))))))))
(defun lazy-filter (pred ls) (lazy-seq (lambda () (loop for p = (force ls) while p when (funcall pred (car p)) return (cons (car p) (lazy-filter pred (cdr p))) do (setf ls (cdr ls))))))
(defun iterate (f init) (lazy-seq (lambda () (cons init (iterate f (funcall f init))))))
(defun lazy-range (&key (start 0) end (step 1)) (if (and end (>= start end)) nil (lazy-seq (lambda () (cons start (lazy-range :start (+ start step) :end end :step step))))))
