(in-package :cl-cc/vm)
(defconstant +mt19937-n+ 624)
(defconstant +mt19937-m+ 397)
(defconstant +mt19937-matrix-a+ #x9908b0df)
(defconstant +mt19937-upper-mask+ #x80000000)
(defconstant +mt19937-lower-mask+ #x7fffffff)

(defstruct (vm-random-state (:constructor %make-vm-random-state))
  (mt (make-array +mt19937-n+ :element-type '(unsigned-byte 32) :initial-element 0))
  (index +mt19937-n+ :type fixnum))

(defun %vm-u32 (value) (logand value #xffffffff))
(defun %vm-mt-seed (seed)
  (let ((state (%make-vm-random-state)))
    (setf (aref (vm-random-state-mt state) 0) (%vm-u32 seed))
    (loop for i from 1 below +mt19937-n+
          for prev = (aref (vm-random-state-mt state) (1- i))
          do (setf (aref (vm-random-state-mt state) i)
                   (%vm-u32 (+ (* 1812433253 (logxor prev (ash prev -30))) i))))
    state))
(defun %vm-mt-copy (source)
  (let ((copy (%make-vm-random-state)))
    (replace (vm-random-state-mt copy) (vm-random-state-mt source))
    (setf (vm-random-state-index copy) (vm-random-state-index source))
    copy))
(defun %vm-mt-twist (state)
  (let ((mt (vm-random-state-mt state)))
    (loop for i from 0 below +mt19937-n+
          for x = (logior (logand (aref mt i) +mt19937-upper-mask+)
                          (logand (aref mt (mod (1+ i) +mt19937-n+)) +mt19937-lower-mask+))
          for xa = (ash x -1)
          do (when (oddp x) (setf xa (logxor xa +mt19937-matrix-a+)))
             (setf (aref mt i) (%vm-u32 (logxor (aref mt (mod (+ i +mt19937-m+) +mt19937-n+)) xa)))))
  (setf (vm-random-state-index state) 0))
(defun vm-random-state-next-u32 (state)
  (when (>= (vm-random-state-index state) +mt19937-n+) (%vm-mt-twist state))
  (let* ((mt (vm-random-state-mt state))
         (y (aref mt (vm-random-state-index state))))
    (incf (vm-random-state-index state))
    (setf y (logxor y (ash y -11)))
    (setf y (logxor y (logand (ash y 7) #x9d2c5680)))
    (setf y (logxor y (logand (ash y 15) #xefc60000)))
    (%vm-u32 (logxor y (ash y -18)))))
(defun vm-make-random-state (&optional state)
  (cond ((vm-random-state-p state) (%vm-mt-copy state))
        ((integerp state) (%vm-mt-seed state))
        ((eq state t) (%vm-mt-seed (logxor (get-universal-time) (get-internal-real-time))))
        (t (%vm-mt-seed 5489))))
(defparameter *vm-random-state* (vm-make-random-state 5489))
(defun vm-random (limit &optional (state *vm-random-state*))
  (cond ((and (integerp limit) (plusp limit)) (mod (vm-random-state-next-u32 state) limit))
        ((and (floatp limit) (plusp limit)) (* limit (/ (vm-random-state-next-u32 state) 4294967296.0)))
        (t (error "Invalid random limit: ~S" limit))))
