(in-package :cl-cc/vm)
(defstruct regex-nfa start accept (states nil) (capture-groups 0))
(defstruct regex-state (id 0) (transitions nil) (epsilon nil) (capture nil))
(defun %re-mk-state (nfa) (let ((s (make-regex-state :id (length (regex-nfa-states nfa))))) (push s (regex-nfa-states nfa)) s))
(defun %re-add-trans (f t c) (push (cons c t) (regex-state-transitions f)))
(defun %re-add-eps (f t) (pushnew t (regex-state-epsilon f)))
(defun %re-char-match (pat ch)
  (cond ((characterp pat) (char= pat ch)) ((eq pat :any) t)
        ((eq pat :d) (digit-char-p ch)) ((eq pat :w) (or (alpha-char-p ch) (digit-char-p ch) (char= ch #\_)))
        ((eq pat :s) (member ch '(#\Space #\Tab #\Newline #\Return))) (t nil)))
(defun %re-eps-closure (states)
  (let ((r (copy-list states)) (stack (copy-list states)))
    (loop while stack for s = (pop stack) do (dolist (n (regex-state-epsilon s)) (unless (member n r :test #'eq) (push n r) (push n stack)))) r))
(defun %re-step (states ch)
  (let ((n nil)) (dolist (s states) (dolist (t (regex-state-transitions s)) (when (%re-char-match (car t) ch) (pushnew (cdr t) n :test #'eq)))) (%re-eps-closure n)))
(defun %re-parse-cc (stream)
  (let ((inv nil) (cs nil))
    (when (char= (peek-char nil stream) #\^) (read-char stream) (setf inv t))
    (loop for ch = (read-char stream) until (or (null ch) (char= ch #\]))
          do (if (char= ch #\-)
                 (let ((s (pop cs)) (e (read-char stream)))
                   (loop for c from (char-code s) to (char-code e) do (push (code-char c) cs)))
                 (push ch cs)))
    (list :cc inv (nreverse cs))))
(defun %re-parse (pattern &key (start 0) (end (length pattern)))
  (let ((pos start) (nfa (make-regex-nfa :start (%re-mk-state nil))))
    (setf (regex-nfa-accept nfa) (regex-nfa-start nfa))
    (labels ((nc () (and (< pos end) (prog1 (char pattern pos) (incf pos))))
             (pk () (and (< pos end) (char pattern pos)))
             (atom ()
               (let ((ch (nc)))
                 (when ch (case ch (#\. :any) (#\[ (%re-parse-cc nil))
                              (#\( (let ((ns (%re-mk-state nfa)) (ne (%re-mk-state nfa)))
                                     (%re-add-eps ns ne) (%re-add-eps (regex-nfa-accept nfa) ns)
                                     (setf (regex-nfa-accept nfa) ne) (incf (regex-nfa-capture-groups nfa))
                                     (loop while (and (pk) (not (char= (pk) #\)))) do (let ((a (rep))) (when a (let ((s (%re-mk-state nfa))) (%re-add-trans (regex-nfa-accept nfa) s a) (setf (regex-nfa-accept nfa) s)))))
                                     (nc) nil))
                              (#\\) (case (nc) (#\d :d) (#\w :w) (#\s :s) (t ch)))
                              (t ch)))))
             (rep ()
               (let ((a (atom)) (n (pk)))
                 (case n (#\* (nc) (let ((s (%re-mk-state nfa)) (e (%re-mk-state nfa))) (%re-add-trans (regex-nfa-accept nfa) s a) (%re-add-eps s e) (%re-add-eps s (regex-nfa-accept nfa)) (setf (regex-nfa-accept nfa) e) nil))
                       (#\+ (nc) (let ((s (%re-mk-state nfa)) (e (%re-mk-state nfa))) (%re-add-trans (regex-nfa-accept nfa) s a) (%re-add-eps s e) (%re-add-eps e s) (setf (regex-nfa-accept nfa) e) nil))
                       (#\? (nc) (let ((sk (%re-mk-state nfa))) (%re-add-eps (regex-nfa-accept nfa) sk) (%re-add-trans (regex-nfa-accept nfa) sk a) (setf (regex-nfa-accept nfa) sk) nil))
                       (t a)))))
      (loop while (pk) do (let ((r (rep))) (when r (let ((s (%re-mk-state nfa))) (%re-add-trans (regex-nfa-accept nfa) s r) (setf (regex-nfa-accept nfa) s)))))
      nfa)))
(defun regex-scan (pattern string &key (start 0) end)
  (let* ((e (or end (length string))) (nfa (%re-parse pattern)) (init (%re-eps-closure (list (regex-nfa-start nfa)))))
    (loop for i from start below e do (let ((s init))
                                        (loop for j from i below e for ch = (char string j) do (setf s (%re-step s ch))
                                              when (member (regex-nfa-accept nfa) s :test #'eq)
                                              return (return-from regex-scan (values i (1+ j)))
                                              when (null s) return nil)))
    nil))
(defun regex-all-matches (p s &key (start 0) end)
  (let ((pos start) (r nil) (e (or end (length s))))
    (loop (multiple-value-bind (ms me) (regex-scan p s :start pos :end e) (unless ms (return)) (push (cons ms me) r) (setf pos me))) (nreverse r)))
(defun regex-replace (p s r)
  (multiple-value-bind (ms me) (regex-scan p s) (if ms (concatenate 'string (subseq s 0 ms) r (subseq s me)) s)))
(defun regex-replace-all (p s r)
  (with-output-to-string (out) (let ((pos 0)) (loop (multiple-value-bind (ms me) (regex-scan p s :start pos) (unless ms (write-string s out :start pos) (return)) (write-string s out :start pos :end ms) (write-string r out) (setf pos me))))))
(defun regex-split (p s)
  (let ((parts nil) (pos 0))
    (loop (multiple-value-bind (ms me) (regex-scan p s :start pos) (unless ms (push (subseq s pos) parts) (return)) (push (subseq s pos ms) parts) (setf pos me))) (nreverse parts)))
