(in-package :cl-cc/vm)
(defun get-universal-time () (cl:get-universal-time))
(defun get-internal-real-time () (cl:get-internal-real-time))
(defparameter internal-time-units-per-second cl:internal-time-units-per-second)
(defun sleep (seconds) (cl:sleep seconds))
(defun encode-universal-time (year month day hour minute second &optional timezone)
  (cl:encode-universal-time year month day hour minute second timezone))
(defun decode-universal-time (universal-time &optional timezone)
  (cl:decode-universal-time universal-time timezone))
