;;;; packages/vm/src/unicode.lisp — Unicode Character Database (FR-590, FR-591)
(in-package :cl-cc/vm)

(defvar +ucd-category-lu+ "Lu")  (defvar +ucd-category-ll+ "Ll")
(defvar +ucd-category-lt+ "Lt")  (defvar +ucd-category-lm+ "Lm")
(defvar +ucd-category-lo+ "Lo")  (defvar +ucd-category-mn+ "Mn")
(defvar +ucd-category-mc+ "Mc")  (defvar +ucd-category-me+ "Me")
(defvar +ucd-category-nd+ "Nd")  (defvar +ucd-category-nl+ "Nl")
(defvar +ucd-category-no+ "No")  (defvar +ucd-category-pc+ "Pc")
(defvar +ucd-category-pd+ "Pd")  (defvar +ucd-category-ps+ "Ps")
(defvar +ucd-category-pe+ "Pe")  (defvar +ucd-category-pi+ "Pi")
(defvar +ucd-category-pf+ "Pf")  (defvar +ucd-category-po+ "Po")
(defvar +ucd-category-sm+ "Sm")  (defvar +ucd-category-sc+ "Sc")
(defvar +ucd-category-sk+ "Sk")  (defvar +ucd-category-so+ "So")
(defvar +ucd-category-zs+ "Zs")  (defvar +ucd-category-zl+ "Zl")
(defvar +ucd-category-zp+ "Zp")  (defvar +ucd-category-cc+ "Cc")
(defvar +ucd-category-cf+ "Cf")  (defvar +ucd-category-cs+ "Cs")
(defvar +ucd-category-co+ "Co")  (defvar +ucd-category-cn+ "Cn")

(defvar *ucd-category-index* nil)

(defun ucd-init-category-index ()
  (let ((table (make-hash-table :test #'equal)) (i 0))
    (dolist (cat (list +ucd-category-lu+ +ucd-category-ll+ +ucd-category-lt+ +ucd-category-lm+ +ucd-category-lo+ +ucd-category-mn+ +ucd-category-mc+ +ucd-category-me+ +ucd-category-nd+ +ucd-category-nl+ +ucd-category-no+ +ucd-category-pc+ +ucd-category-pd+ +ucd-category-ps+ +ucd-category-pe+ +ucd-category-pi+ +ucd-category-pf+ +ucd-category-po+ +ucd-category-sm+ +ucd-category-sc+ +ucd-category-sk+ +ucd-category-so+ +ucd-category-zs+ +ucd-category-zl+ +ucd-category-zp+ +ucd-category-cc+ +ucd-category-cf+ +ucd-category-cs+ +ucd-category-co+ +ucd-category-cn+))
      (setf (gethash cat table) i) (incf i))
    (setf *ucd-category-index* table)))

(defun unicode-char-upcase (ch)
  (let ((cp (char-code ch)))
    (if (<= 97 cp 122) (code-char (- cp 32)) ch)))
(defun unicode-char-downcase (ch)
  (let ((cp (char-code ch)))
    (if (<= 65 cp 90) (code-char (+ cp 32)) ch)))
(defun unicode-alpha-char-p (ch)
  (let ((cp (char-code ch)))
    (or (<= 65 cp 90) (<= 97 cp 122))))
(defun unicode-upper-case-p (ch) (<= 65 (char-code ch) 90))
(defun unicode-lower-case-p (ch) (<= 97 (char-code ch) 122))
(defun unicode-digit-char-p (ch &optional (radix 10))
  (let ((cp (char-code ch)))
    (and (<= 48 cp 57) (< (- cp 48) radix) (- cp 48))))
(defun unicode-alphanumericp (ch)
  (or (unicode-alpha-char-p ch) (unicode-digit-char-p ch)))

(defun unicode-init ()
  (ucd-init-category-index) t)

(eval-when (:load-toplevel :execute) (unicode-init))
