(defpackage :cl-cc/test
  (:use :cl)
  (:shadowing-import-from :cl-cc/type
   :type-node
   :type-primitive   :type-scheme
   :type-primitive-name
   :type-var-id
   :type-var-name
   :type-arrow-params
   :type-arrow-return
   :type-scheme-quantified-vars
   :type-scheme-type
   :type-int
   :type-float
   :type-string
   :type-bool
   :type-symbol
   :type-cons
   :type-null
   :type-any
   :type-char
   :type-unit   :make-type-primitive
   :fresh-type-var
   :make-type-scheme
   :type-constructor
   :type-constructor-p
   :type-constructor-name
   :type-constructor-args
   :make-type-constructor
   :type-to-scheme
   :type-var-p
   :type-var-equal-p
   :type-equal-p
   :type-to-string
   :subst-lookup
   :subst-extend
   :zonk
   :subst-compose
   :type-unify
   :type-unify-lists
   :type-occurs-p
   :type-free-vars
   :generalize
   :instantiate
   :normalize-type-variables
   :type-env-empty
   :type-env-extend
   :type-env-lookup
   :reset-type-vars!
   :infer
   :infer-with-env
   :type-inference-error
   :unbound-variable-error
   :type-mismatch-error
   :synthesize
   :check
   :check-body
   :register-typeclass
   :lookup-typeclass
   :make-type-qualified
   :type-qualified-p
   :type-qualified-constraints
   :register-typeclass-instance
   :has-typeclass-instance-p
   :make-type-effect-row
   :type-effect-row-p
   :type-effect-row-effects
   :type-effect-row-row-var
   :+pure-effect-row+
   :+io-effect-row+
   :make-type-forall
   :type-forall-p
   :type-forall-var
   :type-forall-body
   :make-type-lambda
   :type-lambda-p
   :type-lambda-var
   :type-lambda-knd
   :type-lambda-body
   :kind-node-p
   :fresh-kind-var
   :kind-var-p
   :kind-var-equal-p
   :kind-type-p
   :make-kind-type
   :kind-arrow-p
   :kind-arrow-from
   :kind-arrow-to
   :kind-fun
   :kind-effect-p
   :kind-row-p
   :kind-row-elem
   :kind-equal-p
   :kind-to-string
   :+kind-type+
   :+kind-effect+
   :+kind-constraint+
   :+kind-multiplicity+
   :+kind-row-type+
   :+kind-row-effect+
   :+mult-zero+
   :+mult-one+
   :+mult-omega+
   :multiplicity-p
   :mult-add
   :mult-mul
   :mult-leq
   :mult-to-string
   :type-arrow
   :make-type-arrow
   :make-type-arrow-raw
   :type-arrow-p
   :type-arrow-params
   :type-arrow-return
   :type-arrow-effects
   :type-arrow-mult
   :make-type-app
   :type-app-p
   :type-app-fun
   :type-app-arg
   :make-type-error
   :type-error-p
   :make-type-exists
   :type-exists-p
   :type-exists-var
   :type-exists-body
   :make-type-linear
   :type-linear-p
   :type-linear-base
   :type-linear-grade
   :make-type-mu
   :type-mu-p
   :type-mu-var
   :type-mu-body
   :make-type-product
   :type-product-p
   :type-product-elems
   :make-type-record
   :type-record-p
   :type-record-fields
   :type-record-row-var
   :make-type-union
   :type-union-p
   :type-union-types
   :make-type-intersection
   :type-intersection-p
   :type-intersection-types
   :make-type-variant
   :type-variant-p
   :type-variant-cases
   :type-variant-row-var
   :type-refinement-p
   :type-refinement-base
   :type-refinement-predicate
    :fresh-rigid-var
    :type-rigid-p
    :type-rigid-name
   :type-rigid-equal-p   :upgraded-array-element-type
   :upgraded-complex-part-type
   :type-primitive-p
   :type-var-p
   :type-var-name
   :type-var-equal-p
   :make-substitution
   :substitution-p
   :substitution-generation
   :subst-extend
   :subst-extend!
   :subst-compose
   :zonk
   :make-typeclass-def
   :typeclass-def-p
   :typeclass-def-name
   :typeclass-def-type-params
   :typeclass-def-methods
   :typeclass-instance-p
   :typeclass-instance-class-name
   :typeclass-instance-methods
   :lookup-typeclass-instance
   :row-extend
   :row-restrict
   :row-select
   :row-labels
   :row-closed-p
   :row-open-p
   :make-type-effect-op
   :constraint :constraint-p :constraint-kind :constraint-args
   :make-equal-constraint :make-subtype-constraint
   :make-typeclass-constraint :make-implication-constraint
   :make-effect-subset-constraint :make-mult-leq-constraint
   :make-row-lacks-constraint :make-kind-equal-constraint
   :solve-constraints :collect-constraints))

;;; Compiler/parser/backend imports and exports are split into adjacent helper
;;; files. The type import block stays inside DEFPACKAGE because it relies on
;;; symbol-name resolution rather than read-time package-qualified symbols.
