;;;; packages/emit/tests/llvm-ir-tests.lisp

(in-package :cl-cc/test)

(in-suite cl-cc-unit-suite)

(deftest llvm-ir-lowers-mir-arithmetic-memory-control-and-call
  "FR-690: MIR functions lower to textual LLVM IR with SSA, blocks, memory, branches, and external declarations."
  (let* ((fn (mir-make-function :llvm-add-or-sub))
         (entry (mirf-entry fn))
         (then-block (mir-new-block fn :label :then))
         (else-block (mir-new-block fn :label :else))
         (lhs (mir-new-value fn :name :lhs :type :integer))
         (rhs (mir-new-value fn :name :rhs :type :integer))
         (slot (mir-new-value fn :name :slot :type :pointer))
         (loaded (mir-new-value fn :name :loaded :type :integer))
         (condv (mir-new-value fn :name :cond :type :boolean))
         (sum (mir-new-value fn :name :sum :type :integer))
         (called (mir-new-value fn :name :called :type :integer))
         (diff (mir-new-value fn :name :diff :type :integer)))
    (setf (mirf-params fn) (list lhs rhs))
    (mir-add-succ entry then-block)
    (mir-add-succ entry else-block)
    (mir-emit entry :alloca :dst slot :srcs (list (make-mir-const :value 8 :type :integer)) :type :pointer)
    (mir-emit entry :store :srcs (list slot (make-mir-const :value 0 :type :integer) lhs))
    (mir-emit entry :load :dst loaded :srcs (list slot (make-mir-const :value 0 :type :integer)) :type :integer)
    (mir-emit entry :lt :dst condv :srcs (list loaded rhs) :type :boolean)
    (mir-emit entry :branch :srcs (list condv then-block else-block))
    (mir-emit then-block :add :dst sum :srcs (list loaded rhs) :type :integer)
    (mir-emit then-block :call :dst called
              :srcs (list (make-mir-const :value :external-inc :type :function) sum)
              :type :integer)
    (mir-emit then-block :ret :srcs (list called))
    (mir-emit else-block :sub :dst diff :srcs (list rhs loaded) :type :integer)
    (mir-emit else-block :ret :srcs (list diff))
    (let ((ir (cl-cc/emit:emit-llvm-ir fn :name "fr690-real")))
      (assert-true (search "target triple = \"x86_64-unknown-linux-gnu\"" ir))
      (assert-true (search "define i64 @llvm-add-or-sub(i64 %reg0, i64 %reg1)" ir))
      (assert-true (search "%reg2 = alloca i8, i64 8" ir))
      (assert-true (search "store i64 %reg0, ptr %reg2" ir))
      (assert-true (search "%reg3 = load i64, ptr %reg2" ir))
      (assert-true (search "%reg4 = icmp slt i64 %reg3, %reg1" ir))
      (assert-true (search "br i1 %reg4, label %then, label %else" ir))
      (assert-true (search "%reg5 = add i64 %reg3, %reg1" ir))
      (assert-true (search "%reg6 = call i64 @external-inc(i64 %reg5)" ir))
      (assert-true (search "declare i64 @external-inc(i64)" ir))
      (assert-false (search "TODO" ir))
      (assert-false (search "bridge-only" ir)))))
