(cl:in-package :cl-cc/test)

;;; Public test framework API.
;;; Originally lines 623-678 of package.lisp.

#-cl-cc-self-hosting
(export '(run-tests
          enable-coverage
          disable-coverage
          coverage-enabled-p
          with-coverage
          generate-coverage-report
          write-lcov-report
          coverage-report-index-path
          coverage-report-exists-p
          coverage-report-empty-p
           cl-cc-suite
           cl-cc-unit-suite
           cl-cc-integration-suite
           cl-cc-integration-serial-suite
           cl-cc-e2e-suite
           cl-cc-conformance-suite
          run-suite
          deftest
          defsuite
          in-suite
          assert-=
          assert-eq
          assert-eql
          assert-equal
          assert-string=
          assert-null
          assert-true
          assert-false
          assert-type
          assert-signals
          assert-values
          assert-faster-than
          assert-no-consing
          assert-no-allocation
          assert-type-equal
          assert-unifies
          assert-not-unifies
          assert-bool
          assert-list-contains
          assert-bitfield
          assert-snapshot
          assert-compiles-to
          assert-pbt
          deftest-pbt
          assert-evaluates-to
          assert-macro-expands-to
          assert-infers-type
          deftest-each
          ;; High-level test macros (requirement #7)
          deftest-compile
          deftest-codegen
          deftest-vm
           defbenchmark
           run-benchmark
           benchmark-statistics
           benchmark-result-json
           write-benchmark-result-json
           run-all-benchmarks
           *benchmark-registry*
          testing
          defbefore
          defafter
          set-test-timeouts!
          set-test-timeouts-by-prefix!
          set-suite-test-timeout!
           skip
           pending
           expected-fail
           defexpected
           deftest-fuzz
           shrink
           shrink-integer
           shrink-list
           shrink-string
           minimize-failing-input
           check-property-with-shrinking
           register-type-generator
           deftype-generator
           generator-for-type
           generate-for-type
           generate-from-type-annotation
           make-pbt-command
           pbt-command-p
           pbt-command-name
           pbt-command-precondition
           pbt-command-run
           generate-stateful-command-sequence
           run-stateful-command-sequence
           assert-no-crash
           assert-terminates
          defmetamorphic
          definvariant
          run-mutation-test
          ;; Persistent map (phase 1 of immutable test framework)
          persistent-map
          persistent-map-p
          persist-empty
          persist-assoc
          persist-lookup
          persist-contains-p
          persist-remove
          persist-count
          persist-each
          persist-keys
          persist-values
          persist-to-alist
          persist-from-alist))
