(defpackage :cl-cc/pbt-macho
  (:use :cl)
  (:import-from :cl-cc/pbt
                #:gen-one-of
                #:gen-fmap
                #:gen-bind
                #:gen-list-of
                #:gen-tuple
                #:gen-integer)
  (:export
   #:*max-mach-o-sections*
   ;; Mach-O Constants
   #:+mh-magic+
   #:+mh-magic-64+
   #:+mh-cigam+
   #:+mh-cigam-64+
   #:+cpu-type-x86+
   #:+cpu-type-x86-64+
   #:+cpu-type-arm+
   #:+cpu-type-arm64+
   #:+cpu-subtype-x86-all+
   #:+cpu-subtype-arm-all+
   #:+cpu-subtype-arm64-all+
   #:+mh-object+
   #:+mh-execute+
   #:+mh-fvm+
   #:+mh-core+
   #:+mh-preload+
   #:+mh-dylib+
   #:+mh-dylinker+
   #:+mh-bundle+
   #:+mh-noundefs+
   #:+mh-dyldlink+
   #:+mh-pie+
   #:+lc-segment+
   #:+lc-segment-64+
   #:+lc-symtab+
   #:+lc-dysymtab+
   #:+lc-load-dylib+
   #:+lc-id-dylib+
   #:+lc-load-weak-dylib+
   #:+lc-uuid+
   #:+lc-rpath+
   #:+lc-code-signature+
   #:+lc-reexport-dylib+
   #:+lc-version-min-macosx+
   #:+lc-build-version+
   #:+vm-prot-read+
   #:+vm-prot-write+
   #:+vm-prot-execute+
   ;; Mach-O Structure Generators
   #:gen-mach-magic
   #:gen-mach-cpu-type
   #:gen-mach-cpu-subtype
   #:gen-mach-file-type
   #:gen-mach-flags
   #:gen-mach-header
   #:gen-segment-permissions
   #:gen-segment-name
   #:gen-section-name
   #:gen-mach-section
   #:gen-mach-segment-command
   #:gen-mach-load-command-type
   ;; Mach-O Structures
   #:mach-header
   #:make-mach-header-raw
   #:mach-header-magic
   #:mach-header-cputype
   #:mach-header-cpusubtype
   #:mach-header-filetype
   #:mach-header-ncmds
   #:mach-header-sizeofcmds
   #:mach-header-flags
   #:mach-header-reserved
   #:mach-segment-command
   #:make-mach-segment-raw
   #:mach-segment-command-cmd
   #:mach-segment-command-cmdsize
   #:mach-segment-command-segname
   #:mach-segment-command-vmaddr
   #:mach-segment-command-vmsize
   #:mach-segment-command-fileoff
   #:mach-segment-command-filesize
   #:mach-segment-command-maxprot
   #:mach-segment-command-initprot
   #:mach-segment-command-nsects
   #:mach-segment-command-flags
   #:mach-segment-command-sections
   #:mach-section
   #:make-mach-section-raw
   #:mach-section-sectname
   #:mach-section-segname
   #:mach-section-addr
   #:mach-section-size
   #:mach-section-offset
   #:mach-section-align
   #:mach-section-reloff
   #:mach-section-nreloc
   #:mach-section-flags
   #:mach-section-reserved1
   #:mach-section-reserved2
   #:mach-section-reserved3))

(in-package :cl-cc/pbt-macho)
