;;;; packages/javascript/src/lexer-number.lisp — JS numeric literal lexer
;;;;
;;;; Extracted from lexer.lisp to isolate the number-lexing machinery.
;;;; All four digit-reader helpers are generated by define-js-digit-reader.

(in-package :cl-cc/javascript)

;;; -----------------------------------------------------------------------
;;;  Digit-reader generator macro
;;; -----------------------------------------------------------------------
;;;
;;; Each variant reads digits of its base (skipping _ separators) and
;;; returns (values digit-string new-pos).

(defmacro define-js-digit-reader (name char-pred doc &key (require-nonempty t))
  "Generate a digit-reader function. CHAR-PRED is a form evaluated with
C bound to the current character. When REQUIRE-NONEMPTY is true (default),
an error is raised if no digits are consumed."
  `(defun ,name (source pos)
     ,doc
     (let ((buf (make-array 16 :element-type 'character :fill-pointer 0 :adjustable t))
           ,@(when require-nonempty '((start pos))))
       (loop while (and (< pos (length source))
                        (let ((c (char source pos)))
                          (or ,char-pred (char= c #\_))))
             do (let ((c (char source pos)))
                  (unless (char= c #\_) (vector-push-extend c buf))
                  (incf pos)))
       ,@(when require-nonempty
           '((when (= pos start)
               (error "JS lex error: expected digits"))))
       (values (copy-seq buf) pos))))

(define-js-digit-reader %lex-js-hex-digits
  (js-hex-digit-p c)
  "Read hex digits (0-9 a-f A-F, optional _ separators) from POS.")

(define-js-digit-reader %lex-js-binary-digits
  (member c '(#\0 #\1) :test #'char=)
  "Read binary digits (0 1, optional _ separators) from POS.")

(define-js-digit-reader %lex-js-octal-digits
  (char<= #\0 c #\7)
  "Read octal digits (0-7, optional _ separators) from POS.")

(define-js-digit-reader %lex-js-decimal-digits
  (js-digit-p c)
  "Read decimal digits (0-9, optional _ separators) from POS."
  :require-nonempty nil)

;;; -----------------------------------------------------------------------
;;;  Radix-number helper (hex / octal / binary share the same shape)
;;; -----------------------------------------------------------------------

(defun %lex-js-radix-number (source pos digit-reader radix)
  "Parse a 0x/0o/0b prefixed integer literal starting at POS.
DIGIT-READER is one of the %lex-js-*-digits functions; RADIX is 16/8/2.
Returns (values token new-pos)."
  (multiple-value-bind (digits new-pos)
      (funcall digit-reader source (+ pos 2))   ; skip the two-char prefix
    (let ((bigint-p (and (< new-pos (length source))
                         (char= (char source new-pos) #\n))))
      (when bigint-p (incf new-pos))
      (values (make-js-token (if bigint-p :T-BIGINT :T-NUMBER)
                             (parse-integer digits :radix radix))
              new-pos))))

;;; -----------------------------------------------------------------------
;;;  Main number lexer
;;; -----------------------------------------------------------------------

(defun lex-js-number (source pos)
  "Lex a numeric literal starting at POS.
Handles decimal, hex (0x), octal (0o), binary (0b), BigInt (n suffix),
and numeric separators (_). Returns (values token new-pos)."
  (let ((ch (char source pos)))
    (cond
      ;; Hex: 0x or 0X
      ((and (char= ch #\0) (< (1+ pos) (length source))
            (member (char source (1+ pos)) '(#\x #\X) :test #'char=))
       (%lex-js-radix-number source pos #'%lex-js-hex-digits 16))

      ;; Octal: 0o or 0O
      ((and (char= ch #\0) (< (1+ pos) (length source))
            (member (char source (1+ pos)) '(#\o #\O) :test #'char=))
       (%lex-js-radix-number source pos #'%lex-js-octal-digits 8))

      ;; Binary: 0b or 0B
      ((and (char= ch #\0) (< (1+ pos) (length source))
            (member (char source (1+ pos)) '(#\b #\B) :test #'char=))
       (%lex-js-radix-number source pos #'%lex-js-binary-digits 2))

      ;; Decimal (integer or float)
      (t
       (multiple-value-bind (int-digits pos2)
           (%lex-js-decimal-digits source pos)
         (let ((is-float nil)
               (num-str int-digits))
           ;; Fractional part
           (when (and (< pos2 (length source))
                      (char= (char source pos2) #\.)
                      (or (and (< (1+ pos2) (length source))
                               (js-digit-p (char source (1+ pos2))))
                          ;; "1." is a valid float
                          (not (and (< (1+ pos2) (length source))
                                    (js-id-start-p (char source (1+ pos2)))))))
             (setf is-float t)
             (incf pos2)
             (multiple-value-bind (frac-digits pos3)
                 (%lex-js-decimal-digits source pos2)
               (setf num-str (concatenate 'string num-str "." frac-digits)
                     pos2 pos3)))
           ;; Exponent part
           (when (and (< pos2 (length source))
                      (member (char source pos2) '(#\e #\E) :test #'char=))
             (setf is-float t)
             (let ((exp-str "e"))
               (incf pos2)
               (when (and (< pos2 (length source))
                          (member (char source pos2) '(#\+ #\-) :test #'char=))
                 (setf exp-str (concatenate 'string exp-str (string (char source pos2))))
                 (incf pos2))
               (multiple-value-bind (exp-digits pos3)
                   (%lex-js-decimal-digits source pos2)
                 (setf num-str (concatenate 'string num-str exp-str exp-digits)
                       pos2 pos3))))
           ;; BigInt suffix (only on integer, not float)
           (when (and (not is-float)
                      (< pos2 (length source))
                      (char= (char source pos2) #\n))
             (incf pos2)
             (return-from lex-js-number
               (values (make-js-token :T-BIGINT (parse-integer num-str)) pos2)))
           ;; JS numbers are IEEE-754 doubles; bind *read-default-float-format*
           ;; to double-float so "1.5e-3" reads at full double precision.
           (let ((val (if is-float
                          (let ((*read-eval* nil)
                                (*read-default-float-format* 'double-float))
                            (float (read-from-string num-str) 1.0d0))
                          (parse-integer num-str))))
             (values (make-js-token :T-NUMBER val) pos2))))))))
