;;;; compiler-selfhost-fixtures-ext.lisp — Extended self-hosting fixtures (runtime/CLOS heavy)
(in-package :cl-cc/test)

(defparameter *self-host-stack-compiler-program*
  "(progn
     (defstruct ast-num value)
     (defstruct ast-binop op lhs rhs)
     (defun parse (expr)
       (cond
         ((numberp expr) (make-ast-num :value expr))
         ((consp expr)
          (make-ast-binop :op (car expr)
                          :lhs (parse (cadr expr))
                          :rhs (parse (caddr expr))))
         (t (error \"unknown\"))))
     (defun compile-node (node)
       (cond
         ((ast-num-p node)
          (list (list 'push (ast-num-value node))))
         ((ast-binop-p node)
          (append (compile-node (ast-binop-lhs node))
                  (compile-node (ast-binop-rhs node))
                  (list (list 'op (ast-binop-op node)))))
         (t nil)))
     (defun run-vm (instrs)
       (let ((stack nil))
         (dolist (inst instrs)
           (cond
             ((eq (car inst) 'push) (push (cadr inst) stack))
             ((eq (car inst) 'op)
              (let ((b (pop stack))
                    (a (pop stack)))
                (cond
                  ((eq (cadr inst) '+) (push (+ a b) stack))
                  ((eq (cadr inst) '*) (push (* a b) stack))
                  ((eq (cadr inst) '-) (push (- a b) stack)))))))
         (car stack)))
     (run-vm (compile-node (parse '(+ (* 3 4) (- 10 5)))))"
  "Readable self-hosting stack-machine compiler fixture.")

(defparameter *self-host-clos-compiler-program*
  "(progn
     (defclass ast-n6 () ())
     (defclass ast-i6 (ast-n6) ((v :initarg :v :reader ast-i6-v)))
     (defclass ast-v6 (ast-n6) ((n :initarg :n :reader ast-v6-n)))
     (defclass ast-b6 (ast-n6)
       ((op :initarg :op :reader ast-b6-op)
        (l :initarg :l :reader ast-b6-l)
        (r :initarg :r :reader ast-b6-r)))
     (defstruct cx6 (nr 0) (insts nil) (env nil))
     (defun mr6 (c)
       (let ((r (cx6-nr c)))
         (setf (cx6-nr c) (+ r 1))
         (intern (concatenate 'string \"R\" (write-to-string r)) :keyword)))
     (defun em6 (c i)
       (setf (cx6-insts c) (append (cx6-insts c) (list i))))
     (defgeneric cn6 (node ctx))
     (defmethod cn6 ((node ast-i6) ctx)
       (let ((r (mr6 ctx)))
         (em6 ctx (list :const r (ast-i6-v node)))
         r))
     (defmethod cn6 ((node ast-v6) ctx)
       (cdr (assoc (ast-v6-n node) (cx6-env ctx))))
     (defmethod cn6 ((node ast-b6) ctx)
       (let ((l (cn6 (ast-b6-l node) ctx))
             (rv (cn6 (ast-b6-r node) ctx))
             (dst (mr6 ctx)))
         (em6 ctx (list (ast-b6-op node) dst l rv))
         dst))
     (let ((ctx (make-cx6)))
       (let ((r (cn6 (make-instance 'ast-b6 :op :add
                           :l (make-instance 'ast-i6 :v 10)
                           :r (make-instance 'ast-i6 :v 20))
                       ctx)))
         (list r (length (cx6-insts ctx))))))"
  "Readable self-hosting CLOS compiler fixture with generic dispatch.")

(defparameter *self-host-make-register-program*
  "(progn
     (defstruct compiler-ctx (next-register 0))
     (defun make-register (ctx)
       (let ((reg (intern (format nil \"R~D\" (compiler-ctx-next-register ctx)) :keyword)))
         (setf (compiler-ctx-next-register ctx) (+ (compiler-ctx-next-register ctx) 1))
         reg))
     (let ((ctx (make-compiler-ctx)))
       (list (make-register ctx)
             (make-register ctx)
             (make-register ctx))))"
  "Readable self-hosting register allocation utility fixture.")

(defparameter *self-host-mini-compiler-program*
  "(progn
     (defstruct mc-int (val 0))
     (defstruct mc-binop (op nil) (l nil) (r nil))
     (defstruct mc-ctx (instrs nil) (nreg 0))
     (defun mc-reg (ctx)
       (let ((r (intern (format nil \"R~D\" (mc-ctx-nreg ctx)) :keyword)))
         (setf (mc-ctx-nreg ctx) (+ (mc-ctx-nreg ctx) 1))
         r))
     (defun mc-emit (ctx inst)
       (setf (mc-ctx-instrs ctx) (cons inst (mc-ctx-instrs ctx))))
     (defun mc-compile (node ctx)
       (cond
         ((mc-int-p node)
          (let ((dst (mc-reg ctx)))
            (mc-emit ctx (list :const dst (mc-int-val node)))
            dst))
         ((mc-binop-p node)
          (let* ((lr (mc-compile (mc-binop-l node) ctx))
                 (rr (mc-compile (mc-binop-r node) ctx))
                 (dst (mc-reg ctx))
                 (opcode (case (mc-binop-op node)
                           (+ :add)
                           (- :sub)
                           (* :mul))))
            (mc-emit ctx (list opcode dst lr rr))
            dst))
         (t (error \"unknown\"))))
     (defun mc-run (instrs)
       (let ((regs (make-hash-table)))
         (dolist (inst instrs)
           (let ((op (car inst)))
             (cond
               ((eq op :const)
                (setf (gethash (cadr inst) regs) (caddr inst)))
               ((member op '(:add :sub :mul))
                (let ((l (gethash (caddr inst) regs))
                      (r (gethash (cadddr inst) regs)))
                  (setf (gethash (cadr inst) regs)
                        (case op
                          (:add (+ l r))
                          (:sub (- l r))
                          (:mul (* l r)))))))))
         (gethash (cadr (car (last instrs))) regs)))
     (let ((ctx (make-mc-ctx)))
       (mc-compile (make-mc-binop :op '*
                    :l (make-mc-binop :op '+
                         :l (make-mc-int :val 3)
                         :r (make-mc-int :val 4))
                    :r (make-mc-binop :op '-
                         :l (make-mc-int :val 10)
                         :r (make-mc-int :val 5)))
                  ctx)
       (mc-run (nreverse (mc-ctx-instrs ctx)))))"
  "Readable self-hosting mini-compiler pipeline fixture.")

(defparameter *self-host-clos-compiler-full-program*
  "(progn
     (defclass c-node () ())
     (defclass c-int (c-node) ((val :initarg :val :reader c-int-val)))
     (defclass c-add (c-node)
       ((lhs :initarg :lhs :reader c-add-lhs)
        (rhs :initarg :rhs :reader c-add-rhs)))
     (defclass c-mul (c-node)
       ((lhs :initarg :lhs :reader c-mul-lhs)
        (rhs :initarg :rhs :reader c-mul-rhs)))
     (defclass c-ctx ()
       ((instrs :initform nil :accessor c-ctx-instrs)
        (nreg :initform 0 :accessor c-ctx-nreg)))
     (defun c-reg (ctx)
       (let ((r (intern (format nil \"R~D\" (c-ctx-nreg ctx)) :keyword)))
         (setf (c-ctx-nreg ctx) (+ (c-ctx-nreg ctx) 1))
         r))
     (defun c-emit (ctx inst)
       (setf (c-ctx-instrs ctx) (cons inst (c-ctx-instrs ctx))))
     (defgeneric c-compile (node ctx))
     (defmethod c-compile ((node c-int) ctx)
       (let ((dst (c-reg ctx)))
         (c-emit ctx (list :const dst (c-int-val node)))
         dst))
     (defmethod c-compile ((node c-add) ctx)
       (let* ((lr (c-compile (c-add-lhs node) ctx))
              (rr (c-compile (c-add-rhs node) ctx))
              (dst (c-reg ctx)))
         (c-emit ctx (list :add dst lr rr))
         dst))
     (defmethod c-compile ((node c-mul) ctx)
       (let* ((lr (c-compile (c-mul-lhs node) ctx))
              (rr (c-compile (c-mul-rhs node) ctx))
              (dst (c-reg ctx)))
         (c-emit ctx (list :mul dst lr rr))
         dst))
     (let ((ctx (make-instance 'c-ctx)))
       (c-compile (make-instance 'c-add
                    :lhs (make-instance 'c-mul
                           :lhs (make-instance 'c-int :val 3)
                           :rhs (make-instance 'c-int :val 4))
                    :rhs (make-instance 'c-int :val 5))
                  ctx)
       (nreverse (c-ctx-instrs ctx))))"
  "Readable full self-hosting CLOS compiler pipeline fixture.")
