(in-package :cl-cc/test)

(defparameter *self-host-optimizer-pipeline-program*
  "(progn
     (defclass ir () ())
     (defclass ir-const (ir) ((val :initarg :val :accessor ir-const-val)))
     (defclass ir-add (ir) ((lhs :initarg :lhs :accessor ir-add-lhs)
                            (rhs :initarg :rhs :accessor ir-add-rhs)))
     (defclass ir-mul (ir) ((lhs :initarg :lhs :accessor ir-mul-lhs)
                            (rhs :initarg :rhs :accessor ir-mul-rhs)))
     (defclass ir-seq (ir) ((forms :initarg :forms :accessor ir-seq-forms)))
     (defparameter *opt-count* 0)
     (defun mk-const (v) (make-instance 'ir-const :val v))
     (defun mk-add (l r) (make-instance 'ir-add :lhs l :rhs r))
     (defun mk-mul (l r) (make-instance 'ir-mul :lhs l :rhs r))
     (defun mk-seq (fs) (make-instance 'ir-seq :forms fs))
     (defgeneric opt (node))
     (defmethod opt ((n ir-const)) n)
     (defmethod opt ((n ir-add))
       (let ((l (opt (ir-add-lhs n))) (r (opt (ir-add-rhs n))))
         (if (and (typep l 'ir-const) (typep r 'ir-const))
             (progn
               (setq *opt-count* (+ *opt-count* 1))
               (mk-const (+ (ir-const-val l) (ir-const-val r))))
             (mk-add l r))))
     (defmethod opt ((n ir-mul))
       (let ((l (opt (ir-mul-lhs n))) (r (opt (ir-mul-rhs n))))
         (if (and (typep l 'ir-const) (typep r 'ir-const))
             (progn
               (setq *opt-count* (+ *opt-count* 1))
               (mk-const (* (ir-const-val l) (ir-const-val r))))
             (mk-mul l r))))
     (defmethod opt ((n ir-seq)) (mk-seq (mapcar #'opt (ir-seq-forms n))))
     (defgeneric eval-ir (node))
     (defmethod eval-ir ((n ir-const)) (ir-const-val n))
     (defmethod eval-ir ((n ir-add)) (+ (eval-ir (ir-add-lhs n)) (eval-ir (ir-add-rhs n))))
     (defmethod eval-ir ((n ir-mul)) (* (eval-ir (ir-mul-lhs n)) (eval-ir (ir-mul-rhs n))))
     (defmethod eval-ir ((n ir-seq))
       (let ((r 0))
         (dolist (f (ir-seq-forms n) r)
           (setq r (eval-ir f)))))
     (let ((ir-prog (mk-seq (list (mk-add (mk-const 10) (mk-const 20))
                                  (mk-mul (mk-const 3) (mk-const 10))))))
       (eval-ir (opt ir-prog))))"
  "Readable self-hosting mini-optimizer fixture used by integration tests.")

(defparameter *self-host-macro-system-program*
  "(progn
     (defvar *mx* (make-hash-table :test 'eq))
     (defun register-macro (name fn) (setf (gethash name *mx*) fn))
     (defun mx-expand (form)
       (if (consp form)
           (let ((expander (gethash (car form) *mx*)))
             (if expander
                 (mx-expand (funcall expander form))
                 (mapcar (lambda (x) (if (consp x) (mx-expand x) x)) form)))
           form))
     (register-macro 'when
       (lambda (f) (list 'if (cadr f) (cons 'progn (cddr f)) nil)))
      (mx-expand '(when x (when y z))))"
  "Readable self-hosting macro-expansion fixture used by integration tests.")

(defparameter *self-host-simple-macro-expander-program*
  "(progn
     (defvar *macros* (make-hash-table :test 'eq))
     (defun reg-macro (name fn) (setf (gethash name *macros*) fn))
     (defun expand (form)
       (if (and (consp form) (symbolp (car form)))
           (let ((ex (gethash (car form) *macros*)))
             (if ex
                 (expand (funcall ex form nil))
                 (mapcar (lambda (x) (if (consp x) (expand x) x)) form)))
           form))
     (reg-macro 'when
                (lambda (f e)
                  (declare (ignore e))
                  (list 'if (second f) (cons 'progn (cddr f)) nil)))
     (expand '(when x (+ 1 2))))"
  "Readable single-step self-hosting macro-expander fixture used by integration tests.")

(defparameter *self-host-type-checker-program*
  "(progn
     (defclass ty () ())
     (defclass ty-int (ty) ())
     (defclass ty-str (ty) ())
     (defclass ty-fn (ty)
       ((arg :initarg :arg :accessor ty-fn-arg)
        (ret :initarg :ret :accessor ty-fn-ret)))
     (defgeneric ty-eq (a b))
     (defmethod ty-eq ((a ty-int) (b ty-int)) t)
     (defmethod ty-eq ((a ty-str) (b ty-str)) t)
     (defmethod ty-eq ((a ty-fn) (b ty-fn))
       (and (ty-eq (ty-fn-arg a) (ty-fn-arg b))
            (ty-eq (ty-fn-ret a) (ty-fn-ret b))))
     (defmethod ty-eq ((a t) (b t)) nil)
     (defvar *env* (make-hash-table :test 'eq))
     (defun tc (expr)
       (cond
         ((numberp expr) (make-instance 'ty-int))
         ((stringp expr) (make-instance 'ty-str))
         ((symbolp expr) (gethash expr *env*))
         ((and (consp expr) (eq (car expr) 'add))
          (let ((l (tc (cadr expr)))
                (r (tc (caddr expr))))
            (if (and (typep l 'ty-int) (typep r 'ty-int))
                (make-instance 'ty-int)
                (error \"type mismatch\"))))
         (t (error \"unknown\"))))
     (setf (gethash 'x *env*) (make-instance 'ty-int))
     (let ((t1 (tc '(add x 1)))
           (t2 (tc '(add 2 3))))
        (if (and (typep t1 'ty-int) (typep t2 'ty-int)) 'ok 'fail)))"
  "Readable self-hosting HM-style type-checker fixture used by integration tests.")

(defparameter *self-host-clos-full-pipeline-program*
  "(progn
     (defclass ast () ())
     (defclass ast-lit (ast)
       ((value :initarg :value :accessor ast-lit-value)))
     (defclass ast-var (ast)
       ((name :initarg :name :accessor ast-var-name)))
     (defclass ast-binop (ast)
       ((op :initarg :op :accessor ast-binop-op)
        (lhs :initarg :lhs :accessor ast-binop-lhs)
        (rhs :initarg :rhs :accessor ast-binop-rhs)))
     (defclass ast-let (ast)
       ((var :initarg :var :accessor ast-let-var)
        (init :initarg :init :accessor ast-let-init)
        (body :initarg :body :accessor ast-let-body)))
     (defclass ast-if (ast)
       ((test :initarg :test :accessor ast-if-test)
        (then :initarg :then :accessor ast-if-then)
        (else :initarg :else :accessor ast-if-else)))
     (defun parse (sexp)
       (cond
         ((numberp sexp) (make-instance 'ast-lit :value sexp))
         ((symbolp sexp) (make-instance 'ast-var :name sexp))
         ((not (consp sexp)) (error \"bad\"))
         ((eq (car sexp) 'let)
          (make-instance 'ast-let
                         :var (caar (cadr sexp))
                         :init (parse (cadar (cadr sexp)))
                         :body (parse (caddr sexp))))
         ((eq (car sexp) 'if)
          (make-instance 'ast-if
                         :test (parse (cadr sexp))
                         :then (parse (caddr sexp))
                         :else (parse (cadddr sexp))))
         ((member (car sexp) '(+ - * =))
          (make-instance 'ast-binop
                         :op (car sexp)
                         :lhs (parse (cadr sexp))
                         :rhs (parse (caddr sexp))))
         (t (error \"unknown\"))))
     (defvar *rc* 0)
     (defvar *code* nil)
     (defun fr ()
       (let ((r (intern (format nil \"R~D\" *rc*))))
         (setq *rc* (+ *rc* 1))
         r))
     (defun em (inst) (push inst *code*))
     (defgeneric cn (node env))
     (defmethod cn ((n ast-lit) env)
       (let ((r (fr)))
         (em (list 'CONST r (ast-lit-value n)))
         r))
     (defmethod cn ((n ast-var) env)
       (cdr (assoc (ast-var-name n) env)))
     (defmethod cn ((n ast-binop) env)
       (let ((l (cn (ast-binop-lhs n) env))
             (r (cn (ast-binop-rhs n) env))
             (d (fr)))
         (em (list (ast-binop-op n) d l r))
         d))
     (defmethod cn ((n ast-let) env)
       (cn (ast-let-body n)
           (acons (ast-let-var n) (cn (ast-let-init n) env) env)))
     (defmethod cn ((n ast-if) env)
       (let ((tr (cn (ast-if-test n) env))
             (th (cn (ast-if-then n) env))
             (el (cn (ast-if-else n) env))
             (d (fr)))
         (em (list 'SEL d tr th el))
         d))
     (defun rp (instrs)
       (let ((regs (make-hash-table :test 'eq)))
         (dolist (inst instrs)
           (let ((op (nth 0 inst))
                 (dst (nth 1 inst)))
             (cond
               ((eq op 'CONST)
                (setf (gethash dst regs) (nth 2 inst)))
               ((eq op 'SEL)
                (let ((tv (gethash (nth 2 inst) regs)))
                  (setf (gethash dst regs)
                        (if (and tv (not (zerop tv)))
                            (gethash (nth 3 inst) regs)
                            (gethash (nth 4 inst) regs)))))
               (t
                (let ((a (gethash (nth 2 inst) regs))
                      (b (gethash (nth 3 inst) regs)))
                  (setf (gethash dst regs)
                        (cond
                          ((eq op '+) (+ a b))
                          ((eq op '-) (- a b))
                          ((eq op '*) (* a b))
                          ((eq op '=) (if (= a b) 1 0))
                          (t 0))))))))
         (gethash (intern (format nil \"R~D\" (- *rc* 1))) regs)))
     (setq *rc* 0)
     (setq *code* nil)
     (cn (parse '(let ((x 10))
                   (if (= x 10)
                       (* x x)
                       (+ x 1))))
         nil)
     (rp (nreverse *code*)))"
  "Readable full CLOS AST-to-register self-hosting compiler fixture.")

(defparameter *self-host-mapcar-inst-sexp-program*
  "(progn
     (defclass instruction () ())
     (defclass inst-const (instruction)
       ((dst :initarg :dst :reader inst-dst)
        (value :initarg :value :reader inst-value)))
     (defclass inst-add (instruction)
       ((dst :initarg :dst :reader inst-dst)
        (lhs :initarg :lhs :reader inst-lhs)
        (rhs :initarg :rhs :reader inst-rhs)))
     (defgeneric inst-sexp (inst))
     (defmethod inst-sexp ((inst inst-const))
       (list :const (inst-dst inst) (inst-value inst)))
     (defmethod inst-sexp ((inst inst-add))
       (list :add (inst-dst inst) (inst-lhs inst) (inst-rhs inst)))
     (let ((program (list (make-instance 'inst-const :dst 'r0 :value 42)
                          (make-instance 'inst-const :dst 'r1 :value 7)
                          (make-instance 'inst-add :dst 'r2 :lhs 'r0 :rhs 'r1))))
       (mapcar #'inst-sexp program)))"
  "Readable self-hosting instruction serialization fixture used by mapcar tests.")

(defparameter *self-host-compiler-context-program*
  "(progn
     (defclass compiler-context ()
       ((instructions :initform nil :accessor ctx-instructions)
        (next-register :initform 0 :accessor ctx-next-register)
        (next-label :initform 0 :accessor ctx-next-label)))
     (defun make-register (ctx)
       (let ((n (ctx-next-register ctx)))
         (setf (ctx-next-register ctx) (+ n 1))
         (intern (concatenate 'string \"R\" (write-to-string n)) :keyword)))
     (defun make-label (ctx prefix)
       (let ((n (ctx-next-label ctx)))
         (setf (ctx-next-label ctx) (+ n 1))
         (concatenate 'string prefix \"_\" (write-to-string n))))
     (defun emit (ctx inst)
       (setf (ctx-instructions ctx) (cons inst (ctx-instructions ctx))))
     (let ((ctx (make-instance 'compiler-context)))
       (let ((r0 (make-register ctx))
             (r1 (make-register ctx)))
         (emit ctx (list :const r0 42))
         (emit ctx (list :const r1 7))
         (emit ctx (list :add (make-register ctx) r0 r1))
         (nreverse (ctx-instructions ctx)))))"
  "Readable self-hosting compiler-context fixture with register and label helpers.")

(defparameter *self-host-ast-compile-dispatch-program*
  "(progn
     (defclass ctx ()
       ((instrs :initform nil :accessor ctx-instrs)
        (rc :initform 0 :accessor ctx-rc)))
     (defun mk-r (c)
       (let ((n (ctx-rc c)))
         (setf (ctx-rc c) (+ n 1))
         (intern (concatenate 'string \"R\" (write-to-string n)) :keyword)))
     (defclass nd () ())
     (defclass nd-int (nd) ((v :initarg :v :reader nd-v)))
     (defclass nd-op (nd)
       ((o :initarg :o :reader nd-o)
        (l :initarg :l :reader nd-l)
        (r :initarg :r :reader nd-r)))
     (defgeneric cmp (n c))
     (defmethod cmp ((n nd-int) c)
       (let ((d (mk-r c)))
         (setf (ctx-instrs c) (cons (list :const d (nd-v n)) (ctx-instrs c)))
         d))
     (defmethod cmp ((n nd-op) c)
       (let* ((lr (cmp (nd-l n) c))
              (rr (cmp (nd-r n) c))
              (d (mk-r c)))
         (setf (ctx-instrs c) (cons (list (nd-o n) d lr rr) (ctx-instrs c)))
         d))
     (let ((c (make-instance 'ctx)))
       (cmp (make-instance 'nd-op :o :add
              :l (make-instance 'nd-op :o :mul
                   :l (make-instance 'nd-int :v 3)
                   :r (make-instance 'nd-int :v 4))
              :r (make-instance 'nd-int :v 5))
            c)
       (nreverse (ctx-instrs c))))"
  "Readable self-hosting CLOS AST compile-dispatch fixture.")

