(in-package :cl-cc)

;;; ── Exception handling: catch / throw / unwind-protect / handler-case ────

(defmethod compile-ast ((node ast-catch) ctx)
  (setf (ctx-tail-position ctx) nil)
  (let ((tag-reg (compile-ast (ast-catch-tag node) ctx))
        (result-reg (make-register ctx))
        (handler-label (make-label ctx "catch_handler"))
        (end-label (make-label ctx "catch_end")))
    (emit ctx (make-vm-establish-catch
               :tag-reg tag-reg
               :handler-label handler-label
               :result-reg result-reg))
    (let ((body-result (let ((last nil))
                         (dolist (form (ast-catch-body node))
                           (setf last (compile-ast form ctx)))
                         last)))
      (emit ctx (make-vm-move :dst result-reg :src body-result)))
    (emit ctx (make-vm-remove-handler))
    (emit ctx (make-vm-jump :label end-label))
    (emit ctx (make-vm-label :name handler-label))
    (emit ctx (make-vm-label :name end-label))
    result-reg))

(defmethod compile-ast ((node ast-throw) ctx)
  (setf (ctx-tail-position ctx) nil)
  (let ((tag-reg (compile-ast (ast-throw-tag node) ctx))
        (value-reg (compile-ast (ast-throw-value node) ctx)))
    (emit ctx (make-vm-throw :tag-reg tag-reg :value-reg value-reg))
    value-reg))

(defmethod compile-ast ((node ast-unwind-protect) ctx)
  (setf (ctx-tail-position ctx) nil)
  (let ((result-reg (make-register ctx))
        (error-reg (make-register ctx))
        (error-flag-reg (make-register ctx))
        (handler-label (make-label ctx "unwind_handler"))
        (cleanup-label (make-label ctx "unwind_cleanup"))
        (end-label (make-label ctx "unwind_end")))
    (emit ctx (make-vm-const :dst error-flag-reg :value nil))
    (emit ctx (make-vm-establish-handler
               :handler-label handler-label
               :result-reg error-reg
               :error-type 'error))
    (let ((protected-result (compile-ast (ast-unwind-protected node) ctx)))
      (emit ctx (make-vm-move :dst result-reg :src protected-result)))
    (emit ctx (make-vm-remove-handler))
    (emit ctx (make-vm-jump :label cleanup-label))
    (emit ctx (make-vm-label :name handler-label))
    (emit ctx (make-vm-const :dst error-flag-reg :value t))
    (emit ctx (make-vm-label :name cleanup-label))
    (dolist (form (ast-unwind-cleanup node))
      (compile-ast form ctx))
    (emit ctx (make-vm-jump-zero :reg error-flag-reg :label end-label))
    (emit ctx (make-vm-sync-handler-regs))
    (emit ctx (make-vm-signal-error :error-reg error-reg))
    (emit ctx (make-vm-label :name end-label))
    result-reg))

(defmethod compile-ast ((node ast-handler-case) ctx)
  "Compile handler-case: establish handlers, run protected form, handle errors."
  (setf (ctx-tail-position ctx) nil)
  (let* ((clauses (ast-handler-case-clauses node))
         (result-reg (make-register ctx))
         (normal-exit-label (make-label ctx "handler_case_exit"))
         (handler-infos (mapcar (lambda (clause)
                                  (declare (ignore clause))
                                  (list (make-label ctx "handler")
                                        (make-register ctx)))
                                clauses)))
    (loop for clause in (reverse clauses)
          for info in (reverse handler-infos)
          do (emit ctx (make-vm-establish-handler
                        :handler-label (first info)
                        :result-reg (second info)
                        :error-type (first clause))))
    (let ((form-result (compile-ast (ast-handler-case-form node) ctx)))
      (emit ctx (make-vm-move :dst result-reg :src form-result)))
    (dotimes (i (length clauses))
      (emit ctx (make-vm-remove-handler)))
    (emit ctx (make-vm-jump :label normal-exit-label))
    (loop for clause in clauses
          for info in handler-infos
          do (let* ((var (second clause))
                    (body (cddr clause))
                    (handler-label (first info))
                    (error-reg (second info))
                    (old-env (ctx-env ctx)))
               (emit ctx (make-vm-label :name handler-label))
               (unwind-protect
                    (progn
                      (when var
                        (push (cons var error-reg) (ctx-env ctx)))
                      (let ((last-reg nil))
                        (if body
                            (dolist (form body)
                              (setf last-reg (compile-ast form ctx)))
                            (setf last-reg error-reg))
                        (emit ctx (make-vm-move :dst result-reg :src last-reg))))
                 (setf (ctx-env ctx) old-env))
               (emit ctx (make-vm-jump :label normal-exit-label))))
    (emit ctx (make-vm-label :name normal-exit-label))
    result-reg))

;;; ── Multiple values ───────────────────────────────────────────────────────

(defmethod compile-ast ((node ast-values) ctx)
  (setf (ctx-tail-position ctx) nil)
  (let* ((src-regs (mapcar (lambda (form) (compile-ast form ctx))
                           (ast-values-forms node)))
         (dst (make-register ctx)))
    (emit ctx (make-vm-values :dst dst :src-regs src-regs))
    dst))

(defmethod compile-ast ((node ast-multiple-value-bind) ctx)
  (setf (ctx-tail-position ctx) nil)
  (let* ((vars (ast-mvb-vars node))
         (body (ast-mvb-body node))
         (old-env (ctx-env ctx)))
    (compile-ast (ast-mvb-values-form node) ctx)
    (let ((var-regs (loop for v in vars collect (make-register ctx))))
      (emit ctx (make-vm-mv-bind :dst-regs var-regs))
      (unwind-protect
           (progn
             (setf (ctx-env ctx)
                   (append (mapcar #'cons vars var-regs) (ctx-env ctx)))
             (let ((last nil))
               (dolist (form body)
                 (setf last (compile-ast form ctx)))
               last))
        (setf (ctx-env ctx) old-env)))))

(defmethod compile-ast ((node ast-apply) ctx)
  (setf (ctx-tail-position ctx) nil)
  (let* ((func-reg (compile-ast (ast-apply-func node) ctx))
         (result-reg (make-register ctx)))
    (labels ((compile-apply-arg (arg)
               (compile-ast arg ctx)))
      (let* ((args (ast-apply-args node))
             (spread-arg (car (last args)))
             (spread-val (and spread-arg
                              (typep spread-arg 'ast-quote)
                              (ast-quote-value spread-arg))))
        (if (and spread-val (or (null spread-val) (listp spread-val)))
            (let ((leading-regs (mapcar #'compile-apply-arg (butlast args)))
                  (spread-regs (mapcar (lambda (v)
                                         (compile-ast (make-ast-quote :value v) ctx))
                                       spread-val)))
              (emit ctx (make-vm-call :dst result-reg :func func-reg
                                      :args (append leading-regs spread-regs))))
            (let ((arg-regs (mapcar #'compile-apply-arg args)))
              (emit ctx (make-vm-apply :dst result-reg :func func-reg :args arg-regs))))))
    result-reg))

(defmethod compile-ast ((node ast-multiple-value-call) ctx)
  "Evaluate FUNC, collect ALL values from each arg form, apply FUNC to them."
  (setf (ctx-tail-position ctx) nil)
  (let* ((func-reg (compile-ast (ast-mv-call-func node) ctx))
         (args (ast-mv-call-args node))
         (result-reg (make-register ctx)))
    (if (null args)
        (let ((empty-reg (make-register ctx)))
          (emit ctx (make-vm-const :dst empty-reg :value nil))
          (emit ctx (make-vm-apply :dst result-reg :func func-reg :args (list empty-reg))))
        (let ((list-regs
               (mapcar (lambda (arg)
                         (emit ctx (make-vm-clear-values))
                         (let ((primary-reg (compile-ast arg ctx)))
                           (emit ctx (make-vm-ensure-values :src primary-reg))
                           (let ((lr (make-register ctx)))
                             (emit ctx (make-vm-values-to-list :dst lr))
                             lr)))
                       args)))
          (let ((combined-reg
                 (reduce (lambda (acc lr)
                           (let ((new-reg (make-register ctx)))
                             (emit ctx (make-vm-append :dst new-reg :src1 acc :src2 lr))
                             new-reg))
                         (cdr list-regs)
                         :initial-value (car list-regs))))
            (emit ctx (make-vm-apply :dst result-reg :func func-reg
                                     :args (list combined-reg))))))
    result-reg))

(defmethod compile-ast ((node ast-multiple-value-prog1) ctx)
  "Save result of first form, evaluate remaining forms, return saved result."
  (setf (ctx-tail-position ctx) nil)
  (let ((first-reg (compile-ast (ast-mv-prog1-first node) ctx))
        (result-reg (make-register ctx)))
    (emit ctx (make-vm-move :dst result-reg :src first-reg))
    (dolist (form (ast-mv-prog1-forms node))
      (compile-ast form ctx))
    result-reg))
