(in-package :cl-cc/compile)

;;; ── Exception handling: catch / throw / unwind-protect / handler-case ────

(defmethod compile-ast ((node ast-catch) ctx)
  (setf (ctx-tail-position ctx) nil)
  (let ((tag-reg (compile-ast (ast-catch-tag node) ctx))
        (result-reg (make-register ctx))
        (handler-label (make-label ctx "catch_handler"))
        (end-label (make-label ctx "catch_end")))
    (emit ctx (make-vm-establish-catch
               :tag-reg tag-reg
               :handler-label handler-label
               :result-reg result-reg))
    (let ((body-result (let ((last nil))
                         (dolist (form (ast-catch-body node))
                           (setf last (compile-ast form ctx)))
                         last)))
      (emit ctx (make-vm-move :dst result-reg :src body-result)))
    (emit ctx (make-vm-remove-handler))
    (emit ctx (make-vm-jump :label end-label))
    (emit ctx (make-vm-label :name handler-label))
    (emit ctx (make-vm-label :name end-label))
    result-reg))

(defmethod compile-ast ((node ast-throw) ctx)
  (setf (ctx-tail-position ctx) nil)
  (let ((tag-reg (compile-ast (ast-throw-tag node) ctx))
        (value-reg (compile-ast (ast-throw-value node) ctx)))
    (emit ctx (make-vm-throw :tag-reg tag-reg :value-reg value-reg))
    value-reg))

(defmethod compile-ast ((node ast-unwind-protect) ctx)
  (setf (ctx-tail-position ctx) nil)
  (let ((result-reg (make-register ctx))
        (error-reg (make-register ctx))
        (error-flag-reg (make-register ctx))
        (handler-label (make-label ctx "unwind_handler"))
        (cleanup-label (make-label ctx "unwind_cleanup"))
        (end-label (make-label ctx "unwind_end")))
    (emit ctx (make-vm-const :dst error-flag-reg :value nil))
    (emit ctx (make-vm-establish-handler
               :handler-label handler-label
               :result-reg error-reg
               :error-type 'error))
    (let ((protected-result (compile-ast (ast-unwind-protected node) ctx)))
      (emit ctx (make-vm-move :dst result-reg :src protected-result)))
    (emit ctx (make-vm-remove-handler))
    (emit ctx (make-vm-jump :label cleanup-label))
    (emit ctx (make-vm-label :name handler-label))
    (emit ctx (make-vm-const :dst error-flag-reg :value t))
    (emit ctx (make-vm-label :name cleanup-label))
    (dolist (form (ast-unwind-cleanup node))
      (compile-ast form ctx))
    (emit ctx (make-vm-jump-zero :reg error-flag-reg :label end-label))
    (emit ctx (make-vm-sync-handler-regs))
    (emit ctx (make-vm-signal-error :error-reg error-reg))
    (emit ctx (make-vm-label :name end-label))
    result-reg))

(defmethod compile-ast ((node ast-handler-case) ctx)
  "Compile handler-case: establish handlers, run protected form, handle errors."
  (setf (ctx-tail-position ctx) nil)
  (let ((clauses (ast-handler-case-clauses node))
        (result-reg (make-register ctx))
        (normal-exit-label (make-label ctx "handler_case_exit"))
        (handler-infos nil)
        (handler-infos-rev nil)
        (clauses-rev nil)
        (handler-count 0))
    (let ((tail clauses))
      (tagbody
       build-infos
         (when (null tail)
           (go build-done))
         (let ((info (list (make-label ctx "handler")
                           (make-register ctx))))
           (setf handler-infos-rev (cons info handler-infos-rev))
           (setf clauses-rev (cons (car tail) clauses-rev))
           (setf handler-count (+ handler-count 1)))
         (setf tail (cdr tail))
         (go build-infos)
       build-done))
    (let ((tail handler-infos-rev))
      (tagbody
       reverse-infos
         (when (null tail)
           (go reverse-done))
         (setf handler-infos (cons (car tail) handler-infos))
         (setf tail (cdr tail))
         (go reverse-infos)
       reverse-done))
    (let ((clause-tail clauses-rev)
          (info-tail handler-infos-rev))
      (tagbody
       establish-handlers
         (when (or (null clause-tail) (null info-tail))
           (go establish-done))
         (let ((clause (car clause-tail))
               (info (car info-tail)))
           (emit ctx (make-vm-establish-handler
                      :handler-label (first info)
                      :result-reg (second info)
                      :error-type (first clause))))
         (setf clause-tail (cdr clause-tail))
         (setf info-tail (cdr info-tail))
         (go establish-handlers)
       establish-done))
    (let ((form-result (compile-ast (ast-handler-case-form node) ctx)))
      (emit ctx (make-vm-move :dst result-reg :src form-result)))
    (let ((remaining handler-count))
      (tagbody
       remove-handlers
         (when (<= remaining 0)
           (go remove-done))
         (emit ctx (make-vm-remove-handler))
         (setf remaining (- remaining 1))
         (go remove-handlers)
       remove-done))
    (emit ctx (make-vm-jump :label normal-exit-label))
    (let ((clause-tail clauses)
          (info-tail handler-infos))
      (tagbody
       emit-handler-bodies
         (when (or (null clause-tail) (null info-tail))
           (go emit-handler-done))
         (let* ((clause (car clause-tail))
                (info (car info-tail))
                (var (second clause))
                (body (cddr clause))
                (handler-label (first info))
                (error-reg (second info))
                (old-env (ctx-env ctx)))
           (emit ctx (make-vm-label :name handler-label))
           (when var
             (setf (ctx-env ctx) (cons (cons var error-reg) (ctx-env ctx))))
           (let ((last-reg nil)
                 (body-tail body))
             (if body-tail
                 (tagbody
                  compile-handler-body
                    (when (null body-tail)
                      (go compile-handler-done))
                    (setf last-reg (compile-ast (car body-tail) ctx))
                    (setf body-tail (cdr body-tail))
                    (go compile-handler-body)
                  compile-handler-done)
                 (setf last-reg error-reg))
             (emit ctx (make-vm-move :dst result-reg :src last-reg)))
           (setf (ctx-env ctx) old-env)
           (emit ctx (make-vm-jump :label normal-exit-label)))
         (setf clause-tail (cdr clause-tail))
         (setf info-tail (cdr info-tail))
         (go emit-handler-bodies)
       emit-handler-done))
    (emit ctx (make-vm-label :name normal-exit-label))
    result-reg))

;;; ── Multiple values ───────────────────────────────────────────────────────

(defmethod compile-ast ((node ast-values) ctx)
  (setf (ctx-tail-position ctx) nil)
  (let* ((src-regs (mapcar (lambda (form) (compile-ast form ctx))
                           (ast-values-forms node)))
         (dst (make-register ctx)))
    (emit ctx (make-vm-values :dst dst :src-regs src-regs))
    dst))

(defmethod compile-ast ((node ast-multiple-value-bind) ctx)
  (setf (ctx-tail-position ctx) nil)
  (let* ((vars (ast-mvb-vars node))
         (body (ast-mvb-body node))
         (old-env (ctx-env ctx))
         (values-form (ast-mvb-values-form node))
         (var-regs nil))
    (if (typep values-form 'ast-values)
        (let ((src-regs nil)
              (forms-tail (ast-values-forms values-form)))
          (tagbody
           compile-value-forms
             (when (null forms-tail)
               (go compile-value-forms-done))
             (setf src-regs (cons (compile-ast (car forms-tail) ctx) src-regs))
             (setf forms-tail (cdr forms-tail))
             (go compile-value-forms)
           compile-value-forms-done)
          (let ((reverse-tail src-regs)
                (src-regs-forward nil))
            (tagbody
             reverse-value-regs
               (when (null reverse-tail)
                 (go reverse-value-regs-done))
               (setf src-regs-forward (cons (car reverse-tail) src-regs-forward))
               (setf reverse-tail (cdr reverse-tail))
               (go reverse-value-regs)
             reverse-value-regs-done)
            (let ((vars-tail vars)
                  (src-tail src-regs-forward)
                  (regs-rev nil))
              (tagbody
               bind-value-vars
                 (when (null vars-tail)
                   (go bind-value-vars-done))
                 (if src-tail
                     (progn
                       (setf regs-rev (cons (car src-tail) regs-rev))
                       (setf src-tail (cdr src-tail)))
                     (let ((nil-reg (make-register ctx)))
                       (emit ctx (make-vm-const :dst nil-reg :value nil))
                       (setf regs-rev (cons nil-reg regs-rev))))
                 (setf vars-tail (cdr vars-tail))
                 (go bind-value-vars)
               bind-value-vars-done)
              (let ((tail regs-rev))
                (tagbody
                 reverse-bound-regs
                   (when (null tail)
                     (go reverse-bound-regs-done))
                   (setf var-regs (cons (car tail) var-regs))
                   (setf tail (cdr tail))
                   (go reverse-bound-regs)
                 reverse-bound-regs-done)))))
        (progn
          (compile-ast values-form ctx)
          (let ((vars-tail vars)
                (regs-rev nil))
            (tagbody
             allocate-mv-regs
               (when (null vars-tail)
                 (go allocate-mv-regs-done))
               (setf regs-rev (cons (make-register ctx) regs-rev))
               (setf vars-tail (cdr vars-tail))
               (go allocate-mv-regs)
             allocate-mv-regs-done)
            (let ((tail regs-rev))
              (tagbody
               reverse-mv-regs
                 (when (null tail)
                   (go reverse-mv-regs-done))
                 (setf var-regs (cons (car tail) var-regs))
                 (setf tail (cdr tail))
                 (go reverse-mv-regs)
               reverse-mv-regs-done))
            (emit ctx (make-vm-mv-bind :dst-regs var-regs)))))
    (let ((vars-tail vars)
          (regs-tail var-regs)
          (bindings-rev nil))
      (tagbody
       build-mvb-bindings
         (when (or (null vars-tail) (null regs-tail))
           (go build-mvb-bindings-done))
         (setf bindings-rev (cons (cons (car vars-tail) (car regs-tail)) bindings-rev))
         (setf vars-tail (cdr vars-tail))
         (setf regs-tail (cdr regs-tail))
         (go build-mvb-bindings)
       build-mvb-bindings-done)
      (let ((tail bindings-rev))
        (tagbody
         install-mvb-bindings
           (when (null tail)
             (go install-mvb-bindings-done))
           (setf (ctx-env ctx) (cons (car tail) (ctx-env ctx)))
           (setf tail (cdr tail))
           (go install-mvb-bindings)
         install-mvb-bindings-done)))
    (let ((last nil)
          (body-tail body))
      (tagbody
       compile-mvb-body
         (when (null body-tail)
           (go compile-mvb-body-done))
         (setf last (compile-ast (car body-tail) ctx))
         (setf body-tail (cdr body-tail))
         (go compile-mvb-body)
       compile-mvb-body-done)
      (setf (ctx-env ctx) old-env)
      last)))

(defmethod compile-ast ((node ast-apply) ctx)
  (setf (ctx-tail-position ctx) nil)
  (let* ((func-node  (ast-apply-func node))
         (raw-func-reg (if (typep func-node 'ast-function)
                           (compile-ast func-node ctx)
                           (if (and (typep func-node 'ast-quote)
                                    (symbolp (ast-quote-value func-node)))
                               (%resolve-func-sym-reg (ast-quote-value func-node) ctx)
                               (if (symbolp func-node)
                                   (%resolve-func-sym-reg func-node ctx)
                                   (compile-ast func-node ctx)))))
         (func-reg   (make-register ctx))
         (result-reg (make-register ctx))
         (args       (ast-apply-args node))
         (spread-arg nil)
         (leading-args nil)
         (spread-val nil))
    (let ((tail args)
          (leading-rev nil))
      (tagbody
       split-apply-args
         (when (null tail)
           (go split-apply-done))
         (if (cdr tail)
             (progn
               (setf leading-rev (cons (car tail) leading-rev))
               (setf tail (cdr tail))
               (go split-apply-args))
             (progn
               (setf spread-arg (car tail))
               (setf tail nil)
               (go split-apply-done)))
       split-apply-done)
      (let ((reverse-tail leading-rev))
        (tagbody
         reverse-leading-args
           (when (null reverse-tail)
             (go reverse-leading-done))
           (setf leading-args (cons (car reverse-tail) leading-args))
           (setf reverse-tail (cdr reverse-tail))
           (go reverse-leading-args)
         reverse-leading-done)))
    (when (and spread-arg (typep spread-arg 'ast-quote))
      (setf spread-val (ast-quote-value spread-arg)))
    (emit ctx (make-vm-move :dst func-reg :src raw-func-reg))
    (if (and spread-val (or (null spread-val) (listp spread-val)))
        (let ((leading-regs nil)
              (spread-regs nil)
              (call-args nil))
          (let ((tail leading-args)
                (regs-rev nil))
            (tagbody
             compile-leading-args
               (when (null tail)
                 (go compile-leading-done))
               (setf regs-rev (cons (compile-ast (car tail) ctx) regs-rev))
               (setf tail (cdr tail))
               (go compile-leading-args)
             compile-leading-done)
            (let ((reverse-tail regs-rev))
              (tagbody
               reverse-leading-regs
                 (when (null reverse-tail)
                   (go reverse-leading-regs-done))
                 (setf leading-regs (cons (car reverse-tail) leading-regs))
                 (setf reverse-tail (cdr reverse-tail))
                 (go reverse-leading-regs)
               reverse-leading-regs-done)))
          (let ((tail spread-val)
                (regs-rev nil))
            (tagbody
             compile-spread-values
               (when (null tail)
                 (go compile-spread-done))
               (setf regs-rev (cons (compile-ast (make-ast-quote :value (car tail)) ctx)
                                     regs-rev))
               (setf tail (cdr tail))
               (go compile-spread-values)
             compile-spread-done)
            (let ((reverse-tail regs-rev))
              (tagbody
               reverse-spread-regs
                 (when (null reverse-tail)
                   (go reverse-spread-regs-done))
                 (setf spread-regs (cons (car reverse-tail) spread-regs))
                 (setf reverse-tail (cdr reverse-tail))
                 (go reverse-spread-regs)
               reverse-spread-regs-done)))
          (setf call-args spread-regs)
          (let ((tail leading-regs)
                (leading-rev nil))
            (tagbody
             reverse-leading-for-prepend
               (when (null tail)
                 (go reverse-leading-for-prepend-done))
               (setf leading-rev (cons (car tail) leading-rev))
               (setf tail (cdr tail))
               (go reverse-leading-for-prepend)
             reverse-leading-for-prepend-done)
            (let ((prepend-tail leading-rev))
              (tagbody
               prepend-leading-to-spread
                 (when (null prepend-tail)
                   (go prepend-leading-to-spread-done))
                 (setf call-args (cons (car prepend-tail) call-args))
                 (setf prepend-tail (cdr prepend-tail))
                 (go prepend-leading-to-spread)
               prepend-leading-to-spread-done)))
          (emit ctx (make-vm-call :dst result-reg :func func-reg
                                  :args call-args)))
        (let ((arg-regs nil)
              (tail args)
              (regs-rev nil))
          (tagbody
           compile-apply-args
             (when (null tail)
               (go compile-apply-args-done))
             (setf regs-rev (cons (compile-ast (car tail) ctx) regs-rev))
             (setf tail (cdr tail))
             (go compile-apply-args)
           compile-apply-args-done)
          (let ((reverse-tail regs-rev))
            (tagbody
             reverse-apply-regs
               (when (null reverse-tail)
                 (go reverse-apply-regs-done))
               (setf arg-regs (cons (car reverse-tail) arg-regs))
               (setf reverse-tail (cdr reverse-tail))
               (go reverse-apply-regs)
             reverse-apply-regs-done))
          (emit ctx (make-vm-apply :dst result-reg :func func-reg :args arg-regs))))
    result-reg))

(defmethod compile-ast ((node ast-multiple-value-call) ctx)
  "Evaluate FUNC, collect ALL values from each arg form, apply FUNC to them."
  (setf (ctx-tail-position ctx) nil)
  (let* ((raw-func-reg (compile-ast (ast-mv-call-func node) ctx))
         (func-reg (make-register ctx))
         (args (ast-mv-call-args node))
         (result-reg (make-register ctx)))
    (emit ctx (make-vm-move :dst func-reg :src raw-func-reg))
    (if (null args)
        (emit ctx (make-vm-call :dst result-reg :func func-reg :args nil))
        (let ((all-values-p t)
              (scan-tail args))
          (tagbody
           check-value-args
             (when (null scan-tail)
               (go check-value-args-done))
             (unless (typep (car scan-tail) 'ast-values)
               (setf all-values-p nil)
               (go check-value-args-done))
             (setf scan-tail (cdr scan-tail))
             (go check-value-args)
           check-value-args-done)
          (if all-values-p
              (let ((flat-arg-regs nil)
                    (regs-rev nil)
                    (arg-tail args))
                (tagbody
                 compile-flat-value-args
                   (when (null arg-tail)
                     (go compile-flat-value-args-done))
                   (let ((form-tail (ast-values-forms (car arg-tail))))
                     (tagbody
                      compile-flat-value-forms
                        (when (null form-tail)
                          (go compile-flat-value-forms-done))
                        (setf regs-rev (cons (compile-ast (car form-tail) ctx)
                                             regs-rev))
                        (setf form-tail (cdr form-tail))
                        (go compile-flat-value-forms)
                      compile-flat-value-forms-done))
                   (setf arg-tail (cdr arg-tail))
                   (go compile-flat-value-args)
                 compile-flat-value-args-done)
                (let ((tail regs-rev))
                  (tagbody
                   reverse-flat-value-regs
                     (when (null tail)
                       (go reverse-flat-value-regs-done))
                     (setf flat-arg-regs (cons (car tail) flat-arg-regs))
                     (setf tail (cdr tail))
                     (go reverse-flat-value-regs)
                   reverse-flat-value-regs-done))
                (emit ctx (make-vm-call :dst result-reg :func func-reg :args flat-arg-regs)))
              (let ((list-regs nil)
                    (regs-rev nil)
                    (arg-tail args))
                (tagbody
                 compile-value-list-args
                   (when (null arg-tail)
                     (go compile-value-list-args-done))
                   (emit ctx (make-vm-clear-values))
                   (let ((primary-reg (compile-ast (car arg-tail) ctx))
                         (lr (make-register ctx)))
                     (emit ctx (make-vm-ensure-values :src primary-reg))
                     (emit ctx (make-vm-values-to-list :dst lr))
                     (setf regs-rev (cons lr regs-rev)))
                   (setf arg-tail (cdr arg-tail))
                   (go compile-value-list-args)
                 compile-value-list-args-done)
                (let ((tail regs-rev))
                  (tagbody
                   reverse-value-list-regs
                     (when (null tail)
                       (go reverse-value-list-regs-done))
                     (setf list-regs (cons (car tail) list-regs))
                     (setf tail (cdr tail))
                     (go reverse-value-list-regs)
                   reverse-value-list-regs-done))
                (let ((combined-reg (car list-regs))
                      (tail (cdr list-regs)))
                  (tagbody
                   append-value-lists
                     (when (null tail)
                       (go append-value-lists-done))
                     (let ((new-reg (make-register ctx)))
                       (emit ctx (make-vm-append :dst new-reg :src1 combined-reg :src2 (car tail)))
                       (setf combined-reg new-reg))
                     (setf tail (cdr tail))
                     (go append-value-lists)
                   append-value-lists-done)
                  (emit ctx (make-vm-apply :dst result-reg :func func-reg
                                           :args (cons combined-reg nil))))))))
    result-reg))

(defmethod compile-ast ((node ast-multiple-value-prog1) ctx)
  "Save result of first form, evaluate remaining forms, return saved result."
  (setf (ctx-tail-position ctx) nil)
  (let ((first-reg (compile-ast (ast-mv-prog1-first node) ctx))
        (result-reg (make-register ctx)))
    (emit ctx (make-vm-move :dst result-reg :src first-reg))
    (dolist (form (ast-mv-prog1-forms node))
      (compile-ast form ctx))
    result-reg))
