(defpackage :cl-cc/php
  (:use :cl :cl-cc/ast :cl-cc/bootstrap :cl-cc/parse)
  (:export
    #:tokenize-php-source
     #:parse-php-source
     #:parse-php-source-to-cst
     #:php-attribute
     #:make-php-attribute
     #:php-attribute-name
     #:php-attribute-args
     #:php-attribute-target-type
     #:%php-parse-attributes
     #:%php-parse-attribute-group
     #:%php-parse-attribute
     #:%php-skip-attributes
     #:+php-null+
    #:%php-array
    #:%php-array-empty-p
     #:%php-array-ref
     #:%php-array-set
     #:%php-array-unset
     #:%php-eq-loose
    #:%php-eq-strict
    #:%php-null-p
    #:%php-to-number
    #:%php-truthy
    #:%php-value-type
    #:%php-count
    #:%php-strlen
    #:%php-strtolower
   #:%php-strtoupper
    #:%php-stringify
    #:%php-concat
    #:%php-modulo
    #:%php-shift-left
    #:%php-shift-right
    #:%php-spaceship
    #:%php-bitwise-and
    #:%php-bitwise-or
    #:%php-bitwise-xor
    #:%php-bitwise-not
    #:%php-isset
    #:%php-array-key-exists
     #:%php-yield
     #:%php-yield-from
      #:%php-throw
       #:%php-make-exception
       #:%php-exception-object-p
       #:%php-exception-value
       #:%php-exception-matches-p
       #:%php-enum-make-case
       #:%php-enum-cases
       #:%php-enum-case-list
       #:%php-enum-from
       #:%php-enum-try-from
       #:%php-enum-case-value
       #:php-exception
    #:*php-builtin-map*
   #:php-check-supported-forms
   #:*php-trait-registry*
   #:%php-parse-trait-decl
   #:%php-parse-use-trait-stmt
   #:*php-interface-registry*
   #:%php-parse-interface-decl
   #:%php-fiber-make
   #:%php-fiber-start
   #:%php-fiber-resume
   #:%php-fiber-suspend
   #:%php-array-find
   #:%php-array-find-key
   #:%php-array-any
   #:%php-array-all
   #:%php-callable-ref
   ;; Reference / by-ref semantics
   #:php-ref-p
   #:%php-ref-p
   #:%php-make-ref
   #:%php-deref
   #:%php-ref-set!
   #:*php-by-ref-param-registry*
   ;; foreach by-reference
   #:%php-foreach-by-ref
   ;; Generator (yield/yield-from/send)
   #:php-generator-p
   #:%php-generator-p
   #:%php-make-generator
   #:%php-generator-next
   #:%php-generator-send
   #:%php-generator-valid
   #:%php-generator-current
   #:%php-generator-get-return
   #:*current-generator*))
