;;;; Central PHP builtin registry.

(in-package :cl-cc/php)

(defparameter *php-builtin-registry* (make-hash-table :test #'equal)
  "Map lowercase PHP builtin names to Common Lisp helper functions.")

(defparameter *php-builtin-symbol-registry* (make-hash-table :test #'equal)
  "Map lowercase PHP builtin names to helper symbols for parser lowering.")

(defparameter *php-builtin-registration-order* nil
  "Builtin names in registration order, used to rebuild `*php-builtin-map*`.")

(defun %php-normalize-builtin-name (name)
  "Normalize PHP builtin NAME for case-insensitive lookup."
  (string-downcase (string name)))

(defun %php-register-builtin (name function)
  "Register PHP builtin NAME to FUNCTION and return FUNCTION."
  ;; FUNCTION may be a function object or a function designator symbol. The
  ;; public registry stores the resolved helper function, while a side registry
  ;; keeps the symbol for parser integrations that lower calls to helper vars.
  ;; (%php-register-builtin "strlen" '%php-strlen) => #<FUNCTION %PHP-STRLEN>
  (let* ((key (%php-normalize-builtin-name name))
         (symbol (and (symbolp function) function))
         (fn (if symbol (symbol-function symbol) function)))
    (unless (gethash key *php-builtin-registry*)
      (setf *php-builtin-registration-order*
            (append *php-builtin-registration-order* (list key))))
    (setf (gethash key *php-builtin-registry*) fn)
    (when symbol
      (setf (gethash key *php-builtin-symbol-registry*) symbol))
    fn))

(defun %php-lookup-builtin (name)
  "Return the helper function registered for PHP builtin NAME, or NIL."
  ;; (%php-lookup-builtin "STRLEN") => #<FUNCTION %PHP-STRLEN>
  (gethash (%php-normalize-builtin-name name) *php-builtin-registry*))

(defun %php-lookup-builtin-symbol (name)
  "Return the helper symbol registered for PHP builtin NAME, or NIL."
  (gethash (%php-normalize-builtin-name name) *php-builtin-symbol-registry*))

(defun %php-sync-legacy-builtin-map ()
  "Synchronize legacy `*php-builtin-map*` with the central registry."
  (when (boundp '*php-builtin-map*)
    (setf *php-builtin-map*
          (loop for name in *php-builtin-registration-order*
                for fn = (%php-lookup-builtin name)
                when fn collect (cons name fn)))))

(defun %php-register-all-builtins ()
  "Register all supported PHP builtin helpers and return the registry."
  ;; The registry intentionally includes common aliases such as sizeof/count,
  ;; join/implode, and is_integer/is_int.
  ;; (%php-register-all-builtins) => *PHP-BUILTIN-REGISTRY*
  (clrhash *php-builtin-registry*)
  (clrhash *php-builtin-symbol-registry*)
  (setf *php-builtin-registration-order* nil)

  ;; Core.
  (%php-register-builtin "count" '%php-count)
  (%php-register-builtin "sizeof" '%php-count)
  (%php-register-builtin "isset" '%php-isset)
  (%php-register-builtin "empty" '%php-empty)
  (%php-register-builtin "is_null" '%php-is-null)
  (%php-register-builtin "unset" '%php-unset)
  (%php-register-builtin "print_r" '%php-print-r)
  (%php-register-builtin "var_dump" '%php-var-dump)
  (%php-register-builtin "gettype" '%php-gettype)
  (%php-register-builtin "array_key_exists" '%php-array-key-exists)

  ;; String.
  (%php-register-builtin "strlen" '%php-strlen)
  (%php-register-builtin "strtolower" '%php-strtolower)
  (%php-register-builtin "strtoupper" '%php-strtoupper)
  (%php-register-builtin "str_replace" '%php-str-replace)
  (%php-register-builtin "str_ireplace" '%php-str-ireplace)
  (%php-register-builtin "substr" '%php-substr)
  (%php-register-builtin "trim" '%php-trim)
  (%php-register-builtin "ltrim" '%php-ltrim)
  (%php-register-builtin "rtrim" '%php-rtrim)
  (%php-register-builtin "explode" '%php-explode)
  (%php-register-builtin "implode" '%php-implode)
  (%php-register-builtin "join" '%php-join)
  (%php-register-builtin "strpos" '%php-strpos)
  (%php-register-builtin "stripos" '%php-stripos)
  (%php-register-builtin "strrpos" '%php-strrpos)
  (%php-register-builtin "str_contains" '%php-str-contains)
  (%php-register-builtin "str_starts_with" '%php-str-starts-with)
  (%php-register-builtin "str_ends_with" '%php-str-ends-with)
  (%php-register-builtin "strrev" '%php-strrev)
  (%php-register-builtin "str_repeat" '%php-str-repeat)
  (%php-register-builtin "sprintf" '%php-sprintf)
  (%php-register-builtin "htmlspecialchars" '%php-htmlspecialchars)
  (%php-register-builtin "str_pad" '%php-str-pad)
  (%php-register-builtin "str_split" '%php-str-split)
  (%php-register-builtin "substr_count" '%php-substr-count)
  (%php-register-builtin "substr_replace" '%php-substr-replace)
  (%php-register-builtin "ucfirst" '%php-ucfirst)
  (%php-register-builtin "lcfirst" '%php-lcfirst)
  (%php-register-builtin "ucwords" '%php-ucwords)
  (%php-register-builtin "ord" '%php-ord)
  (%php-register-builtin "chr" '%php-chr)
  (%php-register-builtin "bin2hex" '%php-bin2hex)
  (%php-register-builtin "hex2bin" '%php-hex2bin)
  (%php-register-builtin "strcmp" '%php-strcmp)
  (%php-register-builtin "strcasecmp" '%php-strcasecmp)
  (%php-register-builtin "strncmp" '%php-strncmp)
  (%php-register-builtin "strncasecmp" '%php-strncasecmp)
  (%php-register-builtin "strstr" '%php-strstr)
  (%php-register-builtin "stristr" '%php-stristr)
  (%php-register-builtin "strchr" '%php-strchr)
  (%php-register-builtin "str_word_count" '%php-str-word-count)
  (%php-register-builtin "levenshtein" '%php-levenshtein)
  (%php-register-builtin "similar_text" '%php-similar-text)
  (%php-register-builtin "soundex" '%php-soundex)
  (%php-register-builtin "printf" '%php-printf)
  (%php-register-builtin "vsprintf" '%php-vsprintf)
  (%php-register-builtin "vprintf" '%php-vprintf)
  (%php-register-builtin "nl2br" '%php-nl2br)
  (%php-register-builtin "wordwrap" '%php-wordwrap)
  (%php-register-builtin "chunk_split" '%php-chunk-split)
  (%php-register-builtin "html_entity_decode" '%php-html-entity-decode)
  (%php-register-builtin "strip_tags" '%php-strip-tags)
  (%php-register-builtin "addslashes" '%php-addslashes)
  (%php-register-builtin "stripslashes" '%php-stripslashes)
  (%php-register-builtin "base64_encode" '%php-base64-encode)
  (%php-register-builtin "base64_decode" '%php-base64-decode)
  (%php-register-builtin "md5" '%php-md5)
  (%php-register-builtin "sha1" '%php-sha1)
  (%php-register-builtin "crc32" '%php-crc32)
  (%php-register-builtin "urlencode" '%php-urlencode)
  (%php-register-builtin "urldecode" '%php-urldecode)
  (%php-register-builtin "rawurlencode" '%php-rawurlencode)
  (%php-register-builtin "rawurldecode" '%php-rawurldecode)
  (%php-register-builtin "json_encode" '%php-json-encode)
  (%php-register-builtin "json_decode" '%php-json-decode)
  (%php-register-builtin "mb_strlen" '%php-mb-strlen)
  (%php-register-builtin "mb_substr" '%php-mb-substr)
  (%php-register-builtin "mb_strtolower" '%php-mb-strtolower)
  (%php-register-builtin "mb_strtoupper" '%php-mb-strtoupper)
  (%php-register-builtin "mb_strpos" '%php-mb-strpos)
  (%php-register-builtin "mb_strrpos" '%php-mb-strrpos)
  (%php-register-builtin "mb_substr_count" '%php-mb-substr-count)
  (%php-register-builtin "mb_detect_encoding" '%php-mb-detect-encoding)
  (%php-register-builtin "mb_internal_encoding" '%php-mb-internal-encoding)
  (%php-register-builtin "mb_convert_encoding" '%php-mb-convert-encoding)
  (%php-register-builtin "mb_convert_case" '%php-mb-convert-case)
  (%php-register-builtin "mb_str_pad" '%php-mb-str-pad)
  (%php-register-builtin "mb_str_split" '%php-mb-str-split)
  (%php-register-builtin "str_getcsv" '%php-str-getcsv)
  (%php-register-builtin "mb_chr" '%php-mb-chr)
  (%php-register-builtin "mb_ord" '%php-mb-ord)
  (%php-register-builtin "mb_strimwidth" '%php-mb-strimwidth)
  (%php-register-builtin "mb_ereg" '%php-mb-ereg)
  (%php-register-builtin "mb_eregi" '%php-mb-eregi)
  (%php-register-builtin "mb_ereg_replace" '%php-mb-ereg-replace)
  (%php-register-builtin "mb_eregi_replace" '%php-mb-eregi-replace)
  (%php-register-builtin "mb_split" '%php-mb-split)
  ;; Additional string functions
  (%php-register-builtin "strtr" '%php-strtr)
  (%php-register-builtin "strpbrk" '%php-strpbrk)
  (%php-register-builtin "strspn" '%php-strspn)
  (%php-register-builtin "strcspn" '%php-strcspn)
  (%php-register-builtin "quotemeta" '%php-quotemeta)
  (%php-register-builtin "htmlentities" '%php-htmlentities)
  (%php-register-builtin "metaphone" '%php-metaphone)
  (%php-register-builtin "nl_langinfo" '%php-nl-langinfo)
  ;; HTML/encoding
  (%php-register-builtin "htmlspecialchars_decode" '%php-htmlspecialchars-decode)
  (%php-register-builtin "html_entity_decode" '%php-html-entity-decode)
  (%php-register-builtin "quoted_printable_encode" '%php-quoted-printable-encode)
  (%php-register-builtin "quoted_printable_decode" '%php-quoted-printable-decode)
  ;; JSON
  (%php-register-builtin "json_validate" '%php-json-validate)
  ;; ctype_* character classification
  (%php-register-builtin "ctype_alpha" '%php-ctype-alpha)
  (%php-register-builtin "ctype_digit" '%php-ctype-digit)
  (%php-register-builtin "ctype_alnum" '%php-ctype-alnum)
  (%php-register-builtin "ctype_space" '%php-ctype-space)
  (%php-register-builtin "ctype_upper" '%php-ctype-upper)
  (%php-register-builtin "ctype_lower" '%php-ctype-lower)
  (%php-register-builtin "ctype_punct" '%php-ctype-punct)
  (%php-register-builtin "ctype_graph" '%php-ctype-graph)
  (%php-register-builtin "ctype_print" '%php-ctype-print)
  (%php-register-builtin "ctype_xdigit" '%php-ctype-xdigit)
  ;; Type checks
  (%php-register-builtin "is_countable" '%php-is-countable)

  ;; Array.
  (%php-register-builtin "array_merge" '%php-array-merge)
  (%php-register-builtin "array_keys" '%php-array-keys)
  (%php-register-builtin "array_values" '%php-array-values)
  (%php-register-builtin "array_push" '%php-array-push)
  (%php-register-builtin "array_pop" '%php-array-pop)
  (%php-register-builtin "array_shift" '%php-array-shift)
  (%php-register-builtin "array_unshift" '%php-array-unshift)
  (%php-register-builtin "in_array" '%php-in-array)
  (%php-register-builtin "array_search" '%php-array-search)
  (%php-register-builtin "array_reverse" '%php-array-reverse)
  (%php-register-builtin "array_slice" '%php-array-slice)
  (%php-register-builtin "array_unique" '%php-array-unique)
  (%php-register-builtin "array_map" '%php-array-map)
  (%php-register-builtin "array_filter" '%php-array-filter)
  (%php-register-builtin "array_reduce" '%php-array-reduce)
  (%php-register-builtin "sort" '%php-sort)
  (%php-register-builtin "rsort" '%php-rsort)
  (%php-register-builtin "asort" '%php-asort)
  (%php-register-builtin "ksort" '%php-ksort)
  (%php-register-builtin "range" '%php-range)
  (%php-register-builtin "usort" '%php-usort)
  (%php-register-builtin "uasort" '%php-uasort)
  (%php-register-builtin "uksort" '%php-uksort)
  (%php-register-builtin "array_walk" '%php-array-walk)
  (%php-register-builtin "array_chunk" '%php-array-chunk)
  (%php-register-builtin "array_pad" '%php-array-pad)
  (%php-register-builtin "array_count_values" '%php-array-count-values)
  (%php-register-builtin "array_sum" '%php-array-sum)
  (%php-register-builtin "array_product" '%php-array-product)
  (%php-register-builtin "array_diff" '%php-array-diff)
  (%php-register-builtin "array_intersect" '%php-array-intersect)
  (%php-register-builtin "array_pop" '%php-array-pop)
  (%php-register-builtin "array_shift" '%php-array-shift)
  (%php-register-builtin "array_push" '%php-array-push)
  (%php-register-builtin "array_unshift" '%php-array-unshift)
  (%php-register-builtin "array_column" '%php-array-column)
  (%php-register-builtin "array_combine" '%php-array-combine)
  (%php-register-builtin "array_flip" '%php-array-flip)
  (%php-register-builtin "array_fill" '%php-array-fill)
  (%php-register-builtin "array_fill_keys" '%php-array-fill-keys)
  (%php-register-builtin "array_splice" '%php-array-splice)
  (%php-register-builtin "array_replace" '%php-array-replace)
  (%php-register-builtin "krsort" '%php-krsort)
  (%php-register-builtin "arsort" '%php-arsort)
  (%php-register-builtin "array_diff_key" '%php-array-diff-key)
  (%php-register-builtin "array_intersect_key" '%php-array-intersect-key)
  (%php-register-builtin "array_diff_assoc" '%php-array-diff-assoc)
  (%php-register-builtin "array_intersect_assoc" '%php-array-intersect-assoc)
  (%php-register-builtin "array_merge_recursive" '%php-array-merge-recursive)
  (%php-register-builtin "shuffle" '%php-shuffle)
  (%php-register-builtin "array_key_first" '%php-array-key-first)
  (%php-register-builtin "array_key_last" '%php-array-key-last)
  (%php-register-builtin "compact" '%php-compact)
  (%php-register-builtin "array_walk_recursive" '%php-array-walk-recursive)
  (%php-register-builtin "natsort" '%php-natsort)
  (%php-register-builtin "natcasesort" '%php-natcasesort)

  ;; Array sorts and extras.
  (%php-register-builtin "array_multisort" '%php-array-multisort)
  ;; list() — returns array for destructuring
  (%php-register-builtin "list" '%php-list-assign)

  ;; PHP 8.4 array functions.
  (%php-register-builtin "array_find"     '%php-array-find)
  (%php-register-builtin "array_find_key" '%php-array-find-key)
  (%php-register-builtin "array_any"      '%php-array-any)
  (%php-register-builtin "array_all"      '%php-array-all)

  ;; PHP 8.1 Fiber builtins are registered in php84-features.lisp (loaded later)
  ;; after those functions are defined.

  ;; PHP Exception / Throwable helpers.
  (%php-register-builtin "set_exception_handler" '%php-set-exception-handler)
  (%php-register-builtin "class_implements" (lambda (class-name &optional autoload)
                                               (declare (ignore autoload class-name))
                                               (%php-make-array)))
  (%php-register-builtin "class_parents" (lambda (class-name &optional autoload)
                                           (declare (ignore autoload class-name))
                                           (%php-make-array)))
  (%php-register-builtin "class_uses" (lambda (class-name &optional autoload)
                                        (declare (ignore autoload class-name))
                                        (%php-make-array)))
  (%php-register-builtin "spl_autoload_register" (lambda (fn &optional throw prepend)
                                                    (declare (ignore fn throw prepend))
                                                    t))
  (%php-register-builtin "spl_autoload_unregister" (lambda (fn)
                                                      (declare (ignore fn))
                                                      t))
  (%php-register-builtin "spl_autoload_functions" (lambda () (%php-make-array)))

  ;; extract() — import array keys as variables (returns count; we can't mutate the calling scope)
  (%php-register-builtin "extract" (lambda (array &optional flags prefix)
                                     (declare (ignore flags prefix))
                                     (if (hash-table-p array) (%php-count array) 0)))

  ;; SPL data structures (stubs returning empty arrays).
  (%php-register-builtin "SplStack"    (lambda () (%php-make-array)))
  (%php-register-builtin "SplQueue"    (lambda () (%php-make-array)))
  (%php-register-builtin "SplDoublyLinkedList" (lambda () (%php-make-array)))
  (%php-register-builtin "SplMinHeap" (lambda () (%php-make-array)))
  (%php-register-builtin "SplMaxHeap" (lambda () (%php-make-array)))
  (%php-register-builtin "SplFixedArray" (lambda (&optional size)
                                           (%php-array-fill 0 (or size 0) +php-null+)))

  ;; Math.
  (%php-register-builtin "abs" '%php-abs)
  (%php-register-builtin "ceil" '%php-ceil)
  (%php-register-builtin "floor" '%php-floor)
  (%php-register-builtin "round" '%php-round)
  (%php-register-builtin "max" '%php-max)
  (%php-register-builtin "min" '%php-min)
  (%php-register-builtin "rand" '%php-rand)
  (%php-register-builtin "mt_rand" '%php-mt-rand)
  (%php-register-builtin "sqrt" '%php-sqrt)
  (%php-register-builtin "pow" '%php-pow)
  (%php-register-builtin "pi" '%php-pi)
  (%php-register-builtin "sin" (lambda (x) (sin (coerce x 'double-float))))
  (%php-register-builtin "cos" (lambda (x) (cos (coerce x 'double-float))))
  (%php-register-builtin "tan" (lambda (x) (tan (coerce x 'double-float))))
  (%php-register-builtin "log" (lambda (x &optional (base nil))
                                 (if base (/ (log (coerce x 'double-float)) (log (coerce base 'double-float)))
                                     (log (coerce x 'double-float)))))
  (%php-register-builtin "exp" (lambda (x) (exp (coerce x 'double-float))))
  (%php-register-builtin "fmod" (lambda (x y) (mod (coerce x 'double-float) (coerce y 'double-float))))
  (%php-register-builtin "intdiv" (lambda (x y) (truncate x y)))
  (%php-register-builtin "number_format" '%php-number-format)
  (%php-register-builtin "base_convert" (lambda (num from-base to-base)
                                          (format nil "~vR" to-base (parse-integer (%php-stringify num) :radix from-base :junk-allowed t))))
  (%php-register-builtin "asin"  (lambda (x) (asin  (coerce x 'double-float))))
  (%php-register-builtin "acos"  (lambda (x) (acos  (coerce x 'double-float))))
  (%php-register-builtin "atan"  (lambda (x) (atan  (coerce x 'double-float))))
  (%php-register-builtin "atan2" (lambda (y x) (atan (coerce y 'double-float) (coerce x 'double-float))))
  (%php-register-builtin "sinh"  (lambda (x) (sinh  (coerce x 'double-float))))
  (%php-register-builtin "cosh"  (lambda (x) (cosh  (coerce x 'double-float))))
  (%php-register-builtin "tanh"  (lambda (x) (tanh  (coerce x 'double-float))))
  (%php-register-builtin "log10" (lambda (x) (log   (coerce x 'double-float) 10d0)))
  (%php-register-builtin "log2"  (lambda (x) (log   (coerce x 'double-float)  2d0)))
  (%php-register-builtin "hypot" (lambda (x y) (sqrt (+ (* x x) (* y y)))))
  (%php-register-builtin "deg2rad" (lambda (x) (* (coerce x 'double-float) (/ pi 180))))
  (%php-register-builtin "rad2deg" (lambda (x) (* (coerce x 'double-float) (/ 180 pi))))
  (%php-register-builtin "decbin"  (lambda (n) (format nil "~b" n)))
  (%php-register-builtin "decoct"  (lambda (n) (format nil "~o" n)))
  (%php-register-builtin "dechex"  (lambda (n) (format nil "~x" n)))
  (%php-register-builtin "bindec"  (lambda (s) (parse-integer (%php-stringify s) :radix 2 :junk-allowed t)))
  (%php-register-builtin "octdec"  (lambda (s) (parse-integer (%php-stringify s) :radix 8 :junk-allowed t)))
  (%php-register-builtin "hexdec"  (lambda (s) (parse-integer (%php-stringify s) :radix 16 :junk-allowed t)))
  (%php-register-builtin "is_nan"      (lambda (x) (and (floatp x) (not (= x x)))))
  (%php-register-builtin "is_finite"   (lambda (x) (and (floatp x) (< (abs x) #.most-positive-double-float) (= x x))))
  (%php-register-builtin "is_infinite" (lambda (x) (and (floatp x) (= x x) (>= (abs x) #.most-positive-double-float))))
  (%php-register-builtin "fdiv" (lambda (x y)
                                  (if (zerop y)
                                      (cond ((zerop x) 0.0d0)
                                            ((plusp x) #.most-positive-double-float)
                                            (t #.most-negative-double-float))
                                      (/ (coerce x 'double-float) (coerce y 'double-float)))))
  (%php-register-builtin "lcg_value" (lambda () (random 1.0d0)))
  (%php-register-builtin "mt_srand"  (lambda (&optional seed) (when seed (setf *random-state* (make-random-state t)))))
  (%php-register-builtin "srand"     (lambda (&optional seed) (when seed (setf *random-state* (make-random-state t)))))

  ;; Regex
  (%php-register-builtin "preg_match" '%php-preg-match)
  (%php-register-builtin "preg_match_all" '%php-preg-match-all)
  (%php-register-builtin "preg_replace" '%php-preg-replace)
  (%php-register-builtin "preg_split" '%php-preg-split)
  (%php-register-builtin "preg_quote" '%php-preg-quote)
  (%php-register-builtin "preg_replace_callback" '%php-preg-replace-callback)
  (%php-register-builtin "preg_replace_callback_array" '%php-preg-replace-callback-array)

  ;; Date/Time
  (%php-register-builtin "time" '%php-time)
  (%php-register-builtin "microtime" '%php-microtime)
  (%php-register-builtin "mktime" '%php-mktime)
  (%php-register-builtin "strtotime" '%php-strtotime)
  (%php-register-builtin "date" '%php-date)
  (%php-register-builtin "checkdate" '%php-checkdate)
  (%php-register-builtin "gmdate" '%php-gmdate)
  (%php-register-builtin "date_create" '%php-date-create)
  (%php-register-builtin "date_format" '%php-date-format)
  (%php-register-builtin "date_modify" '%php-date-modify)
  (%php-register-builtin "date_diff" '%php-date-diff)
  (%php-register-builtin "date_timestamp_get" '%php-date-timestamp)
  (%php-register-builtin "date_default_timezone_set" '%php-date-default-timezone-set)
  (%php-register-builtin "date_default_timezone_get" '%php-date-default-timezone-get)

  ;; Types and conversions.
  (%php-register-builtin "is_int" '%php-is-int)
  (%php-register-builtin "is_integer" '%php-is-integer)
  (%php-register-builtin "is_long" '%php-is-long)
  (%php-register-builtin "is_float" '%php-is-float)
  (%php-register-builtin "is_double" '%php-is-double)
  (%php-register-builtin "is_real" '%php-is-real)
  (%php-register-builtin "is_string" '%php-is-string)
  (%php-register-builtin "is_bool" '%php-is-bool)
  (%php-register-builtin "is_array" '%php-is-array)
  (%php-register-builtin "is_object" '%php-is-object)
  (%php-register-builtin "is_callable" '%php-is-callable)
  (%php-register-builtin "is_numeric" '%php-is-numeric)
  (%php-register-builtin "is_scalar" '%php-is-scalar)
  (%php-register-builtin "is_iterable" '%php-is-iterable)
  (%php-register-builtin "intval" '%php-intval)
  (%php-register-builtin "floatval" '%php-floatval)
  (%php-register-builtin "strval" '%php-strval)
  (%php-register-builtin "boolval" '%php-boolval)
  (%php-register-builtin "settype" (lambda (v _type) (declare (ignore _type)) v))
  (%php-register-builtin "get_debug_type" '%php-gettype)
  (%php-register-builtin "array_is_list" (lambda (a) (when (hash-table-p a)
                                                         (loop for i from 0 for k in (%php-array-ordered-keys a)
                                                               always (eql k i)))))

  ;; File I/O.
  (%php-register-builtin "file_get_contents" '%php-file-get-contents)
  (%php-register-builtin "file_put_contents" '%php-file-put-contents)
  (%php-register-builtin "file" '%php-file)
  (%php-register-builtin "readfile" '%php-readfile)
  (%php-register-builtin "file_exists" '%php-file-exists)
  (%php-register-builtin "is_file" '%php-is-file)
  (%php-register-builtin "is_dir" '%php-is-dir)
  (%php-register-builtin "is_readable" '%php-is-readable)
  (%php-register-builtin "is_writable" '%php-is-writable)
  (%php-register-builtin "is_writeable" '%php-is-writeable)
  (%php-register-builtin "is_executable" '%php-is-executable)
  (%php-register-builtin "is_link" '%php-is-link)
  (%php-register-builtin "filesize" '%php-filesize)
  (%php-register-builtin "filemtime" '%php-filemtime)
  (%php-register-builtin "filetype" '%php-filetype)
  (%php-register-builtin "unlink" '%php-unlink)
  (%php-register-builtin "rename" '%php-rename)
  (%php-register-builtin "copy" '%php-copy)
  (%php-register-builtin "mkdir" '%php-mkdir)
  (%php-register-builtin "rmdir" '%php-rmdir)
  (%php-register-builtin "scandir" '%php-scandir)
  (%php-register-builtin "getcwd" '%php-getcwd)
  (%php-register-builtin "chdir" '%php-chdir)
  (%php-register-builtin "realpath" '%php-realpath)
  (%php-register-builtin "basename" '%php-basename)
  (%php-register-builtin "dirname" '%php-dirname)
  (%php-register-builtin "pathinfo" '%php-pathinfo)
  (%php-register-builtin "tempnam" '%php-tempnam)
  (%php-register-builtin "sys_get_temp_dir" '%php-sys-get-temp-dir)
  (%php-register-builtin "fopen" '%php-fopen)
  (%php-register-builtin "fclose" '%php-fclose)
  (%php-register-builtin "fread" '%php-fread)
  (%php-register-builtin "fwrite" '%php-fwrite)
  (%php-register-builtin "fputs" '%php-fputs)
  (%php-register-builtin "fgets" '%php-fgets)
  (%php-register-builtin "fgetc" '%php-fgetc)
  (%php-register-builtin "feof" '%php-feof)
  (%php-register-builtin "fflush" '%php-fflush)
  (%php-register-builtin "fseek" '%php-fseek)
  (%php-register-builtin "ftell" '%php-ftell)
  (%php-register-builtin "rewind" '%php-rewind)
  (%php-register-builtin "fgetcsv" '%php-fgetcsv)
  (%php-register-builtin "fputcsv" '%php-fputcsv)

  ;; System / environment.
  (%php-register-builtin "getenv" '%php-getenv)
  (%php-register-builtin "putenv" '%php-putenv)
  (%php-register-builtin "php_uname" '%php-php-uname)
  (%php-register-builtin "php_sapi_name" '%php-php-sapi-name)
  (%php-register-builtin "phpversion" '%php-php-version)
  (%php-register-builtin "ini_get" '%php-ini-get)
  (%php-register-builtin "ini_set" '%php-ini-set)
  (%php-register-builtin "set_error_handler" '%php-set-error-handler)
  (%php-register-builtin "set_exception_handler" '%php-set-exception-handler)
  (%php-register-builtin "error_reporting" '%php-error-reporting)
  (%php-register-builtin "trigger_error" '%php-trigger-error)
  (%php-register-builtin "user_error" '%php-trigger-error)
  (%php-register-builtin "exit" '%php-exit)
  (%php-register-builtin "die" '%php-die)
  (%php-register-builtin "sleep" '%php-sleep)
  (%php-register-builtin "usleep" '%php-usleep)
  (%php-register-builtin "ob_start" '%php-ob-start)
  (%php-register-builtin "ob_end_clean" '%php-ob-end-clean)
  (%php-register-builtin "ob_get_clean" '%php-ob-get-clean)
  (%php-register-builtin "ob_get_contents" '%php-ob-get-contents)
  (%php-register-builtin "header" '%php-header)
  (%php-register-builtin "http_response_code" '%php-http-response-code)

  ;; String misc.
  (%php-register-builtin "parse_str" '%php-parse-str)
  (%php-register-builtin "http_build_query" '%php-http-build-query)

  ;; Generators / iterators.
  (%php-register-builtin "iterator_to_array" (lambda (iter &optional (preserve-keys t))
                                               (if (php-generator-p iter)
                                                   (let ((result (%php-make-array)))
                                                     (loop for i from 0
                                                           while (%php-generator-valid iter)
                                                           do (if (%php-truthy preserve-keys)
                                                                  (%php-array-set result i (%php-generator-next iter))
                                                                  (%php-array-set result (%php-array-next-auto-index result) (%php-generator-next iter))))
                                                     result)
                                                   iter)))
  (%php-register-builtin "iterator_count" (lambda (iter)
                                            (if (php-generator-p iter)
                                                (length (php-gen-values iter))
                                                (%php-count iter))))

  ;; Class / OOP introspection.
  (%php-register-builtin "class_exists" '%php-class-exists)
  (%php-register-builtin "interface_exists" '%php-interface-exists)
  (%php-register-builtin "function_exists" '%php-function-exists)
  (%php-register-builtin "method_exists" '%php-method-exists)
  (%php-register-builtin "property_exists" '%php-property-exists)
  (%php-register-builtin "get_class" '%php-get-class)
  (%php-register-builtin "get_parent_class" '%php-get-parent-class)
  (%php-register-builtin "is_a" '%php-is-a)
  (%php-register-builtin "instanceof" '%php-instanceof)
  (%php-register-builtin "get_object_vars" '%php-get-object-vars)
  (%php-register-builtin "get_class_methods" '%php-get-class-methods)

  ;; Array extras.
  (%php-register-builtin "each" '%php-each)
  (%php-register-builtin "reset" '%php-reset)
  (%php-register-builtin "end" '%php-end)
  (%php-register-builtin "current" '%php-current)
  (%php-register-builtin "next" '%php-next)
  (%php-register-builtin "prev" '%php-prev)
  (%php-register-builtin "key" '%php-key)

  ;; Output / misc.
  (%php-register-builtin "echo" (lambda (&rest args) (dolist (a args) (write-string (%php-stringify a))) nil))
  (%php-register-builtin "print" (lambda (arg) (write-string (%php-stringify arg)) 1))
  (%php-register-builtin "var_export" (lambda (v &optional return-p)
                                        (let ((s (%php-print-r v)))
                                          (if (%php-truthy return-p) s (write-string s)))))
  (%php-register-builtin "serialize" (lambda (v) (format nil "s:~D:\"~A\"" (length (%php-stringify v)) (%php-stringify v))))
  (%php-register-builtin "unserialize" (lambda (s) (%php-stringify s)))

  ;; Misc. globals / constants
  (%php-register-builtin "PHP_EOL" (lambda () (string #\Newline)))
  (%php-register-builtin "PHP_OS" (lambda () "Linux"))
  (%php-register-builtin "PHP_OS_FAMILY" (lambda () "Linux"))
  (%php-register-builtin "PHP_MAJOR_VERSION" (lambda () 8))
  (%php-register-builtin "PHP_MINOR_VERSION" (lambda () 4))
  (%php-register-builtin "PHP_RELEASE_VERSION" (lambda () 0))
  (%php-register-builtin "PHP_VERSION" (lambda () "8.4.0"))
  (%php-register-builtin "PHP_MAXPATHLEN" (lambda () 4096))
  (%php-register-builtin "M_PI" (lambda () pi))
  (%php-register-builtin "M_E"  (lambda () (exp 1.0d0)))
  (%php-register-builtin "M_LN2" (lambda () (log 2.0d0)))
  (%php-register-builtin "M_LN10" (lambda () (log 10.0d0)))
  (%php-register-builtin "M_LOG2E" (lambda () (log (exp 1.0d0) 2.0d0)))
  (%php-register-builtin "M_SQRT2" (lambda () (sqrt 2.0d0)))
  (%php-register-builtin "STDIN" (lambda () nil))
  (%php-register-builtin "STDOUT" (lambda () nil))
  (%php-register-builtin "STDERR" (lambda () nil))
  (%php-register-builtin "E_ALL" (lambda () 32767))
  (%php-register-builtin "E_WARNING" (lambda () 2))
  (%php-register-builtin "E_NOTICE" (lambda () 8))
  (%php-register-builtin "E_ERROR" (lambda () 1))
  (%php-register-builtin "SORT_REGULAR" (lambda () 0))
  (%php-register-builtin "SORT_NUMERIC" (lambda () 1))
  (%php-register-builtin "SORT_STRING" (lambda () 2))
  (%php-register-builtin "SORT_ASC" (lambda () 4))
  (%php-register-builtin "SORT_DESC" (lambda () 3))
  (%php-register-builtin "ARRAY_FILTER_USE_BOTH" (lambda () 1))
  (%php-register-builtin "ARRAY_FILTER_USE_KEY" (lambda () 2))
  (%php-register-builtin "STR_PAD_RIGHT" (lambda () 1))
  (%php-register-builtin "STR_PAD_LEFT" (lambda () 0))
  (%php-register-builtin "STR_PAD_BOTH" (lambda () 2))
  (%php-register-builtin "ENT_QUOTES" (lambda () 3))
  (%php-register-builtin "ENT_HTML5" (lambda () 48))
  (%php-register-builtin "JSON_PRETTY_PRINT" (lambda () 128))
  (%php-register-builtin "JSON_UNESCAPED_UNICODE" (lambda () 256))
  (%php-register-builtin "JSON_UNESCAPED_SLASHES" (lambda () 64))
  (%php-register-builtin "JSON_THROW_ON_ERROR" (lambda () 4194304))
  (%php-register-builtin "FILE_APPEND" (lambda () 8))
  (%php-register-builtin "LOCK_EX" (lambda () 2))
  (%php-register-builtin "SEEK_SET" (lambda () 0))
  (%php-register-builtin "SEEK_CUR" (lambda () 1))
  (%php-register-builtin "SEEK_END" (lambda () 2))
  (%php-register-builtin "T_STRING" (lambda () 319))
  (%php-register-builtin "true" (lambda () t))
  (%php-register-builtin "false" (lambda () nil))
  (%php-register-builtin "null" (lambda () +php-null+))
  (%php-register-builtin "INF" (lambda () #.most-positive-double-float))
  (%php-register-builtin "NAN" (lambda () #.most-positive-double-float))

  ;; Additional type/string utilities
  (%php-register-builtin "chr" '%php-chr)
  (%php-register-builtin "ord" '%php-ord)
  (%php-register-builtin "number_format" '%php-number-format)
  (%php-register-builtin "sprintf" '%php-sprintf)
  (%php-register-builtin "printf" '%php-printf)
  (%php-register-builtin "sscanf" (lambda (str fmt &rest _) (declare (ignore _)) (list (%php-stringify str) (%php-stringify fmt))))
  (%php-register-builtin "scanf" (lambda (fmt &rest _) (declare (ignore fmt _)) (%php-make-array)))

  ;; Additional math
  (%php-register-builtin "max" '%php-max)
  (%php-register-builtin "min" '%php-min)
  (%php-register-builtin "pow" '%php-pow)
  (%php-register-builtin "fmod" (lambda (x y) (mod (coerce x 'double-float) (coerce y 'double-float))))
  (%php-register-builtin "abs" '%php-abs)
  ;; bcmath extension
  (%php-register-builtin "bcadd"  '%php-bcadd)
  (%php-register-builtin "bcsub"  '%php-bcsub)
  (%php-register-builtin "bcmul"  '%php-bcmul)
  (%php-register-builtin "bcdiv"  '%php-bcdiv)
  (%php-register-builtin "bcpow"  '%php-bcpow)
  (%php-register-builtin "bcmod"  '%php-bcmod)
  (%php-register-builtin "bccomp" '%php-bccomp)
  (%php-register-builtin "bcscale" '%php-bcscale)
  (%php-register-builtin "bcsqrt" '%php-bcsqrt)

  (%php-sync-legacy-builtin-map)
  *php-builtin-registry*)

(eval-when (:load-toplevel :execute)
  (export '(*php-builtin-registry*
            %php-register-builtin
            %php-lookup-builtin
            %php-register-all-builtins
            %php-lookup-builtin-symbol
            %php-array-pairs)
          :cl-cc/php)
  (%php-register-all-builtins))
