(in-package :cl-cc)
;;; ─── Pass: Strength Reduction ────────────────────────────────────────────

(defun opt-power-of-2-p (n)
  "T if N is a positive integer that is a power of 2 (>= 2)."
  (and (integerp n) (>= n 2) (zerop (logand n (1- n)))))

(defun %opt-mul-by-const-seq (dst src n new-reg-fn)
  "Build a shift/add instruction sequence computing DST ← SRC * N.
NEW-REG-FN is a thunk that allocates fresh temporary register keywords.
Returns a list of vm instructions (may include vm-const, vm-ash, vm-add, vm-move, vm-neg)."
  (let* ((negp (minusp n))
         (absn (abs n)))
    (cond
      ((zerop absn)
       (list (make-vm-const :dst dst :value 0)))
      ((= absn 1)
       (append (list (make-vm-move :dst dst :src src))
               (when negp (list (make-vm-neg :dst dst :src dst)))))
      (t
       (let ((bits  (loop for bit from 0 below (integer-length absn)
                          when (logbitp bit absn) collect bit))
             (seq   nil)
             (terms nil))
         (dolist (bit bits)
           (if (zerop bit)
               (push src terms)
               (let ((shift-count (funcall new-reg-fn))
                     (shifted     (funcall new-reg-fn)))
                 (push (make-vm-const :dst shift-count :value bit) seq)
                 (push (make-vm-ash   :dst shifted :lhs src :rhs shift-count) seq)
                 (push shifted terms))))
         (setf terms (nreverse terms))
         (let ((first (car terms)))
           (unless (eq first dst)
             (push (make-vm-move :dst dst :src first) seq))
           (dolist (term (cdr terms))
             (push (make-vm-add :dst dst :lhs dst :rhs term) seq))
           (when negp
             (push (make-vm-neg :dst dst :src dst) seq))
           (nreverse seq)))))))

(defun opt-pass-strength-reduce (instructions)
  "Forward pass: replace multiply/divide by powers of 2 with arithmetic shifts.
   - (* x 2^k) → (ash x k)
   - (* 2^k x) → (ash x k)   [commutative]
   - (/ x 2^k) → (ash x -k)  [floor semantics: (floor x 2^k) = (ash x -k)]
   - (mod x 2^k) → (logand x (2^k - 1))
   - (* x N)   → shift/add decomposition for small integer constants N
   At vm-label boundaries, flush the constant environment."
  (let* ((env     (make-hash-table :test #'eq))
         (base    (1+ (opt-max-reg-index instructions)))
         (counter base)
         (result  nil))
    (flet ((new-reg  () (prog1 (intern (format nil "R~A" counter) :keyword) (incf counter)))
           (const-val (reg) (gethash reg env))
           (emit      (i) (push i result))
           (emit-seq  (insts) (dolist (i insts) (push i result))))
      (dolist (inst instructions)
        (typecase inst
          (vm-label
           (clrhash env)
           (emit inst))
          (vm-const
           (setf (gethash (vm-dst inst) env) (vm-value inst))
           (emit inst))
          (vm-mul
           (let* ((dst (vm-dst inst))
                  (lhs (vm-lhs inst))
                  (rhs (vm-rhs inst))
                  (rv  (const-val rhs))
                  (lv  (const-val lhs)))
             (cond
               ((and rv (opt-power-of-2-p rv))
                (let* ((k         (1- (integer-length rv)))
                       (shift-reg (new-reg)))
                  (remhash dst env)
                  (emit (make-vm-const :dst shift-reg :value k))
                  (emit (make-vm-ash   :dst dst :lhs lhs :rhs shift-reg))))
               ((and lv (opt-power-of-2-p lv))
                (let* ((k         (1- (integer-length lv)))
                       (shift-reg (new-reg)))
                  (remhash dst env)
                  (emit (make-vm-const :dst shift-reg :value k))
                  (emit (make-vm-ash   :dst dst :lhs rhs :rhs shift-reg))))
               ((and rv (integerp rv) (not (zerop rv)) (<= (logcount (abs rv)) 2))
                (remhash dst env)
                (emit-seq (%opt-mul-by-const-seq dst lhs rv #'new-reg)))
               ((and lv (integerp lv) (not (zerop lv)) (<= (logcount (abs lv)) 2))
                (remhash dst env)
                (emit-seq (%opt-mul-by-const-seq dst rhs lv #'new-reg)))
               (t (emit inst)))))
          (vm-div
           (let* ((dst (vm-dst inst))
                  (lhs (vm-lhs inst))
                  (rhs (vm-rhs inst))
                  (rv  (const-val rhs)))
             (cond
               ((and rv (opt-power-of-2-p rv))
                (let* ((k         (- (1- (integer-length rv))))
                       (shift-reg (new-reg)))
                  (remhash dst env)
                  (emit (make-vm-const :dst shift-reg :value k))
                  (emit (make-vm-ash   :dst dst :lhs lhs :rhs shift-reg))))
               (t
                (let ((dstreg (opt-inst-dst inst)))
                  (when dstreg (remhash dstreg env)))
                (emit inst)))))
          (vm-mod
           (let* ((dst (vm-dst inst))
                  (lhs (vm-lhs inst))
                  (rhs (vm-rhs inst))
                  (rv  (const-val rhs)))
             (cond
               ((and rv (opt-power-of-2-p rv))
                (let ((mask-reg (new-reg)))
                  (remhash dst env)
                  (emit (make-vm-const  :dst mask-reg :value (1- rv)))
                  (emit (make-vm-logand :dst dst :lhs lhs :rhs mask-reg))))
               (t
                (let ((dstreg (opt-inst-dst inst)))
                  (when dstreg (remhash dstreg env)))
                (emit inst)))))
           (t
            (let ((dst (opt-inst-dst inst)))
              (when dst (remhash dst env)))
            (emit inst)))))
    (nreverse result)))

(defun opt-bswap-recognition-match-at (instructions pos)
  (let ((end (+ pos 19)))
    (when (<= end (length instructions))
      (let* ((c0 (nth (+ pos 0) instructions))
             (a0 (nth (+ pos 1) instructions))
             (s0 (nth (+ pos 2) instructions))
             (b0 (nth (+ pos 3) instructions))
             (c1 (nth (+ pos 4) instructions))
             (a1 (nth (+ pos 5) instructions))
             (s1 (nth (+ pos 6) instructions))
             (b1 (nth (+ pos 7) instructions))
             (c2 (nth (+ pos 8) instructions))
             (a2 (nth (+ pos 9) instructions))
             (s2 (nth (+ pos 10) instructions))
             (b2 (nth (+ pos 11) instructions))
             (c3 (nth (+ pos 12) instructions))
             (a3 (nth (+ pos 13) instructions))
             (s3 (nth (+ pos 14) instructions))
             (b3 (nth (+ pos 15) instructions))
             (o0 (nth (+ pos 16) instructions))
             (o1 (nth (+ pos 17) instructions))
             (o2 (nth (+ pos 18) instructions)))
        (when (and (typep c0 'vm-const)
                   (eql (vm-value c0) #xFF)
                   (typep a0 'vm-logand)
                   (typep s0 'vm-const)
                   (typep b0 'vm-ash)
                   (typep c1 'vm-const)
                   (eql (vm-value c1) #xFF00)
                   (typep a1 'vm-logand)
                   (typep s1 'vm-const)
                   (typep b1 'vm-ash)
                   (typep c2 'vm-const)
                   (eql (vm-value c2) #xFF0000)
                   (typep a2 'vm-logand)
                   (typep s2 'vm-const)
                   (typep b2 'vm-ash)
                   (typep c3 'vm-const)
                   (eql (vm-value c3) #xFF000000)
                   (typep a3 'vm-logand)
                   (typep s3 'vm-const)
                   (typep b3 'vm-ash)
                   (typep o0 'vm-logior)
                   (typep o1 'vm-logior)
                   (typep o2 'vm-logior))
            (let* ((src (vm-lhs a0))
                   (dst (vm-dst o2)))
              (when (and (eq (vm-lhs a0) src)
                         (eq (vm-rhs a0) (vm-dst c0))
                         (eq (vm-lhs a1) src)
                         (eq (vm-rhs a1) (vm-dst c1))
                         (eq (vm-lhs a2) src)
                         (eq (vm-rhs a2) (vm-dst c2))
                         (eq (vm-lhs a3) src)
                         (eq (vm-rhs a3) (vm-dst c3))
                         (equal (mapcar #'vm-value (list s0 s1 s2 s3)) '(24 8 -8 -24))
                         (eq (vm-lhs b0) (vm-dst a0))
                         (eq (vm-rhs b0) (vm-dst s0))
                         (eq (vm-lhs b1) (vm-dst a1))
                         (eq (vm-rhs b1) (vm-dst s1))
                         (eq (vm-lhs b2) (vm-dst a2))
                         (eq (vm-rhs b2) (vm-dst s2))
                         (eq (vm-lhs b3) (vm-dst a3))
                         (eq (vm-rhs b3) (vm-dst s3))
                         (eq (vm-lhs o0) (vm-dst b0))
                         (eq (vm-rhs o0) (vm-dst b1))
                         (eq (vm-lhs o1) (vm-dst b2))
                         (eq (vm-rhs o1) (vm-dst b3))
                         (eq (vm-lhs o2) (vm-dst o0))
                         (eq (vm-rhs o2) (vm-dst o1)))
                (values (make-vm-bswap :dst dst :src src) 19))))))))

(defun opt-pass-bswap-recognition (instructions)
  "Collapse explicit byte-swap bit-manipulation trees into vm-bswap.

   Recognizes the canonical 32-bit reverse-bytes tree built from four masked
   extracts, four shifts, and three logior nodes, matching the bswap pattern
   documented for the backend."
  (let ((result nil)
        (i 0)
        (n (length instructions)))
    (do () ((>= i n) (nreverse result))
      (multiple-value-bind (rewritten consumed)
          (opt-bswap-recognition-match-at instructions i)
        (if rewritten
            (progn
              (push rewritten result)
              (incf i consumed))
              (progn
                (push (nth i instructions) result)
                 (incf i 1)))))))

(defun opt-rotate-recognition-match-at (instructions pos)
  (let ((end (+ pos 5)))
    (when (<= end (length instructions))
      (let* ((c0 (nth (+ pos 0) instructions))
             (a0 (nth (+ pos 1) instructions))
             (c1 (nth (+ pos 2) instructions))
             (a1 (nth (+ pos 3) instructions))
             (o0 (nth (+ pos 4) instructions)))
        (when (and (typep c0 'vm-const)
                   (typep a0 'vm-ash)
                   (typep c1 'vm-const)
                   (typep a1 'vm-ash)
                   (typep o0 'vm-logior))
          (let* ((k0 (vm-value c0))
                 (k1 (vm-value c1))
                 (src0 (vm-lhs a0))
                 (src1 (vm-lhs a1))
                 (count0 (vm-rhs a0))
                 (count1 (vm-rhs a1))
                 (dst0 (vm-dst a0))
                 (dst1 (vm-dst a1))
                 (out-dst (vm-dst o0)))
            (when (and (integerp k0)
                       (integerp k1)
                       (eq src0 src1)
                       (eq count0 (vm-dst c0))
                       (eq count1 (vm-dst c1))
                       (or (and (eq (vm-lhs o0) dst0) (eq (vm-rhs o0) dst1))
                           (and (eq (vm-lhs o0) dst1) (eq (vm-rhs o0) dst0))))
              (cond
                ((and (plusp k0) (= k1 (- k0 64)))
                 (values (list (make-vm-const :dst (vm-dst c1)
                                              :value (mod (- 64 k0) 64))
                               (make-vm-rotate :dst out-dst
                                               :lhs src0
                                               :rhs (vm-dst c1)))
                         5))
                ((and (plusp k1) (= k0 (- k1 64)))
                 (values (list (make-vm-const :dst (vm-dst c0)
                                              :value (mod (- 64 k1) 64))
                               (make-vm-rotate :dst out-dst
                                               :lhs src0
                                               :rhs (vm-dst c0)))
                         5))))))))))

(defun opt-pass-rotate-recognition (instructions)
  "Collapse rotate idioms into vm-rotate.

   Recognizes the classic two-shift + OR tree that implements a 64-bit rotate
   and replaces it with a single vm-rotate plus the normalized count constant."
  (let ((result nil)
        (i 0)
        (n (length instructions)))
    (do () ((>= i n) (nreverse result))
        (multiple-value-bind (rewritten consumed)
            (opt-rotate-recognition-match-at instructions i)
        (if rewritten
            (progn
              (dolist (inst (reverse rewritten))
                (push inst result))
              (incf i consumed))
            (progn
              (push (nth i instructions) result)
              (incf i 1)))))))

;;; (Arithmetic reassociation and batch concatenation passes are in
;;;  optimizer-strength-ext.lisp which loads after this file.)
