(in-package :cl-cc/runtime)
(defstruct rt-actor
  (id (gensym "ACTOR-")) (name nil) (mailbox nil) (behavior nil)
  (task nil) (links nil) (monitors nil) (supervisor nil) (children nil)
  (status :created) (m (rt-make-mutex)) (c (rt-make-condition-variable)))
(defstruct rt-supervisor (strategy :one-for-one) (children nil) (restarts 0))
(defvar *rt-actor-registry* (make-hash-table :test #'equal))
(defun rt-make-actor (behavior &key name supervisor)
  (let ((a (make-rt-actor :behavior behavior :name name :supervisor supervisor)))
    (when name (setf (gethash name *rt-actor-registry*) a))
    (when supervisor (push a (rt-supervisor-children supervisor)))
    a))
(defun rt-actor-whereis (name) (gethash name *rt-actor-registry*))
(defun rt-actor-register (name actor) (setf (rt-actor-name actor) name (gethash name *rt-actor-registry*) actor))
(defun rt-actor-unregister (name) (remhash name *rt-actor-registry*))
(defun rt-actor-send (a msg) (rt-with-mutex ((rt-actor-m a)) (push msg (rt-actor-mailbox a)) (rt-condition-notify (rt-actor-c a))) msg)
(defun rt-actor-receive (a &key timeout)
  (rt-with-mutex ((rt-actor-m a) :timeout timeout)
    (loop until (or (eq (rt-actor-status a) :stopped) (rt-actor-mailbox a))
          do (rt-condition-wait (rt-actor-c a) (rt-actor-m a) :timeout timeout))
    (when (rt-actor-mailbox a) (pop (rt-actor-mailbox a)))))
(defun rt-actor-link (a b) (pushnew b (rt-actor-links a)) (pushnew a (rt-actor-links b)) b)
(defun rt-actor-monitor (watcher target) (pushnew watcher (rt-actor-monitors target)) target)
(defun rt-make-supervisor (&key (strategy :one-for-one)) (make-rt-supervisor :strategy strategy))
(defun %rt-actor-notify-exit (a reason)
  (dolist (m (rt-actor-monitors a)) (rt-actor-send m (list :down a reason)))
  (dolist (l (rt-actor-links a)) (rt-actor-send l (list :exit a reason))))
(defun %rt-supervisor-restart (sup actor)
  (when sup
    (incf (rt-supervisor-restarts sup))
    (case (rt-supervisor-strategy sup)
      (:one-for-one (funcall (symbol-function 'rt-actor-spawn) actor))
      (:one-for-all (dolist (child (rt-supervisor-children sup))
                      (funcall (symbol-function 'rt-actor-spawn) child))))))
(defun rt-actor-stop (a &optional (reason :normal))
  (rt-with-mutex ((rt-actor-m a))
    (setf (rt-actor-status a) :stopped)
    (rt-condition-notify-all (rt-actor-c a)))
  (%rt-actor-notify-exit a reason)
  a)
(defun rt-actor-spawn (a)
  (setf (rt-actor-status a) :running
        (rt-actor-task a)
        (rt-spawn
         (lambda ()
           (loop until (eq (rt-actor-status a) :stopped)
                 for msg = (rt-actor-receive a)
                 when msg do
                   (handler-case (funcall (rt-actor-behavior a) msg)
                     (error (c)
                       (setf (rt-actor-status a) :failed)
                       (%rt-actor-notify-exit a c)
                       (%rt-supervisor-restart (rt-actor-supervisor a) a)
                       (return c)))))))
  a)
(defun rt-actor-clear-registry () (clrhash *rt-actor-registry*) t)
