;;;; CSP Channels (FR-282)
(in-package :cl-cc/runtime)
(defstruct rt-channel
  (buffer nil) (capacity 0) (closed-p nil)
  (mutex (rt-make-mutex))
  (send-cond (rt-make-condition-variable))
  (recv-cond (rt-make-condition-variable)))
(defun rt-make-channel (&key (capacity 0)) (make-rt-channel :capacity (max 0 capacity)))
(defun rt-channel-open-p (ch) (not (rt-channel-closed-p ch)))
(defun rt-channel-buffered-p (ch) (> (rt-channel-capacity ch) 0))
(defun rt-channel-count (ch) (length (rt-channel-buffer ch)))
(defun %rt-channel-full-p (ch)
  (and (rt-channel-buffered-p ch)
       (>= (length (rt-channel-buffer ch)) (rt-channel-capacity ch))))
(defun %rt-channel-enqueue (ch val)
  (setf (rt-channel-buffer ch) (nconc (rt-channel-buffer ch) (list val))))
(defun %rt-channel-dequeue (ch)
  (let ((val (car (rt-channel-buffer ch))))
    (setf (rt-channel-buffer ch) (cdr (rt-channel-buffer ch)))
    val))
(defun rt-channel-send (ch val &key timeout)
  (rt-with-mutex ((rt-channel-mutex ch) :timeout timeout)
    (when (rt-channel-closed-p ch) (error "channel closed"))
    (loop while (%rt-channel-full-p ch)
          do (rt-condition-wait (rt-channel-send-cond ch) (rt-channel-mutex ch) :timeout timeout))
    (%rt-channel-enqueue ch val)
    (rt-condition-notify (rt-channel-recv-cond ch))
    val))
(defun rt-channel-recv (ch &key timeout)
  (rt-with-mutex ((rt-channel-mutex ch) :timeout timeout)
    (loop until (or (rt-channel-closed-p ch) (rt-channel-buffer ch))
          do (rt-condition-wait (rt-channel-recv-cond ch) (rt-channel-mutex ch) :timeout timeout))
    (if (and (rt-channel-closed-p ch) (null (rt-channel-buffer ch)))
        (values nil nil)
        (let ((val (%rt-channel-dequeue ch)))
          (rt-condition-notify (rt-channel-send-cond ch))
          (values val t)))))
(defun rt-channel-try-send (ch val)
  (rt-with-mutex ((rt-channel-mutex ch))
    (when (and (not (rt-channel-closed-p ch)) (not (%rt-channel-full-p ch)))
      (%rt-channel-enqueue ch val)
      (rt-condition-notify (rt-channel-recv-cond ch))
      t)))
(defun rt-channel-try-recv (ch)
  (rt-with-mutex ((rt-channel-mutex ch))
    (when (rt-channel-buffer ch)
      (let ((val (%rt-channel-dequeue ch)))
        (rt-condition-notify (rt-channel-send-cond ch))
        (values val t)))))
(defun rt-channel-close (ch)
  (rt-with-mutex ((rt-channel-mutex ch))
    (setf (rt-channel-closed-p ch) t)
    (rt-condition-notify-all (rt-channel-recv-cond ch))
    (rt-condition-notify-all (rt-channel-send-cond ch))
    t))
(defun rt-channel-select (channels &key timeout default)
  (let ((deadline (and timeout (+ (get-internal-real-time)
                                  (floor (* timeout internal-time-units-per-second))))))
    (loop
      (dolist (ch channels)
        (multiple-value-bind (val ok) (rt-channel-try-recv ch)
          (when ok (return-from rt-channel-select (values val ch t)))))
      (when default (return-from rt-channel-select (values default nil nil)))
      (when (and deadline (>= (get-internal-real-time) deadline))
        (return-from rt-channel-select (values nil nil nil)))
      (sleep 0.001))))
