(in-package :cl-cc/runtime)
(defstruct rt-lamport-clock (time 0))
(defun rt-make-lamport-clock () (make-rt-lamport-clock))
(defun rt-lamport-now (c) (rt-lamport-clock-time c))
(defun rt-lamport-tick (c) (incf (rt-lamport-clock-time c)))
(defstruct rt-vector-clock (entries (make-hash-table :test #'eql)))
(defun rt-make-vector-clock () (make-rt-vector-clock))
(defun rt-vc-get (vc id) (gethash id (rt-vector-clock-entries vc) 0))
(defun rt-vc-tick (vc id) (incf (gethash id (rt-vector-clock-entries vc) 0)))
(defun rt-vc-merge (vc o) (maphash (lambda (k v) (setf (gethash k (rt-vector-clock-entries vc)) (max v (gethash k (rt-vector-clock-entries vc) 0)))) (rt-vector-clock-entries o)) vc)
(defun rt-clock-init () t)
