(in-package :cl-cc/runtime)
(defstruct rt-cluster-node (id "") (host "127.0.0.1") (port 0) (status :unknown))
(defvar *rt-cluster-nodes* (make-hash-table :test #'equal))
(defvar *rt-cluster-local* nil)
(defun rt-cluster-init (&key (id "node-1") (host "127.0.0.1") (port 0)) (setf *rt-cluster-local* (make-rt-cluster-node :id id :host host :port port :status :up)) (clrhash *rt-cluster-nodes*) (setf (gethash id *rt-cluster-nodes*) *rt-cluster-local*) t)
(defun rt-cluster-join (id host port) (setf (gethash id *rt-cluster-nodes*) (make-rt-cluster-node :id id :host host :port port :status :up)))
(defun rt-cluster-leave (id) (remhash id *rt-cluster-nodes*))
(defun rt-cluster-query-node-status (id) (let ((n (gethash id *rt-cluster-nodes*))) (when n (rt-cluster-node-status n))))
(defun rt-remote-send (ref msg) (declare (ignore ref msg)) nil)
(defstruct rt-remote-actor-ref (node-id "") (actor-id ""))
(defun rt-make-remote-ref (nid aid) (make-rt-remote-actor-ref :node-id nid :actor-id aid))
