(in-package :cl-cc/runtime)
(defconstant +raft-follower+ 0) (defconstant +raft-candidate+ 1) (defconstant +raft-leader+ 2)
(defstruct rt-raft-entry (term 0) (index 0) (command nil))
(defstruct rt-raft-node (id "") (state +raft-follower+) (current-term 0) (voted-for nil) (log nil) (commit-index 0) (election-timeout 150) (election-timer 0))
(defstruct rt-raft-cluster (nodes (make-hash-table :test #'equal)) (node-ids nil) (leader-id nil))
(defun rt-make-raft-node (id &key (election-timeout 150)) (make-rt-raft-node :id id :election-timeout election-timeout :election-timer (random election-timeout)))
(defun rt-make-raft-cluster (ids) (let ((c (make-rt-raft-cluster :node-ids ids))) (dolist (id ids) (setf (gethash id (rt-raft-cluster-nodes c)) (rt-make-raft-node id))) c))
(defun rt-raft-become-leader (n c) (setf (rt-raft-node-state n) +raft-leader+ (rt-raft-cluster-leader-id c) (rt-raft-node-id n)))
(defun rt-raft-request-vote (cand voter) (let ((ct (rt-raft-node-current-term cand))) (when (< ct (rt-raft-node-current-term voter)) (return-from rt-raft-request-vote nil)) (when (>= (length (rt-raft-node-log cand)) (length (rt-raft-node-log voter))) (setf (rt-raft-node-voted-for voter) (rt-raft-node-id cand)) t)))
(defun rt-raft-propose (c val) (let* ((lid (rt-raft-cluster-leader-id c)) (ldr (gethash lid (rt-raft-cluster-nodes c)))) (unless (and ldr (eq (rt-raft-node-state ldr) +raft-leader+)) (error "No leader")) (let ((e (make-rt-raft-entry :term (rt-raft-node-current-term ldr) :index (1+ (length (rt-raft-node-log ldr))) :command val))) (push e (rt-raft-node-log ldr)) (setf (rt-raft-node-commit-index ldr) (rt-raft-entry-index e)) val)))
(defun rt-raft-snapshot (node) (rt-raft-node-log node))
(defun rt-consensus-init () t)
