(in-package :cl-cc/runtime)
(defstruct rt-context (dl nil) (cancelled nil) (values nil) (parent nil))
(defvar *rt-current-context* nil)
(defmacro rt-with-context ((&key deadline) &body body)
  (let ((ctx (gensym "CTX")))
    `(let* ((,ctx (make-rt-context :dl ,deadline :parent *rt-current-context*))
            (*rt-current-context* ,ctx))
       ,@body)))
(defun rt-context-copy (&optional (ctx *rt-current-context*))
  (when ctx
    (make-rt-context :dl (rt-context-dl ctx)
                     :cancelled (rt-context-cancelled ctx)
                     :values (copy-list (rt-context-values ctx))
                     :parent (rt-context-parent ctx))))
(defun rt-context-get-deadline () (when *rt-current-context* (rt-context-dl *rt-current-context*)))
(defun rt-context-cancel (&optional (ctx *rt-current-context*))
  (when ctx (setf (rt-context-cancelled ctx) t)))
(defun rt-context-cancelled-p (&optional (ctx *rt-current-context*))
  (and ctx (or (rt-context-cancelled ctx)
               (and (rt-context-parent ctx) (rt-context-cancelled-p (rt-context-parent ctx)))
               (and (rt-context-dl ctx) (> (get-internal-real-time) (rt-context-dl ctx))))))
(defun rt-context-value (key &optional (ctx *rt-current-context*))
  (when ctx
    (let ((hit (assoc key (rt-context-values ctx))))
      (if hit (cdr hit) (rt-context-value key (rt-context-parent ctx))))))
(defun rt-context-set-value (key val &optional (ctx *rt-current-context*))
  (when ctx (push (cons key val) (rt-context-values ctx)) val))
(defun rt-context-spawn (thunk &key (priority :normal))
  (let ((ctx (rt-context-copy)))
    (funcall (symbol-function 'rt-spawn)
             (lambda ()
               (let ((*rt-current-context* ctx))
                 (funcall thunk)))
             :priority priority)))
(defmacro rt-with-context-value ((key value) &body body)
  `(let ((*rt-current-context* (or (rt-context-copy) (make-rt-context))))
     (rt-context-set-value ,key ,value)
     ,@body))
