(in-package :cl-cc/runtime)
(defstruct rt-context (dl nil) (cancelled nil) (values nil))
(defvar *rt-current-context* nil)
(defmacro rt-with-context ((&key deadline) &body body)
  (let ((ctx (gensym "CTX")))
    `(let* ((,ctx (make-rt-context :dl ,deadline))
            (*rt-current-context* ,ctx))
       ,@body)))
(defun rt-context-get-deadline () (when *rt-current-context* (rt-context-dl *rt-current-context*)))
(defun rt-context-cancel () (when *rt-current-context* (setf (rt-context-cancelled *rt-current-context*) t)))
(defun rt-context-cancelled-p () (and *rt-current-context* (rt-context-cancelled *rt-current-context*)))
(defun rt-context-value (key) (when *rt-current-context* (cdr (assoc key (rt-context-values *rt-current-context*)))))
(defun rt-context-set-value (key val) (when *rt-current-context* (push (cons key val) (rt-context-values *rt-current-context*)) val))
