(in-package :cl-cc/runtime)
(defstruct rt-gcounter (slots (make-hash-table :test #'eql)))
(defun rt-make-gcounter () (make-rt-gcounter))
(defun rt-gcounter-increment (c nid &optional (d 1))
  (incf (gethash nid (rt-gcounter-slots c) 0) d))
(defun rt-gcounter-value (c)
  (let ((s 0))
    (maphash (lambda (k v) (declare (ignore k)) (incf s v))
             (rt-gcounter-slots c))
    s))
(defun rt-gcounter-merge (c o)
  (maphash (lambda (k v)
              (setf (gethash k (rt-gcounter-slots c))
                    (max v (gethash k (rt-gcounter-slots c) 0))))
           (rt-gcounter-slots o))
  c)
(defstruct rt-pncounter
  (pos (rt-make-gcounter)) (neg (rt-make-gcounter)))
(defun rt-make-pncounter () (make-rt-pncounter))
(defun rt-pncounter-increment (c id &optional (d 1))
  (rt-gcounter-increment (rt-pncounter-pos c) id d))
(defun rt-pncounter-decrement (c id &optional (d 1))
  (rt-gcounter-increment (rt-pncounter-neg c) id d))
(defun rt-pncounter-value (c)
  (- (rt-gcounter-value (rt-pncounter-pos c))
     (rt-gcounter-value (rt-pncounter-neg c))))
(defstruct rt-lwwregister (value nil) (ts 0))
(defun rt-make-lwwregister (&optional init)
  (make-rt-lwwregister :value init))
(defun rt-lwwregister-assign (r v)
  (setf (rt-lwwregister-value r) v
        (rt-lwwregister-ts r) (get-universal-time))
  v)
(defun rt-lwwregister-read (r) (rt-lwwregister-value r))
(defun rt-crdt-init () t)
