(in-package :cl-cc/runtime)
(defstruct rt-gcounter (slots (make-hash-table :test #'eql)))
(defun rt-make-gcounter () (make-rt-gcounter))
(defun rt-gcounter-inc (c nid &optional (d 1)) (incf (gethash nid (rt-gcounter-slots c) 0) d))
(defun rt-gcounter-value (c) (let ((s 0)) (maphash (lambda (k v) (declare (ignore k)) (incf s v)) (rt-gcounter-slots c)) s))
(defun rt-gcounter-merge (c o) (maphash (lambda (k v) (setf (gethash k (rt-gcounter-slots c)) (max v (gethash k (rt-gcounter-slots c) 0)))) (rt-gcounter-slots o)) c)
(defstruct rt-pncounter (inc (rt-make-gcounter)) (dec (rt-make-gcounter)))
(defun rt-make-pncounter () (make-rt-pncounter))
(defun rt-pncounter-inc (c id &optional (d 1)) (rt-gcounter-inc (rt-pncounter-inc c) id d))
(defun rt-pncounter-dec (c id &optional (d 1)) (rt-gcounter-inc (rt-pncounter-dec c) id d))
(defun rt-pncounter-value (c) (- (rt-gcounter-value (rt-pncounter-inc c)) (rt-gcounter-value (rt-pncounter-dec c))))
(defstruct rt-lwwregister (value nil) (ts 0))
(defun rt-make-lwwregister (&optional init) (make-rt-lwwregister :value init))
(defun rt-lwwregister-set (r v) (setf (rt-lwwregister-value r) v (rt-lwwregister-ts r) (get-universal-time)) v)
(defun rt-lwwregister-get (r) (rt-lwwregister-value r))
(defun rt-crdt-init () t)
