;;;; Epoch-Based Reclamation (FR-320)
(in-package :cl-cc/runtime)
(defconstant +ebr-epochs+ 3)
(defstruct rt-ebr-local (epoch 0) (in-critical 0) (retired-0 nil) (retired-1 nil) (retired-2 nil))
(defvar *ebr-global-epoch* 0)
(defvar *ebr-thread-locals* (make-hash-table))
(defvar *ebr-free-function* #'identity)
(defvar *ebr-mutex* (rt-make-mutex))
(defun rt-ebr-init (&optional (free-fn #'identity)) (setf *ebr-free-function* free-fn) (clrhash *ebr-thread-locals*) (setf *ebr-global-epoch* 0))
(defun rt-ebr-register-thread (&optional (thread sb-thread:*current-thread*)) (setf (gethash thread *ebr-thread-locals*) (make-rt-ebr-local)))
(defun rt-ebr-unregister-thread (&optional (thread sb-thread:*current-thread*)) (remhash thread *ebr-thread-locals*))
(defun rt-ebr-enter (local) (incf (rt-ebr-local-in-critical local)))
(defun rt-ebr-leave (local) (when (> (rt-ebr-local-in-critical local) 0) (decf (rt-ebr-local-in-critical local))) (when (zerop (rt-ebr-local-in-critical local)) (setf (rt-ebr-local-epoch local) *ebr-global-epoch*)))
(defmacro rt-with-ebr-critical ((local) &body body) `(progn (rt-ebr-enter ,local) (unwind-protect (progn ,@body) (rt-ebr-leave ,local))))
(defun rt-ebr-retire (local obj) (let ((e (rt-ebr-local-epoch local))) (case e (0 (push obj (rt-ebr-local-retired-0 local))) (1 (push obj (rt-ebr-local-retired-1 local))) (2 (push obj (rt-ebr-local-retired-2 local))))))
(defun %rt-ebr-retired-list (local epoch)
  (case epoch
    (0 (rt-ebr-local-retired-0 local))
    (1 (rt-ebr-local-retired-1 local))
    (2 (rt-ebr-local-retired-2 local))))
(defun (setf %rt-ebr-retired-list) (value local epoch)
  (case epoch
    (0 (setf (rt-ebr-local-retired-0 local) value))
    (1 (setf (rt-ebr-local-retired-1 local) value))
    (2 (setf (rt-ebr-local-retired-2 local) value))))
(defun rt-ebr-can-advance-p ()
  (let ((epoch *ebr-global-epoch*) (ok t))
    (maphash (lambda (thread local)
               (declare (ignore thread))
               (when (and (> (rt-ebr-local-in-critical local) 0)
                          (/= (rt-ebr-local-epoch local) epoch))
                 (setf ok nil)))
             *ebr-thread-locals*)
    ok))
(defun rt-ebr-advance-epoch ()
  (rt-with-mutex (*ebr-mutex*)
    (when (rt-ebr-can-advance-p)
      (setf *ebr-global-epoch* (mod (1+ *ebr-global-epoch*) +ebr-epochs+))
      t)))
(defun rt-ebr-reclaim (local)
  (let* ((safe (mod (+ *ebr-global-epoch* 1) +ebr-epochs+))
         (items (%rt-ebr-retired-list local safe)))
    (setf (%rt-ebr-retired-list local safe) nil)
    (dolist (obj items) (funcall *ebr-free-function* obj))
    (length items)))
(defun rt-ebr-collect (&optional local)
  (rt-ebr-advance-epoch)
  (if local
      (rt-ebr-reclaim local)
      (let ((n 0))
        (maphash (lambda (thread loc) (declare (ignore thread)) (incf n (rt-ebr-reclaim loc)))
                 *ebr-thread-locals*)
        n)))
(defun rt-ebr-current-local (&optional (thread sb-thread:*current-thread*))
  (or (gethash thread *ebr-thread-locals*)
      (rt-ebr-register-thread thread)))
