;;;; Epoch-Based Reclamation (FR-320)
(in-package :cl-cc/runtime)
(defconstant +ebr-epochs+ 3)
(defstruct rt-ebr-local (epoch 0) (in-critical 0) (retired-0 nil) (retired-1 nil) (retired-2 nil))
(defvar *ebr-global-epoch* 0)
(defvar *ebr-thread-locals* (make-hash-table))
(defvar *ebr-free-function* #'identity)
(defun rt-ebr-init (&optional (free-fn #'identity)) (setf *ebr-free-function* free-fn) (clrhash *ebr-thread-locals*) (setf *ebr-global-epoch* 0))
(defun rt-ebr-register-thread (&optional (thread sb-thread:*current-thread*)) (setf (gethash thread *ebr-thread-locals*) (make-rt-ebr-local)))
(defun rt-ebr-unregister-thread (&optional (thread sb-thread:*current-thread*)) (remhash thread *ebr-thread-locals*))
(defun rt-ebr-enter (local) (incf (rt-ebr-local-in-critical local)))
(defun rt-ebr-leave (local) (when (> (rt-ebr-local-in-critical local) 0) (decf (rt-ebr-local-in-critical local))) (when (zerop (rt-ebr-local-in-critical local)) (setf (rt-ebr-local-epoch local) *ebr-global-epoch*)))
(defmacro rt-with-ebr-critical ((local) &body body) `(progn (rt-ebr-enter ,local) (unwind-protect (progn ,@body) (rt-ebr-leave ,local))))
(defun rt-ebr-retire (local obj) (let ((e (rt-ebr-local-epoch local))) (case e (0 (push obj (rt-ebr-local-retired-0 local))) (1 (push obj (rt-ebr-local-retired-1 local))) (2 (push obj (rt-ebr-local-retired-2 local))))))
