(in-package :cl-cc/runtime)
(defstruct rt-fiber
  (id 0) (thunk nil) (status :ready) (result nil) (error nil)
  (locals (make-hash-table :test #'eq)) (yielded-value nil))
(defvar *rt-fiber-counter* 0)
(defvar *rt-current-fiber* nil)
(defvar *rt-fiber-ready* nil)
(defun rt-make-fiber (thunk)
  (make-rt-fiber :id (incf *rt-fiber-counter*) :thunk thunk))
(defun rt-fiber-schedule (fiber)
  (setf (rt-fiber-status fiber) :ready)
  (push fiber *rt-fiber-ready*)
  fiber)
(defun rt-fiber-spawn (thunk)
  (rt-fiber-schedule (rt-make-fiber thunk)))
(defun rt-fiber-resume (f)
  (when (member (rt-fiber-status f) '(:done :failed :cancelled))
    (return-from rt-fiber-resume (rt-fiber-result f)))
  (setf (rt-fiber-status f) :running)
  (handler-case
      (let ((*rt-current-fiber* f))
        (setf (rt-fiber-result f) (funcall (rt-fiber-thunk f)))
        (setf (rt-fiber-status f) :done)
        (rt-fiber-result f))
    (error (c)
      (setf (rt-fiber-error f) c
            (rt-fiber-status f) :failed)
      nil)))
(defun rt-fiber-done-p (f) (eq (rt-fiber-status f) :done))
(defun rt-fiber-status-failed-p (f) (eq (rt-fiber-status f) :failed))
(defun rt-fiber-yield (&optional value)
  (when *rt-current-fiber*
    (setf (rt-fiber-yielded-value *rt-current-fiber*) value
          (rt-fiber-status *rt-current-fiber*) :ready)
    (rt-fiber-schedule *rt-current-fiber*))
  value)
(defun rt-fiber-local (key &optional default)
  (if *rt-current-fiber*
      (gethash key (rt-fiber-locals *rt-current-fiber*) default)
      default))
(defun (setf rt-fiber-local) (value key &optional default)
  (declare (ignore default))
  (unless *rt-current-fiber* (error "no current fiber"))
  (setf (gethash key (rt-fiber-locals *rt-current-fiber*)) value))
(defun rt-run-fibers (&key once)
  (loop for f = (pop *rt-fiber-ready*)
        while f
        do (rt-fiber-resume f)
        when once return f))
