;;;; Future/Promise (FR-283)
(in-package :cl-cc/runtime)
(defstruct rt-future
  (value nil) (resolved-p nil)
  (mutex (rt-make-mutex)) (cond (rt-make-condition-variable)))
(defun rt-make-future () (make-rt-future))
(defun rt-future-resolve (f val)
  (rt-with-mutex ((rt-future-mutex f))
    (setf (rt-future-value f) val
          (rt-future-resolved-p f) t)
    (rt-condition-notify-all (rt-future-cond f)))
  val)
(defun rt-future-await (f &key timeout)
  (rt-with-mutex ((rt-future-mutex f) :timeout timeout)
    (loop until (rt-future-resolved-p f)
          do (rt-condition-wait (rt-future-cond f)
                                (rt-future-mutex f)
                                :timeout timeout)))
  (rt-future-value f))
(defun rt-future-then (f callback)
  (let ((new-f (rt-make-future)))
    (rt-spawn (lambda ()
                (rt-future-resolve new-f
                  (funcall callback (rt-future-await f)))))
    new-f))
(defun rt-future-done-p (f) (rt-future-resolved-p f))
(defun rt-all-futures (futures)
  (dolist (f futures) (rt-future-await f))
  futures)
