;;;; Hazard Pointers (FR-321)
(in-package :cl-cc/runtime)
(defvar *hazard-thread-arrays* (make-hash-table))
(defvar *hazard-slots-per-thread* 4)
(defun rt-hp-register-thread (&optional (n *hazard-slots-per-thread*) (thread sb-thread:*current-thread*)) (setf (gethash thread *hazard-thread-arrays*) (make-array n :initial-element nil)))
(defun rt-hp-unregister-thread (&optional (thread sb-thread:*current-thread*)) (remhash thread *hazard-thread-arrays*))
(defun rt-hp-protect (idx obj &optional (thread sb-thread:*current-thread*)) (let ((a (gethash thread *hazard-thread-arrays*))) (when a (setf (svref a (min idx (1- (length a)))) obj)) idx))
(defun rt-hp-clear (idx &optional (thread sb-thread:*current-thread*)) (let ((a (gethash thread *hazard-thread-arrays*))) (when a (setf (svref a (min idx (1- (length a)))) nil))))
(defun rt-hp-clear-all (&optional (thread sb-thread:*current-thread*)) (let ((a (gethash thread *hazard-thread-arrays*))) (when a (fill a nil))))
(defun rt-hp-scan (objects) (let ((protected (make-hash-table :test #'eq))) (maphash (lambda (th arr) (declare (ignore th)) (dotimes (i (length arr)) (let ((o (svref arr i))) (when o (setf (gethash o protected) t))))) *hazard-thread-arrays*) (remove-if (lambda (o) (gethash o protected)) objects)))
(defun rt-hp-retire (retired free-fn threshold) (if (< (length retired) threshold) retired (let ((safe (rt-hp-scan retired)) (rem nil)) (dolist (o retired (nreverse rem)) (if (member o safe :test #'eq) (funcall free-fn o) (push o rem))))))
(defun rt-hp-init () (clrhash *hazard-thread-arrays*) t)
