;;;; Hazard Pointers (FR-321)
(in-package :cl-cc/runtime)
(defvar *hazard-thread-arrays* (make-hash-table))
(defvar *hazard-slots-per-thread* 4)
(defvar *hazard-retired* (make-hash-table))
(defvar *hazard-retire-threshold* 32)
(defvar *hazard-free-function* #'identity)
(defun rt-hp-register-thread (&optional (n *hazard-slots-per-thread*) (thread sb-thread:*current-thread*)) (setf (gethash thread *hazard-thread-arrays*) (make-array n :initial-element nil)))
(defun rt-hp-unregister-thread (&optional (thread sb-thread:*current-thread*)) (remhash thread *hazard-thread-arrays*))
(defun rt-hp-protect (idx obj &optional (thread sb-thread:*current-thread*)) (let ((a (gethash thread *hazard-thread-arrays*))) (when a (setf (svref a (min idx (1- (length a)))) obj)) idx))
(defun rt-hp-clear (idx &optional (thread sb-thread:*current-thread*)) (let ((a (gethash thread *hazard-thread-arrays*))) (when a (setf (svref a (min idx (1- (length a)))) nil))))
(defun rt-hp-clear-all (&optional (thread sb-thread:*current-thread*)) (let ((a (gethash thread *hazard-thread-arrays*))) (when a (fill a nil))))
(defun rt-hp-scan (objects) (let ((protected (make-hash-table :test #'eq))) (maphash (lambda (th arr) (declare (ignore th)) (dotimes (i (length arr)) (let ((o (svref arr i))) (when o (setf (gethash o protected) t))))) *hazard-thread-arrays*) (remove-if (lambda (o) (gethash o protected)) objects)))
(defun rt-hp-retire (retired free-fn threshold) (if (< (length retired) threshold) retired (let ((safe (rt-hp-scan retired)) (rem nil)) (dolist (o retired (nreverse rem)) (if (member o safe :test #'eq) (funcall free-fn o) (push o rem))))))
(defun rt-hp-retire-object (obj &key (thread sb-thread:*current-thread*)
                                      (free-fn *hazard-free-function*)
                                      (threshold *hazard-retire-threshold*))
  (let ((list (cons obj (gethash thread *hazard-retired*))))
    (setf (gethash thread *hazard-retired*)
          (if (>= (length list) threshold)
              (rt-hp-retire list free-fn threshold)
              list))))
(defun rt-hp-all-protected ()
  (let ((protected nil))
    (maphash (lambda (th arr)
               (declare (ignore th))
               (dotimes (i (length arr))
                 (let ((obj (svref arr i)))
                   (when obj (pushnew obj protected :test #'eq)))))
             *hazard-thread-arrays*)
    protected))
(defun rt-hp-reclaim (&key (thread sb-thread:*current-thread*)
                           (free-fn *hazard-free-function*))
  (let* ((retired (gethash thread *hazard-retired*))
         (protected (rt-hp-all-protected))
         (remaining nil)
         (freed 0))
    (dolist (obj retired)
      (if (member obj protected :test #'eq)
          (push obj remaining)
          (progn (funcall free-fn obj) (incf freed))))
    (setf (gethash thread *hazard-retired*) (nreverse remaining))
    freed))
(defun rt-hp-set-threshold (n) (setf *hazard-retire-threshold* (max 1 n)))
(defun rt-hp-init (&optional (free-fn #'identity))
  (setf *hazard-free-function* free-fn)
  (clrhash *hazard-thread-arrays*)
  (clrhash *hazard-retired*)
  t)
