;;;; Lock-Free Data Structures (FR-322)
(in-package :cl-cc/runtime)
(defstruct rt-lfstack-node (value nil) (next nil))
(defstruct rt-lfstack (top nil))
(defun rt-make-lfstack () (make-rt-lfstack))
(defun rt-lfstack-push (s v) (setf (rt-lfstack-top s) (make-rt-lfstack-node :value v :next (rt-lfstack-top s))) v)
(defun rt-lfstack-pop (s) (let ((top (rt-lfstack-top s))) (when top (setf (rt-lfstack-top s) (rt-lfstack-node-next top)) (values (rt-lfstack-node-value top) t))))
(defun rt-lfstack-empty-p (s) (null (rt-lfstack-top s)))
(defstruct rt-lfqueue-node (value nil) (next nil))
(defstruct rt-lfqueue (head nil) (tail nil) (mutex (rt-make-mutex)))
(defun rt-make-lfqueue () (let ((d (make-rt-lfqueue-node))) (make-rt-lfqueue :head d :tail d)))
(defun rt-lfqueue-push (q v) (rt-with-mutex ((rt-lfqueue-mutex q)) (let ((n (make-rt-lfqueue-node :value v))) (setf (rt-lfqueue-node-next (rt-lfqueue-tail q)) n) (setf (rt-lfqueue-tail q) n))) v)
(defun rt-lfqueue-pop (q) (rt-with-mutex ((rt-lfqueue-mutex q)) (let ((n (rt-lfqueue-node-next (rt-lfqueue-head q)))) (when n (setf (rt-lfqueue-head q) n) (values (rt-lfqueue-node-value n) t)))))
(defun rt-lfqueue-empty-p (q) (null (rt-lfqueue-node-next (rt-lfqueue-head q))))
(defstruct rt-lfhash-map (table (make-hash-table :test #'equal)) (mutex (rt-make-mutex)))
(defun rt-make-lfhash-map (&key (test 'eql)) (declare (ignore test)) (make-rt-lfhash-map))
(defun rt-lfhash-get (m k &optional d) (rt-with-mutex ((rt-lfhash-map-mutex m)) (gethash k (rt-lfhash-map-table m) d)))
(defun rt-lfhash-put (m k v) (rt-with-mutex ((rt-lfhash-map-mutex m)) (setf (gethash k (rt-lfhash-map-table m)) v)))
(defun rt-lfhash-remove (m k) (rt-with-mutex ((rt-lfhash-map-mutex m)) (remhash k (rt-lfhash-map-table m)) t))
(defun rt-lfhash-count (m) (hash-table-count (rt-lfhash-map-table m)))
(defun rt-lockfree-init () t)
