(in-package :cl-cc/runtime)
(defconstant +log-level-info+ 2) (defconstant +log-level-warn+ 3) (defconstant +log-level-error+ 4)
(defvar *rt-log-level* +log-level-info+)
(defvar *rt-log-out* *standard-output*)
(defun rt-log (level msg &key attrs) (declare (ignore attrs)) (when (>= level *rt-log-level*) (format *rt-log-out* "[~D] ~A~%" level msg) (force-output *rt-log-out*)))
(defun rt-log-warn (m &key a) (rt-log +log-level-warn+ m :attrs a))
(defun rt-log-error (m &key a) (rt-log +log-level-error+ m :attrs a))
(defun rt-log-set-level (l) (setf *rt-log-level* l))
(defun rt-log-init () (setf *rt-log-level* +log-level-info+) t)
