;;;; Memory-Mapped I/O (FR-349)
(in-package :cl-cc/runtime)
(defconstant +rt-prot-none+ 0) (defconstant +rt-prot-read+ 1) (defconstant +rt-prot-write+ 2) (defconstant +rt-prot-exec+ 4)
(defconstant +rt-map-shared+ 1) (defconstant +rt-map-private+ 2) (defconstant +rt-map-fixed+ 16) (defconstant +rt-map-anonymous+ 32)
(defun rt-mmap-raw (addr length prot flags fd offset) (declare (ignore addr length prot flags fd offset)) nil)
(defun rt-munmap-raw (addr length) (declare (ignore addr length)) t)
(defun rt-mprotect (addr length prot) (declare (ignore addr length prot)) nil)
(defun rt-allocate-code-memory (size) (declare (ignore size)) nil)
(defun rt-release-code-memory (addr size) (declare (ignore addr size)) nil)
(defun rt-allocate-anonymous-memory (size &key prot) (declare (ignore size prot)) nil)
(defun rt-mmap-init () t)
