(in-package :cl-cc/runtime)
(defstruct rt-mvcc-var (versions nil) (m (rt-make-mutex)))
(defstruct rt-mvcc-version (value nil) (ts 0) (deleted-p nil) (next nil))
(defstruct rt-mvcc-tx (snapshot 0) (writes nil) (active-p t))
(defvar *rt-mvcc-global-time* 0)
(defvar *rt-current-mvcc-tx* nil)
(defun rt-make-mvcc-var (&optional value)
  (let ((var (make-rt-mvcc-var)))
    (when value (funcall (symbol-function 'rt-mvcc-write) var value))
    var))
(defun %rt-mvcc-visible-version (var snapshot)
  (find-if (lambda (v) (<= (rt-mvcc-version-ts v) snapshot))
           (rt-mvcc-var-versions var)))
(defun rt-mvcc-read (var &optional (tx *rt-current-mvcc-tx*))
  (let ((pending (and tx (assoc var (rt-mvcc-tx-writes tx)))))
    (if pending
        (cdr pending)
        (rt-with-mutex ((rt-mvcc-var-m var))
          (let ((v (%rt-mvcc-visible-version var (if tx (rt-mvcc-tx-snapshot tx) *rt-mvcc-global-time*))))
            (when (and v (not (rt-mvcc-version-deleted-p v)))
              (rt-mvcc-version-value v)))))))
(defun rt-mvcc-write (var val &optional (tx *rt-current-mvcc-tx*))
  (if tx
      (let ((cell (assoc var (rt-mvcc-tx-writes tx))))
        (if cell (setf (cdr cell) val) (push (cons var val) (rt-mvcc-tx-writes tx)))
        val)
      (rt-with-mutex ((rt-mvcc-var-m var))
        (incf *rt-mvcc-global-time*)
        (push (make-rt-mvcc-version :value val :ts *rt-mvcc-global-time*
                                    :next (car (rt-mvcc-var-versions var)))
              (rt-mvcc-var-versions var))
        val)))
(defun rt-mvcc-begin () (make-rt-mvcc-tx :snapshot *rt-mvcc-global-time*))
(defun rt-mvcc-commit (&optional (tx *rt-current-mvcc-tx*))
  (when tx
    (dolist (w (rt-mvcc-tx-writes tx))
      (rt-mvcc-write (car w) (cdr w) nil))
    (setf (rt-mvcc-tx-active-p tx) nil))
  t)
(defun rt-mvcc-abort (&optional (tx *rt-current-mvcc-tx*))
  (when tx
    (setf (rt-mvcc-tx-writes tx) nil
          (rt-mvcc-tx-active-p tx) nil))
  nil)
(defmacro rt-with-mvcc-transaction (() &body body)
  `(let ((*rt-current-mvcc-tx* (rt-mvcc-begin)))
     (handler-case
         (prog1 (progn ,@body) (rt-mvcc-commit *rt-current-mvcc-tx*))
       (error (c) (rt-mvcc-abort *rt-current-mvcc-tx*) (error c)))))
(defun rt-mvcc-compact (var older-than)
  (rt-with-mutex ((rt-mvcc-var-m var))
    (setf (rt-mvcc-var-versions var)
          (remove-if (lambda (v) (< (rt-mvcc-version-ts v) older-than))
                     (rt-mvcc-var-versions var)))))
