;;;; Socket/Network Primitives (FR-574)
(in-package :cl-cc/runtime)
(defstruct rt-socket-address (host "127.0.0.1") (port 0))
(defvar *rt-socket-registry* (make-hash-table))
(defvar *rt-next-socket-fd* 100)
(defconstant +rt-sock-stream+ 1) (defconstant +rt-sock-dgram+ 2)
(defun rt-socket (type &key) (declare (ignore type)) (let ((fd (prog1 *rt-next-socket-fd* (incf *rt-next-socket-fd*)))) (setf (gethash fd *rt-socket-registry*) t) fd))
(defun rt-bind (fd addr) (declare (ignore fd addr)) t)
(defun rt-listen (fd &optional (backlog 5)) (declare (ignore fd backlog)) t)
(defun rt-accept (fd) (declare (ignore fd)) nil)
(defun rt-connect (fd addr) (declare (ignore fd addr)) t)
(defun rt-set-nonblocking (fd) (declare (ignore fd)) t)
(defun rt-close-socket (fd) (remhash fd *rt-socket-registry*) t)
(defun rt-socket-send (fd buf &key start end) (declare (ignore fd buf start end)) 0)
(defun rt-socket-recv (fd buf &key start end) (declare (ignore fd buf start end)) 0)
(defun rt-select (rf wf ef &optional to) (declare (ignore rf wf ef to)) (values nil nil nil))
(defun rt-net-init () (clrhash *rt-socket-registry*) (setf *rt-next-socket-fd* 100) t)
