;;;; OS Abstraction Layer (FR-570, FR-573)
(in-package :cl-cc/runtime)
(eval-when (:compile-toplevel :load-toplevel :execute) #+sbcl (require :sb-posix))
(defun rt-open (path mode &key if-exists if-does-not-exist)
  (open path :direction (case mode (:input :input) (:output :output) (:io :io) (t :input))
        :if-exists if-exists :if-does-not-exist if-does-not-exist))
(defun rt-close (stream) (close stream) t)
(defun rt-getenv (name) #+sbcl (sb-ext:posix-getenv name) #-sbcl (error "not implemented"))
(defun rt-argv () #+sbcl sb-ext:*posix-argv* #-sbcl (list "cl-cc"))
(defun rt-exit (&optional (code 0)) #+sbcl (sb-ext:exit :code code) #-sbcl (cl:quit code))
(defun rt-getcwd () (namestring (truename ".")))
(defun rt-chdir (path) (setf *default-pathname-defaults* (truename path)) (namestring path))
(defun rt-sleep (s) (sleep s))
(defun rt-gettime-monotonic () (/ (get-internal-real-time) (float internal-time-units-per-second)))
(defun rt-gettime-real () (get-universal-time))
(defun rt-probe-file (p) (probe-file p))
(defun rt-delete-file (p) (delete-file p) t)
(defun rt-rename-file (old new) (rename-file old new))
(defun rt-file-write-date (p) (file-write-date p))
(defun rt-ensure-directories-exist (p &key verbose) (ensure-directories-exist p :verbose verbose))
(defun rt-directory (p &key) (directory p))
(defvar *rt-saved-argv* nil)
(defvar *rt-max-call-stack-depth* 10000)
(defvar *rt-stack-depth* 0)
(defvar *rt-instruction-limit* nil)
(defvar *rt-instruction-count* 0)
(defun rt-os-init (&key argv) (setf *rt-saved-argv* argv) t)
