(in-package :cl-cc/runtime)
(defvar *rt-parallel-threshold* 1024)
(defvar *rt-fork-join-pool* nil)
(defun rt-parallel-p (size) (>= size *rt-parallel-threshold*))
(defun rt-fork-join (left right combine)
  "Run LEFT and RIGHT as fork/join tasks when a scheduler is present."
  (if *rt-global-scheduler*
      (let ((lt (rt-spawn left :priority :high))
            (rv (funcall right)))
        (rt-scheduler-run)
        (funcall combine (rt-green-thread-result lt) rv))
      (funcall combine (funcall left) (funcall right))))

(defun %rt-merge-vectors (a b pred key)
  (let* ((na (length a)) (nb (length b)) (out (make-array (+ na nb)))
         (i 0) (j 0) (k 0))
    (loop while (and (< i na) (< j nb))
          do (let ((av (aref a i)) (bv (aref b j)))
               (if (funcall pred (if key (funcall key av) av)
                            (if key (funcall key bv) bv))
                   (progn (setf (aref out k) av) (incf i))
                   (progn (setf (aref out k) bv) (incf j)))
               (incf k)))
    (loop while (< i na) do (setf (aref out k) (aref a i)) (incf i) (incf k))
    (loop while (< j nb) do (setf (aref out k) (aref b j)) (incf j) (incf k))
    out))

(defun rt-parallel-sort (seq pred &key key)
  (let* ((vec (coerce seq 'vector)))
    (labels ((psort (v)
               (let ((len (length v)))
                 (if (not (rt-parallel-p len))
                     (sort v pred :key key)
                     (let* ((mid (floor len 2))
                            (left (subseq v 0 mid))
                            (right (subseq v mid)))
                       (rt-fork-join (lambda () (psort left))
                                     (lambda () (psort right))
                                     (lambda (a b) (%rt-merge-vectors a b pred key))))))))
      (let ((sorted (psort vec)))
        (if (listp seq) (coerce sorted 'list) (replace seq sorted))))))

(defun rt-parallel-scan (vec fn init &key inclusive)
  (let* ((n (length vec)) (res (make-array n)) (acc init))
    (dotimes (i n)
      (if inclusive
          (progn (setf acc (funcall fn acc (aref vec i)))
                 (setf (aref res i) acc))
          (progn (setf (aref res i) acc)
                 (setf acc (funcall fn acc (aref vec i))))))
    res))
(defun rt-parallel-prefix-scan (vec fn init) (rt-parallel-scan vec fn init :inclusive t))
(defun rt-parallel-reduce (fn seq &key iv) (if iv (reduce fn seq :initial-value iv) (reduce fn seq)))
(defun rt-parallel-map (fn seq)
  (let ((items (coerce seq 'list)))
    (if (not (rt-parallel-p (length items)))
        (mapcar fn items)
        (let ((tasks (mapcar (lambda (x) (rt-spawn (lambda () (funcall fn x)))) items)))
          (rt-scheduler-run)
          (mapcar #'rt-green-thread-result tasks)))))
(defun rt-parallel-for (start end fn)
  (let ((tasks nil))
    (loop for i from start below end
          do (push (rt-spawn (let ((j i)) (lambda () (funcall fn j)))) tasks))
    (rt-scheduler-run)
    (nreverse tasks)))
(defun rt-parallel-algo-init () (setf *rt-parallel-threshold* 1024) t)
