;;;; Quiescent State Based Reclamation (FR-452)
(in-package :cl-cc/runtime)
(defvar *qsbr-threads* (make-hash-table))
(defvar *qsbr-retired* nil)
(defvar *qsbr-pending-free* nil)
(defvar *qsbr-free-function* #'identity)
(defun rt-qsbr-init (&optional (free-fn #'identity)) (setf *qsbr-free-function* free-fn) (clrhash *qsbr-threads*) (setf *qsbr-retired* nil *qsbr-pending-free* nil))
(defun rt-qsbr-register-thread (&optional (thread sb-thread:*current-thread*)) (setf (gethash thread *qsbr-threads*) t))
(defun rt-qsbr-unregister-thread (&optional (thread sb-thread:*current-thread*)) (remhash thread *qsbr-threads*))
(defun rt-qsbr-quiescent (&optional (thread sb-thread:*current-thread*)) (setf (gethash thread *qsbr-threads*) t))
(defun rt-qsbr-retire (obj) (push obj *qsbr-retired*))
(defun rt-qsbr-synchronize () (let ((threads (loop for k being the hash-keys of *qsbr-threads* collect k))) (dolist (th threads) (setf (gethash th *qsbr-threads*) nil)) (loop until (every (lambda (th) (gethash th *qsbr-threads*)) threads) do (sleep 0.001))) (dolist (obj *qsbr-pending-free*) (funcall *qsbr-free-function* obj)) (setf *qsbr-pending-free* *qsbr-retired* *qsbr-retired* nil))
(defun rt-qsbr-thread-count () (hash-table-count *qsbr-threads*))
