;;;; Green Threads Scheduler (FR-257, FR-258)
(in-package :cl-cc/runtime)
(defstruct (rt-green-thread (:constructor %make-rt-green-thread)) (id 0) (thunk nil) (status :ready) (result nil) (error nil) (wake-time nil) (cancelled-p nil))
(defstruct rt-scheduler (ready nil) (sleeping nil) (counter 0) (mutex (rt-make-mutex)))
(defvar *rt-global-scheduler* nil)
(defvar *rt-current-green-thread* nil)
(defun rt-make-scheduler () (make-rt-scheduler))
(defun rt-scheduler-init () (setf *rt-global-scheduler* (rt-make-scheduler)) t)
(defun rt-spawn (thunk) (let* ((s *rt-global-scheduler*) (t (%make-rt-green-thread :id (incf (rt-scheduler-counter s)) :thunk thunk))) (push t (rt-scheduler-ready s)) t))
(defun rt-yield () (when *rt-current-green-thread* (push *rt-current-green-thread* (rt-scheduler-ready *rt-global-scheduler*))))
(defun rt-current-thread-id () (when *rt-current-green-thread* (rt-green-thread-id *rt-current-green-thread*)))
(defun rt-sleep-task (s) (when *rt-current-green-thread* (setf (rt-green-thread-status *rt-current-green-thread*) :sleeping (rt-green-thread-wake-time *rt-current-green-thread*) (+ (get-internal-real-time) (floor (* s internal-time-units-per-second)))) (push *rt-current-green-thread* (rt-scheduler-sleeping *rt-global-scheduler*))))
(defun rt-scheduler-run () (let ((s *rt-global-scheduler*)) (loop (let ((t (pop (rt-scheduler-ready s)))) (when t (let ((*rt-current-green-thread* t)) (setf (rt-green-thread-status t) :running) (handler-case (progn (setf (rt-green-thread-result t) (funcall (rt-green-thread-thunk t))) (setf (rt-green-thread-status t) :done)) (error (c) (setf (rt-green-thread-status t) :failed (rt-green-thread-error t) c)))))) (let ((now (get-internal-real-time))) (setf (rt-scheduler-sleeping s) (remove-if (lambda (th) (when (and (rt-green-thread-wake-time th) (<= (rt-green-thread-wake-time th) now)) (setf (rt-green-thread-wake-time th) nil (rt-green-thread-status th) :ready) (push th (rt-scheduler-ready s)) t)) (rt-scheduler-sleeping s))))))))
