;;;; Green Threads Scheduler (FR-257, FR-258)
(in-package :cl-cc/runtime)
(defstruct (rt-green-thread (:constructor %make-rt-green-thread)) (id 0) (thunk nil) (status :ready) (result nil) (error nil) (wake-time nil) (cancelled-p nil))
(defstruct rt-scheduler (ready nil) (sleeping nil) (counter 0) (mutex (rt-make-mutex)))
(defvar *rt-global-scheduler* nil)
(defvar *rt-current-green-thread* nil)
(defun rt-make-scheduler () (make-rt-scheduler))
(defun rt-scheduler-init () (setf *rt-global-scheduler* (rt-make-scheduler)) t)
(defun %rt-enqueue (sched thread) (rt-with-mutex ((rt-scheduler-mutex sched)) (push thread (rt-scheduler-ready sched))))
(defun %rt-dequeue (sched) (rt-with-mutex ((rt-scheduler-mutex sched)) (pop (rt-scheduler-ready sched))))
(defun rt-spawn (thunk) (let* ((sched *rt-global-scheduler*) (thread (%make-rt-green-thread :id (incf (rt-scheduler-counter sched)) :thunk thunk))) (%rt-enqueue sched thread) thread))
(defun rt-yield () (when *rt-current-green-thread* (%rt-enqueue *rt-global-scheduler* *rt-current-green-thread*)))
(defun rt-current-thread-id () (when *rt-current-green-thread* (rt-green-thread-id *rt-current-green-thread*)))
(defun %rt-now () (get-internal-real-time))
(defun rt-sleep-task (seconds) (when *rt-current-green-thread* (setf (rt-green-thread-status *rt-current-green-thread*) :sleeping (rt-green-thread-wake-time *rt-current-green-thread*) (+ (%rt-now) (floor (* seconds internal-time-units-per-second)))) (push *rt-current-green-thread* (rt-scheduler-sleeping *rt-global-scheduler*))))
(defun rt-scheduler-run () (let ((sched *rt-global-scheduler*)) (loop (let ((thread (%rt-dequeue sched))) (when thread (let ((*rt-current-green-thread* thread)) (setf (rt-green-thread-status thread) :running) (handler-case (setf (rt-green-thread-result thread) (funcall (rt-green-thread-thunk thread)) (rt-green-thread-status thread) :done) (error (c) (setf (rt-green-thread-status thread) :failed (rt-green-thread-error thread) c)))))) (let ((now (%rt-now))) (rt-with-mutex ((rt-scheduler-mutex sched)) (setf (rt-scheduler-sleeping sched) (remove-if (lambda (th) (when (and (rt-green-thread-wake-time th) (<= (rt-green-thread-wake-time th) now)) (setf (rt-green-thread-wake-time th) nil (rt-green-thread-status th) :ready) (%rt-enqueue sched th) t)) (rt-scheduler-sleeping sched)))))))))
