(in-package :cl-cc/runtime)
(defstruct ser-ctx (br (make-hash-table :test #'eq)) (rbr (make-hash-table :test #'eql)) (nid 0 :type integer))
(declaim (inline %ser-tnil %ser-tfix %ser-tflt %ser-tstr %ser-tsym %ser-tcons %ser-tvec %ser-thash %ser-tref %ser-tt))
(defun %ser-tnil () 0) (defun %ser-tfix () 1) (defun %ser-tflt () 2) (defun %ser-tstr () 3) (defun %ser-tsym () 4)
(defun %ser-tcons () 5) (defun %ser-tvec () 6) (defun %ser-thash () 7) (defun %ser-tref () 8) (defun %ser-tt () 9)
(defun %ser-wb (b s) (write-byte (logand b #xFF) s))
(defun %ser-wtag (t s) (%ser-wb t s))
(defun %ser-wfix (n s) (%ser-wtag (%ser-tfix) s) (let ((v (abs n))) (loop (let ((b (logand v #x7F))) (setf v (ash v -7)) (when (plusp v) (setf b (logior b #x80))) (%ser-wb b s) (when (zerop v) (return)))) (%ser-wb (if (minusp n) 1 0) s)))
(defun %ser-wstr (str s) (%ser-wtag (%ser-tstr) s) (let* ((o (map '(vector (unsigned-byte 8)) #'char-code str)) (len (length o))) (%ser-wfix len s) (write-sequence o s)))
(defun %ser-obj (o c s)
  (unless (or (numberp o) (characterp o)) (let ((e (gethash o (ser-ctx-br c)))) (when e (%ser-wtag (%ser-tref) s) (%ser-wfix e s) (return-from %ser-obj o)) (setf (gethash o (ser-ctx-br c)) (ser-ctx-nid c)) (incf (ser-ctx-nid c))))
  (cond ((null o) (%ser-wtag (%ser-tnil) s)) ((eq o t) (%ser-wtag (%ser-tt) s)) ((fixnump o) (%ser-wfix o s)) ((floatp o) (%ser-wtag (%ser-tflt) s) (let ((m (nth-value 0 (integer-decode-float o)))) (dotimes (i (if (typep o 'double-float) 8 4)) (%ser-wb (ldb (byte 8 (* i 8)) (abs m)) s)))) ((stringp o) (%ser-wstr o s)) ((symbolp o) (%ser-wtag (%ser-tsym) s) (%ser-wstr (format nil "~A::~A" (package-name (symbol-package o)) (symbol-name o)) s)) ((consp o) (%ser-wtag (%ser-tcons) s) (%ser-obj (car o) c s) (%ser-obj (cdr o) c s)) ((vectorp o) (%ser-wtag (%ser-tvec) s) (%ser-wfix (length o) s) (dotimes (i (length o)) (%ser-obj (aref o i) c s))) ((hash-table-p o) (%ser-wtag (%ser-thash) s) (%ser-wfix (hash-table-count o) s) (maphash (lambda (k v) (%ser-obj k c s) (%ser-obj v c s)) o)) (t (%ser-wstr (format nil "#<~S>" (type-of o)) s))))
(defun serialize (o s) (let ((c (make-ser-ctx))) (%ser-obj o c s)))
(defun %ser-rb (s) (let ((b (read-byte s nil :eof))) (when (eq b :eof) (error "EOF")) b))
(defun %ser-rfix (s) (let ((r 0) (sh 0)) (loop (let ((b (%ser-rb s))) (setf r (logior r (ash (logand b #x7F) sh))) (when (zerop (logand b #x80)) (return)) (incf sh 7))) (if (= (%ser-rb s) 1) (- r) r)))
(defun %ser-robj (c s)
  (let ((tag (%ser-rb s)))
    (cond ((= tag (%ser-tnil)) nil) ((= tag (%ser-tt)) t) ((= tag (%ser-tfix)) (%ser-rfix s))
          ((= tag (%ser-tstr)) (let* ((len (%ser-rfix s)) (o (make-array len :element-type '(unsigned-byte 8)))) (read-sequence o s) (map 'string #'code-char o)))
          ((= tag (%ser-tsym)) (let* ((str (%ser-robj (make-ser-ctx) s)) (col (position #\: str))) (if (and col (char= (char str (1+ col)) #\:)) (intern (subseq str (+ col 2)) (subseq str 0 col)) (intern str))))
          ((= tag (%ser-tcons)) (let ((ca (%ser-robj c s)) (cd (%ser-robj c s))) (cons ca cd)))
          ((= tag (%ser-tvec)) (let* ((len (%ser-rfix s)) (v (make-array len))) (dotimes (i len) (setf (aref v i) (%ser-robj c s))) v))
          ((= tag (%ser-thash)) (let* ((cnt (%ser-rfix s)) (tbl (make-hash-table :test #'equal :size cnt))) (dotimes (i cnt) (setf (gethash (%ser-robj c s) tbl) (%ser-robj c s))) tbl))
          ((= tag (%ser-tref)) (gethash (%ser-rfix s) (ser-ctx-rbr c)))
          ((= tag (%ser-tflt)) 0.0d0) (t (error "Unknown tag: ~D" tag)))))
(defun deserialize (s) (let ((c (make-ser-ctx))) (%ser-robj c s)))
