;;;; OS Signal Handling (FR-348, FR-572)
(in-package :cl-cc/runtime)
(defconstant +rt-sigint+ 2) (defconstant +rt-sigsegv+ 11) (defconstant +rt-sigfpe+ 8) (defconstant +rt-sigpipe+ 13)
(defconstant +rt-sigprof+ 27) (defconstant +rt-sigusr1+ 10) (defconstant +rt-sigusr2+ 12)
(defstruct rt-signal-handler (signal 0) (function nil) (one-shot-p nil))
(defvar *rt-signal-handlers* (make-hash-table))
(defun rt-install-signal-handler (sig fn &key one-shot) (push (make-rt-signal-handler :signal sig :function fn :one-shot-p one-shot) (gethash sig *rt-signal-handlers* nil)) (car (gethash sig *rt-signal-handlers*)))
(defun rt-remove-signal-handler (h) (setf (gethash (rt-signal-handler-signal h) *rt-signal-handlers*) (remove h (gethash (rt-signal-handler-signal h) *rt-signal-handlers*))))
(defun rt-install-default-signal-handlers () (rt-install-signal-handler +rt-sigint+ (lambda (s) (declare (ignore s)) (format t "~&Interrupt~%"))) t)
(defun rt-signals-init () (clrhash *rt-signal-handlers*) (rt-install-default-signal-handlers) t)
