;;;; SPSC Ring Buffer (FR-462)
(in-package :cl-cc/runtime)
(defstruct rt-spsc-queue (buffer nil) (mask 0) (head 0) (tail 0) (producer nil) (consumer nil))
(defun rt-make-spsc-queue (cap) (let ((c (max 2 (expt 2 (ceiling (log cap 2)))))) (make-rt-spsc-queue :buffer (make-array c :initial-element nil) :mask (1- c))))
(defun rt-spsc-capacity (q) (1+ (rt-spsc-queue-mask q)))
(defun rt-spsc-size (q) (let ((h (rt-spsc-queue-head q)) (tl (rt-spsc-queue-tail q))) (- h tl)))
(defun rt-spsc-empty-p (q) (= (rt-spsc-queue-head q) (rt-spsc-queue-tail q)))
(defun rt-spsc-full-p (q) (= (- (rt-spsc-queue-head q) (rt-spsc-queue-tail q)) (1+ (rt-spsc-queue-mask q))))
(defun %rt-spsc-thread () sb-thread:*current-thread*)
(defun %rt-spsc-claim-producer (q)
  (let ((me (%rt-spsc-thread)))
    (or (eq (rt-spsc-queue-producer q) me)
        (null (rt-spsc-queue-producer q))
        (error "SPSC queue already has a producer"))
    (setf (rt-spsc-queue-producer q) me)))
(defun %rt-spsc-claim-consumer (q)
  (let ((me (%rt-spsc-thread)))
    (or (eq (rt-spsc-queue-consumer q) me)
        (null (rt-spsc-queue-consumer q))
        (error "SPSC queue already has a consumer"))
    (setf (rt-spsc-queue-consumer q) me)))
(defun rt-spsc-try-push (q item)
  (%rt-spsc-claim-producer q)
  (let* ((h (rt-spsc-queue-head q)) (tl (rt-spsc-queue-tail q)) (mask (rt-spsc-queue-mask q)))
    (when (= (- h tl) (1+ mask)) (return-from rt-spsc-try-push nil))
    (setf (svref (rt-spsc-queue-buffer q) (logand h mask)) item)
    (setf (rt-spsc-queue-head q) (1+ h))
    t))
(defun rt-spsc-try-pop (q)
  (%rt-spsc-claim-consumer q)
  (let ((h (rt-spsc-queue-head q)) (tl (rt-spsc-queue-tail q)))
    (when (= h tl) (return-from rt-spsc-try-pop (values nil nil)))
    (let* ((mask (rt-spsc-queue-mask q)) (item (svref (rt-spsc-queue-buffer q) (logand tl mask))))
      (setf (svref (rt-spsc-queue-buffer q) (logand tl mask)) nil)
      (setf (rt-spsc-queue-tail q) (1+ tl))
      (values item t))))
(defun rt-spsc-push (q item &key spin)
  (loop until (rt-spsc-try-push q item)
        do (when spin (sleep 0.0001)))
  item)
(defun rt-spsc-pop (q &key spin)
  (loop
    (multiple-value-bind (item ok) (rt-spsc-try-pop q)
      (when ok (return item)))
    (when spin (sleep 0.0001))))
(defun rt-spsc-reset (q)
  (fill (rt-spsc-queue-buffer q) nil)
  (setf (rt-spsc-queue-head q) 0
        (rt-spsc-queue-tail q) 0
        (rt-spsc-queue-producer q) nil
        (rt-spsc-queue-consumer q) nil)
  q)
(defun rt-spsc-init () t)
