;;;; SPSC Ring Buffer (FR-462)
(in-package :cl-cc/runtime)
(defstruct rt-spsc-queue (buffer nil) (mask 0) (head 0) (tail 0))
(defun rt-make-spsc-queue (cap) (let ((c (max 2 (expt 2 (ceiling (log cap 2)))))) (make-rt-spsc-queue :buffer (make-array c :initial-element nil) :mask (1- c))))
(defun rt-spsc-capacity (q) (1+ (rt-spsc-queue-mask q)))
(defun rt-spsc-size (q) (let ((h (rt-spsc-queue-head q)) (tl (rt-spsc-queue-tail q))) (- h tl)))
(defun rt-spsc-empty-p (q) (= (rt-spsc-queue-head q) (rt-spsc-queue-tail q)))
(defun rt-spsc-full-p (q) (= (- (rt-spsc-queue-head q) (rt-spsc-queue-tail q)) (1+ (rt-spsc-queue-mask q))))
(defun rt-spsc-try-push (q item) (let* ((h (rt-spsc-queue-head q)) (tl (rt-spsc-queue-tail q)) (mask (rt-spsc-queue-mask q))) (when (= (- h tl) (1+ mask)) (return-from rt-spsc-try-push nil)) (setf (svref (rt-spsc-queue-buffer q) (logand h mask)) item) (setf (rt-spsc-queue-head q) (1+ h)) t))
(defun rt-spsc-try-pop (q) (let ((h (rt-spsc-queue-head q)) (tl (rt-spsc-queue-tail q))) (when (= h tl) (return-from rt-spsc-try-pop (values nil nil))) (let* ((mask (rt-spsc-queue-mask q)) (item (svref (rt-spsc-queue-buffer q) (logand tl mask)))) (setf (svref (rt-spsc-queue-buffer q) (logand tl mask)) nil) (setf (rt-spsc-queue-tail q) (1+ tl)) (values item t))))
(defun rt-spsc-init () t)
