(in-package :cl-cc/runtime)
(defstruct rt-tvar (value nil) (version 0) (lock (rt-make-mutex)) (waiters (rt-make-condition-variable)))
(define-condition rt-stm-conflict (error) ())
(define-condition rt-stm-retry (condition) ())
(defvar *rt-stm-read-log* nil)
(defvar *rt-stm-write-log* nil)
(defvar *rt-stm-clock* 0)
(defun rt-make-tvar (&optional value) (make-rt-tvar :value value :version (incf *rt-stm-clock*)))
(defun rt-read-tvar (tv)
  (let ((value nil) (version nil))
    (rt-with-mutex ((rt-tvar-lock tv))
      (setf value (rt-tvar-value tv)
            version (rt-tvar-version tv)))
    (push (list tv version) *rt-stm-read-log*)
    (let ((pending (assoc tv *rt-stm-write-log*)))
      (if pending (cdr pending) value))))
(defun rt-write-tvar (tv value)
  (let ((cell (assoc tv *rt-stm-write-log*)))
    (if cell
        (setf (cdr cell) value)
        (push (cons tv value) *rt-stm-write-log*)))
  value)
(defun %rt-stm-conflict-p ()
  (some (lambda (entry)
          (destructuring-bind (tv version) entry
            (rt-with-mutex ((rt-tvar-lock tv))
              (/= version (rt-tvar-version tv)))))
        *rt-stm-read-log*))
(defun %rt-stm-commit ()
  (when (%rt-stm-conflict-p) (error 'rt-stm-conflict))
  (dolist (entry *rt-stm-write-log*)
    (let ((tv (car entry)) (value (cdr entry)))
      (rt-with-mutex ((rt-tvar-lock tv))
        (setf (rt-tvar-value tv) value
              (rt-tvar-version tv) (incf *rt-stm-clock*))
        (rt-condition-notify-all (rt-tvar-waiters tv)))))
  t)
(defmacro rt-atomically (&body body)
  `(loop
     (let ((*rt-stm-read-log* nil)
           (*rt-stm-write-log* nil))
       (handler-case
           (let ((result (progn ,@body)))
             (%rt-stm-commit)
             (return result))
         (rt-stm-conflict () (sleep 0.001))
         (rt-stm-retry () (sleep 0.001))))))
(defun rt-retry () (error 'rt-stm-retry))
(defun rt-tvar-value-unsafe (tv) (rt-tvar-value tv))
