;;;; Synchronization Primitives (FR-370-373)
(in-package :cl-cc/runtime)
(defstruct rt-mutex (name nil) (host-mutex #+sbcl (sb-thread:make-mutex) #-sbcl nil) (owner nil) (recursive-p nil))
(defun rt-make-mutex (&key name recursive-p) (make-rt-mutex :name name :recursive-p recursive-p))
(defun rt-mutex-lock (m &key timeout)
  #+sbcl (progn (when timeout (sb-thread:grab-mutex (rt-mutex-host-mutex m) :timeout timeout)) (unless timeout (sb-thread:grab-mutex (rt-mutex-host-mutex m)) t))
  #-sbcl t)
(defun rt-mutex-unlock (m) #+sbcl (sb-thread:release-mutex (rt-mutex-host-mutex m)) #-sbcl t)
(defmacro rt-with-mutex ((m &key timeout) &body body) `(unwind-protect (progn (rt-mutex-lock ,m :timeout ,timeout) ,@body) (rt-mutex-unlock ,m)))
(defstruct rt-condition-variable (name nil) #+sbcl (waitqueue (sb-thread:make-waitqueue)) #-sbcl (waiting nil))
(defun rt-make-condition-variable (&key name) (make-rt-condition-variable :name name))
(defun rt-condition-wait (cv m &key timeout) #+sbcl (sb-thread:condition-wait (rt-condition-variable-waitqueue cv) (rt-mutex-host-mutex m) :timeout (or timeout 1e6)) #-sbcl t)
(defun rt-condition-notify (cv) #+sbcl (sb-thread:condition-notify (rt-condition-variable-waitqueue cv)) #-sbcl t)
(defun rt-condition-notify-all (cv) #+sbcl (sb-thread:condition-broadcast (rt-condition-variable-waitqueue cv)) #-sbcl t)
(defstruct rt-semaphore (name nil) (count 0) (m (rt-make-mutex)) (c (rt-make-condition-variable)))
(defun rt-make-semaphore (&key name count) (make-rt-semaphore :name name :count count))
(defun rt-semaphore-wait (s &key timeout) (rt-with-mutex ((rt-semaphore-m s) :timeout timeout) (loop while (<= (rt-semaphore-count s) 0) do (rt-condition-wait (rt-semaphore-c s) (rt-semaphore-m s))) (decf (rt-semaphore-count s)) t))
(defun rt-semaphore-signal (s &optional (n 1)) (rt-with-mutex ((rt-semaphore-m s)) (incf (rt-semaphore-count s) n) (dotimes (i n) (rt-condition-notify (rt-semaphore-c s))) (rt-semaphore-count s)))
(defstruct rt-barrier (name nil) (count 0) (total 0) (gen 0) (m (rt-make-mutex)) (c (rt-make-condition-variable)))
(defun rt-make-barrier (n &key name) (make-rt-barrier :name name :total n))
(defun rt-barrier-wait (b &key timeout) (rt-with-mutex ((rt-barrier-m b) :timeout timeout) (let ((g (rt-barrier-gen b))) (incf (rt-barrier-count b)) (if (= (rt-barrier-count b) (rt-barrier-total b)) (progn (setf (rt-barrier-count b) 0) (incf (rt-barrier-gen b)) (rt-condition-notify-all (rt-barrier-c b)) t) (progn (loop while (= g (rt-barrier-gen b)) do (rt-condition-wait (rt-barrier-c b) (rt-barrier-m b) :timeout timeout)) nil)))))
(defstruct rt-once (done-p nil) (m (rt-make-mutex)))
(defun rt-make-once () (make-rt-once))
(defun rt-once-call (o fn) (rt-with-mutex ((rt-once-m o)) (unless (rt-once-done-p o) (setf (rt-once-done-p o) (cons t (funcall fn))))) (cdr (rt-once-done-p o)))
(defun rt-sync-init () t)
