;;;; Structured Concurrency / Task Groups (FR-280)
(in-package :cl-cc/runtime)
(defstruct rt-task-group
  (tasks nil) (errors nil) (cancelled-p nil) (parent nil)
  (mutex (rt-make-mutex)) (done (rt-make-condition-variable)))
(defvar *rt-current-task-group* nil)
(defun %rt-task-group-collect-errors (group task)
  (when (eq (rt-green-thread-status task) :failed)
    (push (rt-green-thread-error task) (rt-task-group-errors group))
    (setf (rt-task-group-cancelled-p group) t))
  (rt-task-group-errors group))

(defun rt-task-group-add (group task)
  (rt-with-mutex ((rt-task-group-mutex group))
    (push task (rt-task-group-tasks group))
    (when (rt-task-group-cancelled-p group)
      (funcall (symbol-function 'rt-task-cancel) task)))
  task)

(defun rt-task-group-cancel (group)
  (rt-with-mutex ((rt-task-group-mutex group))
    (setf (rt-task-group-cancelled-p group) t)
    (dolist (task (rt-task-group-tasks group))
      (funcall (symbol-function 'rt-task-cancel) task))
    (rt-condition-notify-all (rt-task-group-done group)))
  group)

(defun rt-task-group-wait (group &key timeout)
  (dolist (task (copy-list (rt-task-group-tasks group)))
    (loop while (member (rt-green-thread-status task) '(:ready :running :sleeping))
          do (if timeout (sleep (min 0.001 timeout)) (sleep 0.001)))
    (%rt-task-group-collect-errors group task))
  (rt-task-group-errors group))

(defmacro rt-with-task-group ((&key cancel-on-error) &body body)
  (let ((g (gensym "GROUP")))
    `(let* ((,g (make-rt-task-group :parent *rt-current-task-group*))
            (*rt-current-task-group* ,g))
       (handler-case
           (progn ,@body)
         (error (c)
           (push c (rt-task-group-errors ,g))
           ,(when cancel-on-error `(rt-task-group-cancel ,g))))
       (rt-task-group-wait ,g)
       ,g)))

(defun rt-task-cancel (task)
  (setf (rt-green-thread-cancelled-p task) t
        (rt-green-thread-status task) :cancelled))
(defun rt-task-cancelled-p (task) (rt-green-thread-cancelled-p task))
(defun rt-task-result (task)
  (values (rt-green-thread-result task) (rt-green-thread-error task) (rt-green-thread-status task)))
(defun rt-task-group-errors-list (group) (copy-list (rt-task-group-errors group)))
