;;;; cli/src/handlers-repl.lisp — REPL Handler and Helpers
;;; Generated by splitting handlers.lisp into domain-specific modules.

(in-package :cl-cc/cli)

(defun %count-parens (str)
  "Count top-level parentheses in STR while ignoring parentheses in strings.

Returns two values: the number of opening parentheses and the number of closing
parentheses observed outside string literals. Backslash escapes are honored
inside strings for REPL input balancing."
  (let ((open 0)
        (close 0)
        (in-string nil)
        (escaped nil))
    (loop for c across str do
      (cond
        (escaped (setf escaped nil))
        ((and (not in-string) (char= c #\\)) (setf escaped t))
        ((char= c #\") (setf in-string (not in-string)))
        ((not in-string)
         (cond ((char= c #\() (incf open))
               ((char= c #\)) (incf close))))))
    (values open close)))

(defun %repl-special-symbol (name)
  (intern name (find-package :cl-user)))

(defun %repl-set-global (name value)
  "Set REPL global NAME to VALUE in both compiler and VM persistent state."
  (cl-cc:%ensure-repl-state)
  (let ((symbol (%repl-special-symbol name)))
    (setf (gethash symbol cl-cc/repl::*repl-global-vars-persistent*) t)
    (setf (gethash symbol (cl-cc/vm:vm-global-vars cl-cc/repl::*repl-vm-state*)) value)
    value))

(defun %repl-global (name &optional default)
  (cl-cc:%ensure-repl-state)
  (multiple-value-bind (value found-p)
      (gethash (%repl-special-symbol name)
               (cl-cc/vm:vm-global-vars cl-cc/repl::*repl-vm-state*))
    (if found-p value default)))

(defun %initialize-repl-completeness-globals ()
  "Initialize ANSI REPL history and interactive stream variables."
  (dolist (entry `(("*" nil) ("**" nil) ("***" nil)
                   ("+" nil) ("++" nil) ("+++" nil)
                   ("/" nil) ("//" nil) ("///" nil)
                   ("*TERMINAL-IO*" ,*terminal-io*)
                   ("*QUERY-IO*" ,*query-io*)
                   ("*DEBUG-IO*" ,*debug-io*)))
    (%repl-set-global (first entry) (second entry))))

(defun %update-repl-completeness-globals (form values-list)
  "Update *, **, ***, +, ++, +++, /, //, /// after evaluating FORM."
  (let ((previous-* (%repl-global "*"))
        (previous-** (%repl-global "**"))
        (previous-+ (%repl-global "+"))
        (previous-++ (%repl-global "++"))
        (previous-/ (%repl-global "/"))
        (previous-// (%repl-global "//")))
    (%repl-set-global "***" previous-**)
    (%repl-set-global "**" previous-*)
    (%repl-set-global "*" (first values-list))
    (%repl-set-global "+++" previous-++)
    (%repl-set-global "++" previous-+)
    (%repl-set-global "+" form)
    (%repl-set-global "///" previous-//)
    (%repl-set-global "//" previous-/)
    (%repl-set-global "/" values-list)))

(defun %repl-history-file ()
  (merge-pathnames #P".cl-cc_history" (user-homedir-pathname)))

(defun %load-repl-history-file ()
  "Load ~/.cl-cc_history into the in-memory REPL history ring."
  (let ((path (%repl-history-file)))
    (when (probe-file path)
      (with-open-file (in path :direction :input)
        (loop for line = (read-line in nil nil)
              while line do
                (cl-cc:%repl-record-history line))))))

(defun %save-repl-history-file ()
  "Save the current REPL history to ~/.cl-cc_history."
  (let ((path (%repl-history-file)))
    (ensure-directories-exist path)
    (with-open-file (out path :direction :output :if-exists :supersede :if-does-not-exist :create)
      (dolist (entry (cl-cc/repl:repl-history))
        (write-line entry out)))))

(defun %repl-inspect (expr)
  "Evaluate EXPR and print object type plus slot/container details."
  (let ((object (cl-cc:run-string-repl expr)))
    (format t "Type: ~S~%" (type-of object))
    (cond
      ((hash-table-p object)
       (format t "Hash table count: ~D~%" (hash-table-count object))
       (maphash (lambda (k v) (format t "  ~S => ~S~%" k v)) object))
      ((standard-object-p object)
       (format t "Object: ~S~%" object)
       (describe object *standard-output*))
      (t
       (format t "Value: ~S~%" object)))
    (force-output)))

(defun %repl-describe (expr)
  "Describe a symbol or evaluated object and print available documentation."
  (let* ((form (read-from-string expr nil nil))
         (object (if (symbolp form) form (cl-cc:run-string-repl expr))))
    (format t "~&~S~%" object)
    (when (symbolp object)
      (dolist (kind '(function variable type))
        (let ((doc (documentation object kind)))
          (when doc
            (format t "~A documentation:~%~A~%" kind doc)))))
    (describe object *standard-output*)
    (force-output)))

(defun %do-repl (parsed)
  "Handle the `cl-cc repl' subcommand using PARSED arguments.

Resets persistent REPL state, optionally preloads the standard library, reads
balanced forms from *STANDARD-INPUT*, evaluates them through RUN-STRING-REPL,
prints non-NIL results, and exits cleanly on EOF or quit commands."
  (let ((stdlib (flag parsed "--stdlib"))
        (no-stdlib (flag parsed "--no-stdlib"))
        (timeout (%get-timeout parsed))
        (watch (flag parsed "--watch"))
        (watch-file (car (parsed-args-positional parsed))))
    (cl-cc:reset-repl-state)
    (cl-cc:%ensure-repl-state)
    (%initialize-repl-completeness-globals)
    (%load-repl-history-file)
    (when stdlib
      (handler-case (cl-cc:run-string-repl cl-cc:*standard-library-source*)
        (error () nil)))
    (when (and watch watch-file)
      (let ((source (%read-command-source watch-file)))
        (%record-hot-reload-source watch-file source nil)
        (%start-watch-file-poll-thread watch-file cl-cc/repl::*repl-vm-state*)))
    (format t "CL-CC ~A  —  ANSI Common Lisp~%" *version*)
    (format t "Type a CL form and press Return. (exit) or Ctrl+D to quit.~%~%")
    (force-output)
    (let ((stdlib-loaded-p stdlib))
       (flet ((eval-and-print (form)
              (let* ((*terminal-io* *terminal-io*)
                     (*query-io* *query-io*)
                     (*debug-io* *debug-io*)
                     (result (handler-case (cl-cc:run-string-repl form)
                               (error (e)
                                 (if (or no-stdlib stdlib-loaded-p)
                                     (error e)
                                     (progn
                                       (cl-cc:run-string-repl cl-cc:*standard-library-source*)
                                       (setf stdlib-loaded-p t)
                                       (cl-cc:run-string-repl form))))))
                     (values-list (or (cl-cc/vm:vm-values-list cl-cc/repl::*repl-vm-state*)
                                      (list result))))
                 (%update-repl-completeness-globals form values-list)
                 (when (not (null result))
                   (format t "=> ~S~%" result))
                 (force-output))))
      (loop
        (format t "* ")
        (force-output)
        (let ((buffer ""))
          (loop
            (let ((line (handler-case (read-line *standard-input* nil nil)
                          (error () nil))))
              (when (null line)
                (%save-repl-history-file)
                (format t "~%Goodbye.~%")
                (uiop:quit 0))
              (multiple-value-bind (edited-line candidates edited-p)
                  (cl-cc:repl-edit-input-line line)
                (declare (ignore edited-p))
                (when candidates
                  (format t "; Completions: ~{~A~^ ~}~%" candidates)
                  (force-output))
                (setf line edited-line))
              (setf buffer (if (string= buffer "")
                                line
                                (concatenate 'string buffer " " line)))
              (multiple-value-bind (open close) (%count-parens buffer)
                (when (>= close open)
                  (return)))))
          (let ((trimmed (string-trim '(#\Space #\Tab #\Newline) buffer)))
            (cond
              ((string= trimmed "") nil)
               ((or (string= trimmed "(exit)")
                    (string= trimmed ":quit")
                    (string= trimmed ":q"))
                (%save-repl-history-file)
                (format t "Goodbye.~%")
                (uiop:quit 0))
               ((uiop:string-prefix-p ":inspect " trimmed)
                (handler-case
                    (%repl-inspect (string-trim '(#\Space #\Tab) (subseq trimmed 9)))
                  (error (e) (format t "; Error: ~A~%" e))))
               ((uiop:string-prefix-p ":describe " trimmed)
                (handler-case
                    (%repl-describe (string-trim '(#\Space #\Tab) (subseq trimmed 10)))
                  (error (e) (format t "; Error: ~A~%" e))))
               (t
               (cl-cc:%repl-record-history trimmed)
                (handler-case
                    (if timeout
                        (handler-case
                            (sb-ext:with-timeout timeout
                              (eval-and-print trimmed))
                          (sb-ext:timeout (c)
                            (declare (ignore c))
                            (format t "; Timeout after ~A second~:P~%" timeout)
                            (force-output)))
                        (eval-and-print trimmed))
                  (error (e)
                    (format t "; Error: ~A~%" e)
                     (force-output))))))))))))
