;;;; cli/src/handlers-run.lisp — Run CLI Handler
;;; Generated by splitting handlers.lisp into domain-specific modules.

(in-package :cl-cc/cli)

(defun %do-run (parsed)
  "Handle the `cl-cc run' subcommand using PARSED command-line arguments.

Reads the required input file, detects Lisp or PHP mode, compiles to the VM,
executes the program, optionally emits trace/flamegraph/PGO artifacts, and
exits with status 0 on success."
  (let* ((file (%required-file-arg parsed "run"))
         (lang-flag (or (flag parsed "--lang") ""))
         (language (%detect-language file lang-flag))
         (stdlib (flag parsed "--stdlib"))
          (verbose (flag parsed "--verbose"))
          (timeout (%get-timeout parsed))
          (opts (%parse-compile-opts parsed))
           (core-path (flag parsed "--core"))
           (source (%read-command-source file))
           (no-stdlib (flag parsed "--no-stdlib")))
    (when verbose
      (format *error-output* "; cl-cc run: ~A  lang=~A  stdlib=~A~%"
              file language (if stdlib "yes" "no")))
     (%with-cli-error-handler
       (%call-with-cli-timeout timeout
        (lambda ()
          (when core-path
            (cl-cc/runtime:rt-load-core core-path))
          (%call-with-optional-output-file
          (compile-opts-trace-json-path opts)
          (lambda (stream)
            (let* ((vm-state (%maybe-make-profiled-vm-state opts))
                   (kwargs (%compile-opts-kwargs opts stream)))
              (cond
                ((eq language :lisp)
                  (let ((result (%compile-lisp-with-auto-stdlib source kwargs stdlib no-stdlib)))
                    (%bind-command-line-arguments (%script-argv-from-parsed parsed) vm-state)
                    (let ((ret (%run-compiled-result result vm-state opts)))
                      (%record-hot-reload-source file source ret)
                      (%maybe-write-pgo-profile opts result vm-state)
                      (if watch
                          (%watch-file-poll file vm-state)
                          ret))))
                ((eq language :php)
                  (let ((result (apply #'compile-string source :target :vm :language :php kwargs)))
                    (%bind-command-line-arguments (%script-argv-from-parsed parsed) vm-state)
                    (let ((ret (%run-compiled-result result vm-state opts)))
                      (%maybe-write-pgo-profile opts result vm-state)
                      ret)))
                  (t
                   (let ((result (apply #'compile-string source :target :vm kwargs)))
                    (%bind-command-line-arguments (%script-argv-from-parsed parsed) vm-state)
                    (let ((ret (%run-compiled-result result vm-state opts)))
                      (%maybe-write-pgo-profile opts result vm-state)
                      (if watch
                          (%watch-file-poll file vm-state)
                          ret)))))
              (uiop:quit 0)))))
       "run"))))
