;;;; lsp-server.lisp -- JSON-RPC/LSP 3.17 stdio server (FR-760).

(cl:in-package :cl-cc/tools/lsp)

(defvar *lsp-enabled* nil
  "When non-NIL, the LSP server accepts JSON-RPC over stdio.")

(defstruct (lsp-server (:constructor make-lsp-server (&key)))
  (documents (make-hash-table :test #'equal) :type hash-table)
  (symbols (make-hash-table :test #'equal) :type hash-table)
  (shutdown-requested-p nil :type boolean)
  (running-p nil :type boolean))

(defun %assoc= (key alist)
  (cdr (assoc key alist :test #'string=)))

(defun %json-whitespace-p (ch)
  (find ch '(#\Space #\Tab #\Newline #\Return)))

(defun %json-escape (string)
  (with-output-to-string (out)
    (loop for ch across (princ-to-string string) do
      (case ch
        (#\\ (write-string "\\\\" out))
        (#\" (write-string "\\\"" out))
        (#\Newline (write-string "\\n" out))
        (#\Return (write-string "\\r" out))
        (#\Tab (write-string "\\t" out))
        (t (write-char ch out))))))

(defun %json-object-p (value)
  (and (listp value)
       (or (null value)
           (every (lambda (entry)
                    (and (consp entry) (stringp (car entry))))
                  value))))

(defun encode-json (value &optional (stream nil stream-p))
  "Encode VALUE as JSON. Alists with string keys are objects; other lists are arrays."
  (let ((out (or stream (make-string-output-stream))))
    (labels ((emit (v)
               (cond
                 ((eq v :true) (write-string "true" out))
                 ((eq v :false) (write-string "false" out))
                 ((null v) (write-string "null" out))
                 ((stringp v) (format out "\"~A\"" (%json-escape v)))
                 ((numberp v) (princ v out))
                 ((symbolp v) (format out "\"~A\"" (%json-escape (symbol-name v))))
                 ((%json-object-p v)
                  (write-char #\{ out)
                  (loop for (k . val) in v
                        for first = t then nil do
                          (unless first (write-char #\, out))
                          (format out "\"~A\":" (%json-escape k))
                          (emit val))
                  (write-char #\} out))
                 ((listp v)
                  (write-char #\[ out)
                  (loop for item in v
                        for first = t then nil do
                          (unless first (write-char #\, out))
                          (emit item))
                  (write-char #\] out))
                 (t (format out "\"~A\"" (%json-escape (princ-to-string v)))))))
      (emit value)
      (if stream-p
          value
          (get-output-stream-string out)))))

(defun parse-json (text)
  "Parse the JSON subset needed by JSON-RPC/LSP into alists, lists, strings, numbers and :TRUE/:FALSE."
  (let ((pos 0)
        (len (length text)))
    (labels ((peek () (and (< pos len) (char text pos)))
             (next () (prog1 (peek) (incf pos)))
             (skip-ws () (loop while (and (peek) (%json-whitespace-p (peek))) do (incf pos)))
             (expect (ch)
               (skip-ws)
               (unless (and (peek) (char= (next) ch))
                 (error "Expected JSON character ~S near offset ~D" ch pos)))
             (parse-string ()
               (expect #\")
               (with-output-to-string (out)
                 (loop for ch = (next) do
                   (cond
                     ((null ch) (error "Unterminated JSON string"))
                     ((char= ch #\") (return))
                     ((char= ch #\\)
                      (let ((esc (next)))
                        (case esc
                          (#\n (write-char #\Newline out))
                          (#\r (write-char #\Return out))
                          (#\t (write-char #\Tab out))
                          (#\" (write-char #\" out))
                          (#\\ (write-char #\\ out))
                          (#\/ (write-char #\/ out))
                          (t (write-char esc out)))))
                     (t (write-char ch out))))))
             (parse-number ()
               (let ((start pos))
                 (when (char= (peek) #\-) (incf pos))
                 (loop while (and (peek) (digit-char-p (peek))) do (incf pos))
                 (when (and (peek) (char= (peek) #\.))
                   (incf pos)
                   (loop while (and (peek) (digit-char-p (peek))) do (incf pos)))
                 (read-from-string (subseq text start pos))))
             (parse-literal (literal value)
               (unless (and (<= (+ pos (length literal)) len)
                            (string= literal text :start2 pos :end2 (+ pos (length literal))))
                 (error "Expected JSON literal ~A near offset ~D" literal pos))
               (incf pos (length literal))
               value)
             (parse-array ()
               (expect #\[)
               (skip-ws)
               (let ((items nil))
                 (unless (and (peek) (char= (peek) #\]))
                   (loop do (push (parse-value) items)
                            (skip-ws)
                         while (and (peek) (char= (peek) #\,)) do (incf pos)))
                 (expect #\])
                 (nreverse items)))
             (parse-object ()
               (expect #\{)
               (skip-ws)
               (let ((items nil))
                 (unless (and (peek) (char= (peek) #\}))
                   (loop do (let ((key (parse-string)))
                              (expect #\:)
                              (push (cons key (parse-value)) items))
                            (skip-ws)
                         while (and (peek) (char= (peek) #\,)) do (incf pos)))
                 (expect #\})
                 (nreverse items)))
             (parse-value ()
               (skip-ws)
               (case (peek)
                 (#\{ (parse-object))
                 (#\[ (parse-array))
                 (#\" (parse-string))
                 (#\t (parse-literal "true" :true))
                 (#\f (parse-literal "false" :false))
                 (#\n (parse-literal "null" nil))
                 (otherwise (parse-number)))))
      (prog1 (parse-value) (skip-ws)))))

(defun write-jsonrpc-message (stream payload)
  "Write PAYLOAD as a Content-Length framed JSON-RPC message."
  (let* ((json (encode-json payload))
         (length (length json)))
    (format stream "Content-Length: ~D~C~C~C~C" length #\Return #\Newline #\Return #\Newline)
    (write-string json stream)
    (force-output stream)
    payload))

(defun read-jsonrpc-message (&optional (stream *standard-input*))
  "Read one Content-Length framed JSON-RPC message from STREAM."
  (let ((content-length nil))
    (loop for line = (read-line stream nil nil)
          while line do
            (let ((trimmed (string-right-trim '(#\Return #\Newline) line)))
              (when (string= trimmed "") (return))
              (let ((colon (position #\: trimmed)))
                (when (and colon (string-equal "Content-Length" trimmed :end2 colon))
                  (setf content-length
                        (parse-integer (string-trim '(#\Space #\Tab)
                                                    (subseq trimmed (1+ colon)))))))))
    (unless content-length
      (error "Missing Content-Length header"))
    (let ((buffer (make-string content-length)))
      (read-sequence buffer stream)
      (parse-json buffer))))

(defun %count-parens (text)
  (let ((open 0) (close 0) (in-string nil) (escaped nil))
    (loop for ch across (or text "") do
      (cond
        (escaped (setf escaped nil))
        ((and in-string (char= ch #\\)) (setf escaped t))
        ((char= ch #\") (setf in-string (not in-string)))
        ((not in-string)
         (cond ((char= ch #\() (incf open))
               ((char= ch #\)) (incf close))))))
    (values open close)))

(defun %offset-line-character (text offset)
  (let ((line 0) (character 0))
    (loop for i below (min offset (length text))
          for ch = (char text i) do
            (if (char= ch #\Newline)
                (setf line (1+ line) character 0)
                (incf character)))
    (values line character)))

(defun %line-character-offset (text line character)
  (let ((current-line 0) (current-character 0))
    (loop for i from 0 below (length text)
          for ch = (char text i) do
            (when (and (= current-line line) (= current-character character))
              (return-from %line-character-offset i))
            (if (char= ch #\Newline)
                (setf current-line (1+ current-line) current-character 0)
                (incf current-character)))
    (length text)))

(defun %word-at (text line character)
  (let* ((offset (%line-character-offset text line character))
         (start (loop for i downfrom (min offset (1- (length text))) to 0
                      while (let ((ch (char text i)))
                              (or (alphanumericp ch) (find ch '(#\- #\* #\+ #\/ #\< #\> #\= #\? #\!))))
                      finally (return (1+ i))))
         (end (loop for i from offset below (length text)
                    while (let ((ch (char text i)))
                            (or (alphanumericp ch) (find ch '(#\- #\* #\+ #\/ #\< #\> #\= #\? #\!))))
                    finally (return i))))
    (subseq text start end)))

(defun %scan-document-symbols (uri text)
  (let ((symbols nil) (offset 0))
    (loop
      (multiple-value-bind (form end) (ignore-errors (read-from-string text nil nil :start offset))
        (unless form (return))
        (when (and (consp form)
                   (member (car form) '(defun defvar defparameter defclass defgeneric defmacro defconstant) :test #'eq)
                   (symbolp (second form)))
          (multiple-value-bind (line char) (%offset-line-character text offset)
            (push `(("name" . ,(string-downcase (symbol-name (second form))))
                    ("kind" . 12)
                    ("location" . (("uri" . ,uri)
                                    ("range" . (("start" . (("line" . ,line) ("character" . ,char)))
                                                 ("end" . (("line" . ,line) ("character" . ,(+ char 1)))))))))
                  symbols)))
        (setf offset end)))
    (nreverse symbols)))

(defun lsp-open-document (server uri text)
  "Open or replace URI in SERVER and refresh its symbol index."
  (setf (gethash uri (lsp-server-documents server)) text
        (gethash uri (lsp-server-symbols server)) (%scan-document-symbols uri text))
  text)

(defun %diagnostics-for-source (uri text)
  (declare (ignore uri))
  (let ((diagnostics nil))
    (multiple-value-bind (open close) (%count-parens text)
      (when (/= open close)
        (push `(("range" . (("start" . (("line" . 0) ("character" . 0)))
                             ("end" . (("line" . 0) ("character" . 1)))))
                ("severity" . 1)
                ("source" . "cl-cc")
                ("message" . ,(format nil "Unbalanced parentheses: ~D open, ~D close" open close)))
              diagnostics)))
    (handler-case
        (progn (cl-cc:compile-string text :target :vm :language :lisp) nil)
      (error (e)
        (unless diagnostics
          (push `(("range" . (("start" . (("line" . 0) ("character" . 0)))
                               ("end" . (("line" . 0) ("character" . 1)))))
                  ("severity" . 1)
                  ("source" . "cl-cc")
                  ("message" . ,(princ-to-string e)))
                diagnostics))))
    (nreverse diagnostics)))

(defun lsp-publish-diagnostics (server uri)
  "Return a textDocument/publishDiagnostics notification for URI."
  (let* ((text (gethash uri (lsp-server-documents server)))
         (diagnostics (%diagnostics-for-source uri (or text ""))))
    `(("jsonrpc" . "2.0")
      ("method" . "textDocument/publishDiagnostics")
      ("params" . (("uri" . ,uri) ("diagnostics" . ,diagnostics))))))

(defun %response (id result)
  `(("jsonrpc" . "2.0") ("id" . ,id) ("result" . ,result)))

(defun %empty-response (id)
  (%response id nil))

(defun %capabilities ()
  '(("capabilities" . (("textDocumentSync" . (("openClose" . :true) ("change" . 1)))
                        ("completionProvider" . (("resolveProvider" . :false)))
                        ("hoverProvider" . :true)
                        ("definitionProvider" . :true)
                        ("workspaceSymbolProvider" . :true)))))

(defun %all-symbols (server)
  (let ((out nil))
    (maphash (lambda (_uri symbols) (declare (ignore _uri)) (setf out (append symbols out)))
             (lsp-server-symbols server))
    out))

(defun %find-symbol-info (server name)
  (find name (%all-symbols server) :key (lambda (s) (%assoc= "name" s)) :test #'string-equal))

(defun lsp-handle-request (server request)
  "Handle one JSON-RPC/LSP REQUEST and return a response or notification alist."
  (let* ((id (%assoc= "id" request))
         (method (%assoc= "method" request))
         (params (%assoc= "params" request)))
    (cond
      ((string= method "initialize") (%response id (%capabilities)))
      ((string= method "shutdown") (setf (lsp-server-shutdown-requested-p server) t) (%empty-response id))
      ((string= method "exit") (setf (lsp-server-running-p server) nil) nil)
      ((string= method "textDocument/didOpen")
       (let* ((doc (%assoc= "textDocument" params))
              (uri (%assoc= "uri" doc))
              (text (%assoc= "text" doc)))
         (lsp-open-document server uri (or text ""))
         (lsp-publish-diagnostics server uri)))
      ((string= method "textDocument/didChange")
       (let* ((doc (%assoc= "textDocument" params))
              (uri (%assoc= "uri" doc))
              (changes (%assoc= "contentChanges" params))
              (text (or (%assoc= "text" (car (last changes))) "")))
         (lsp-open-document server uri text)
         (lsp-publish-diagnostics server uri)))
      ((string= method "textDocument/completion")
       (declare (ignore params))
       (%response id `(("isIncomplete" . :false)
                       ("items" . ,(mapcar (lambda (label) `(("label" . ,label) ("kind" . 3)))
                                            (append '("defun" "defvar" "defparameter" "lambda" "let" "if")
                                                    (mapcar (lambda (s) (%assoc= "name" s)) (%all-symbols server))))))))
      ((string= method "textDocument/hover")
       (let* ((doc (%assoc= "textDocument" params))
              (uri (%assoc= "uri" doc))
              (pos (%assoc= "position" params))
              (text (gethash uri (lsp-server-documents server) ""))
              (word (%word-at text (or (%assoc= "line" pos) 0) (or (%assoc= "character" pos) 0))))
         (%response id `(("contents" . (("kind" . "markdown") ("value" . ,(format nil "`~A`" word))))))))
      ((string= method "textDocument/definition")
       (let* ((doc (%assoc= "textDocument" params))
              (uri (%assoc= "uri" doc))
              (pos (%assoc= "position" params))
              (text (gethash uri (lsp-server-documents server) ""))
              (word (%word-at text (or (%assoc= "line" pos) 0) (or (%assoc= "character" pos) 0)))
              (sym (%find-symbol-info server word)))
         (%response id (and sym (%assoc= "location" sym)))))
      ((string= method "workspace/symbol")
       (let* ((query (or (%assoc= "query" params) ""))
              (symbols (remove-if-not (lambda (s) (search query (%assoc= "name" s) :test #'char-equal))
                                      (%all-symbols server))))
         (%response id symbols)))
      (t (%response id nil)))))

(defun lsp-start (&key (port 0) (input *standard-input*) (output *standard-output*))
  "Start the LSP server. PORT=0 selects stdio mode."
  (declare (ignore port))
  (let ((server (make-lsp-server :running-p t)))
    (loop while (lsp-server-running-p server) do
      (let* ((request (read-jsonrpc-message input))
             (response (lsp-handle-request server request)))
        (when response (write-jsonrpc-message output response))))
    server))

(defun lsp-stop ()
  "Stop the LSP server (stdio mode exits when it receives exit)."
  (setf *lsp-enabled* nil)
  t)
