(in-package :cl-cc/ffi)
(defstruct dl-lib (name "" :type string) (handle nil) (loaded nil))
(defvar *loaded-libs* (make-hash-table :test #'equal))
(defun load-shared-library (path &key (if-not-found :error))
  (let ((ex (gethash path *loaded-libs*))) (when ex (return-from load-shared-library ex)))
  (let ((resolved (or (probe-file path) (probe-file (format nil "~A.dylib" path)) (probe-file (format nil "~A.so" path)) (probe-file (format nil "/usr/lib/~A" path)) (probe-file (format nil "/usr/local/lib/~A" path)))))
    (cond (resolved (let ((lib (make-dl-lib :name path :loaded t))) (setf (gethash path *loaded-libs*) lib) lib)) ((eq if-not-found :error) (error "Library not found: ~S" path)) (t nil))))
(defun load-framework (name) (load-shared-library (format nil "/System/Library/Frameworks/~A.framework/~A" name name)))
(defun unload-shared-library (lib) (setf (dl-lib-loaded lib) nil) (remhash (dl-lib-name lib) *loaded-libs*) (values))
(defun list-loaded-libraries () (loop for lib being the hash-values of *loaded-libs* when (dl-lib-loaded lib) collect (dl-lib-name lib)))
(defun find-foreign-symbol (name lib) (declare (ignore name lib)) (warn "find-foreign-symbol not implemented") nil)
