;;;; packages/engine/vm/src/facade-package.lisp -- cl-cc/vm package definition
;;;;
;;;; VM instruction set subsystem: instruction defstructs, VM state, heap
;;;; operations, I/O, conditions, CLOS dispatch, hash tables, strings, etc.
;;;;
;;;; Extracted as a Phase 2 sibling system (:cl-cc-vm). The package
;;;; facade is loaded first (no dependencies); the umbrella :cl-cc system
;;;; then sets up (use-package :cl-cc :cl-cc/vm) so the source files
;;;; can access all symbols unqualified.

(defpackage :cl-cc/vm
  (:use :cl :cl-cc/bootstrap)
  (:export
   ;; ---- package-exports-2.lisp symbols ----
   #:vm-cons-cell-car
   #:vm-cons-cell-cdr
   #:vm-closure-object
   #:vm-closure-entry-label
   #:vm-closure-params
   #:vm-closure-captured-values
   #:vm-instruction
   #:vm-const
   #:vm-move
   #:vm-binop
   #:vm-add
   #:vm-integer-add
   #:vm-integer-sub
   #:vm-integer-mul
   #:vm-float-add
   #:vm-float-sub
   #:vm-float-mul
   #:vm-float-div
   #:vm-sub
   #:vm-mul
   #:vm-label
   #:vm-jump
   #:vm-jump-zero
   #:vm-print
   #:vm-halt
   #:vm-closure
   #:vm-call
   #:vm-tail-call
   #:vm-ret
   #:vm-func-ref
   #:vm-push
   #:vm-pop
   #:vm-values
   #:vm-spread-values
   #:vm-mv-bind
   #:vm-dst-regs
   #:vm-lcm
   #:vm-gcd
   #:vm-ash
   #:vm-rotate
   #:vm-bswap
   #:vm-logand
   #:vm-logior
   #:vm-logxor
   #:vm-logeqv
   #:vm-logtest
   #:vm-logbitp
   #:vm-logcount
   #:vm-integer-length
   #:vm-min
   #:vm-max
   #:vm-rem
   #:vm-mod
   #:vm-div
   #:vm-truncate
   #:vm-floor-inst
   #:vm-ceiling-inst
   #:vm-round-inst
   #:vm-lognot
   #:vm-rational
   #:vm-rationalize
   #:vm-numerator
   #:vm-denominator
   #:vm-make-array
   #:vm-eq
   #:vm-num-eq
   #:vm-lt
   #:vm-gt
   #:vm-le
   #:vm-ge
   #:vm-and
   #:vm-or
   #:vm-abs
   #:vm-inc
   #:vm-dec
   #:vm-not
   #:vm-concatenate
   #:vm-select
   #:vm-cons-p
   #:vm-symbol-p
   #:vm-number-p
   #:vm-integer-p
   #:vm-function-p
   #:vm-apply
   #:vm-register-function
   #:vm-function-registry
   #:vm-resolve-function
   #:vm-register-host-bridge
   #:*vm-host-bridge-functions*
   #:vm-generic-function-p
   #:vm-resolve-gf-method
   #:vm-set-global
   #:vm-get-global
   #:vm-global-name
   #:vm-global-vars
   #:vm-values-list
   #:vm-establish-handler
   #:vm-remove-handler
   #:vm-signal-error
   #:vm-sync-handler-regs
   #:vm-handler-label
   #:vm-handler-result-reg
   #:vm-error-type
   #:vm-error-reg
   #:vm-establish-catch
   #:vm-throw
   #:vm-catch-tag-reg
   #:vm-catch-handler-label
   #:vm-catch-result-reg
   #:vm-throw-tag-reg
   #:vm-throw-value-reg
   #:vm-handler-stack
   #:make-vm-instruction
   #:make-vm-abs
   #:make-vm-acons
   #:make-vm-add
   #:make-vm-alpha-char-p
   #:make-vm-integer-add
   #:make-vm-integer-sub
   #:make-vm-integer-mul
   #:make-vm-float-add
   #:make-vm-float-sub
   #:make-vm-float-mul
   #:make-vm-float-div
   #:make-vm-alphanumericp
   #:make-vm-and
   #:make-vm-append
   #:make-vm-apply
   #:make-vm-adjust-array
   #:make-vm-aref
   #:make-vm-aref-multi
   #:vm-aref-multi
   #:make-vm-array-length
   #:make-vm-aset
   #:make-vm-assoc
   #:make-vm-array-adjustable-p
   #:make-vm-array-dimension
   #:make-vm-array-dimensions
   #:make-vm-array-displacement
   #:make-vm-array-has-fill-pointer-p
   #:make-vm-array-rank
   #:make-vm-array-row-major-index
   #:make-vm-array-total-size
   #:make-vm-atom
   #:make-vm-binop
   #:make-vm-bit-access
   #:make-vm-bit-and
   #:make-vm-bit-not
   #:make-vm-bit-or
   #:make-vm-bit-set
   #:make-vm-bit-xor
   #:make-vm-butlast
   #:make-vm-sbit
   #:make-vm-call
   #:make-vm-tail-call
   #:make-vm-call-next-method
   #:make-vm-car
   #:make-vm-cdr
   #:make-vm-ceiling-inst
   #:make-vm-char
   #:make-vm-char-code
   #:make-vm-char-downcase
   #:make-vm-char-not-greaterp
   #:make-vm-char-not-lessp
   #:make-vm-char-upcase
   #:make-vm-char<
   #:make-vm-char=
   #:make-vm-characterp
   #:make-vm-class-def
   #:make-vm-close-file
   #:make-vm-closure
   #:make-vm-closure-ref-idx
   #:make-vm-clrhash
   #:make-vm-code-char
   #:make-vm-coerce-to-list
   #:make-vm-coerce-to-string
   #:make-vm-coerce-to-vector
   #:make-vm-clear-values
   #:make-vm-concatenate
   #:make-vm-cons
   #:make-vm-cons-p
   #:make-vm-const
   #:make-vm-complex
   #:make-vm-conjugate
   #:make-vm-copy-list
   #:make-vm-copy-tree
   #:make-vm-dec
   #:make-vm-denominator
   #:make-vm-digit-char-p
   #:make-vm-digit-char
   #:make-vm-both-case-p
   #:make-vm-graphic-char-p
   #:make-vm-standard-char-p
   #:make-vm-char-name
   #:make-vm-name-char
   #:make-vm-div
   #:make-vm-cl-div
   #:vm-cl-div
   #:make-vm-endp
   #:make-vm-eof-p
   #:make-vm-eq
   #:make-vm-equal
   #:make-vm-establish-handler
   #:make-vm-establish-catch
   #:make-vm-ensure-values
   #:make-vm-eval
   #:make-vm-macroexpand-1-inst
   #:make-vm-macroexpand-inst
   #:vm-macroexpand-1-inst
   #:vm-macroexpand-inst
   #:make-vm-sxhash
   #:vm-sxhash
   #:make-vm-class-name-fn
   #:make-vm-class-of-fn
   #:make-vm-find-class
   #:vm-class-name-fn
   #:vm-class-of-fn
   #:vm-find-class
   #:make-vm-evenp
   #:make-vm-fceiling
   #:make-vm-ffloor
   #:make-vm-fifth
   #:make-vm-sixth
   #:make-vm-seventh
   #:make-vm-eighth
   #:make-vm-ninth
   #:make-vm-tenth
   #:make-vm-file-length
   #:make-vm-fill-pointer-inst
   #:make-vm-file-position
   #:make-vm-first
   #:make-vm-floor-inst
   #:make-vm-fdefinition
   #:make-vm-fmakunbound
   #:make-vm-format-inst
   #:make-vm-fourth
   #:make-vm-fround
   #:make-vm-fresh-line-inst
   #:make-vm-ftruncate
   #:make-vm-func-ref
   #:make-vm-function-p
   #:make-vm-ge
   #:make-vm-generic-call
   #:make-vm-select
   #:make-vm-generic-add
   #:make-vm-generic-sub
   #:make-vm-generic-mul
   #:make-vm-generic-div
   #:make-vm-generic-eq
   #:make-vm-generic-lt
   #:make-vm-generic-gt
   #:vm-generic-add
   #:vm-generic-sub
   #:vm-generic-mul
   #:vm-generic-div
   #:vm-generic-eq
   #:vm-generic-lt
   #:vm-generic-gt
   #:make-vm-gensym-inst
   #:make-vm-get-global
   #:make-vm-get-output-stream-string-inst
   #:make-vm-get-string-from-stream
   #:make-vm-get-universal-time
   #:make-vm-get-internal-real-time
   #:make-vm-get-internal-run-time
   #:make-vm-decode-universal-time
   #:make-vm-encode-universal-time
   #:make-vm-lisp-implementation-type
   #:make-vm-lisp-implementation-version
   #:make-vm-machine-type
   #:make-vm-machine-version
   #:make-vm-machine-instance
   #:make-vm-software-type
   #:make-vm-software-version
   #:make-vm-short-site-name
   #:make-vm-long-site-name
   #:make-vm-gcd
   #:make-vm-gethash
   #:make-vm-gt
   #:make-vm-halt
   #:make-vm-hash-table-count
   #:make-vm-hash-table-keys
   #:make-vm-hash-table-p
   #:make-vm-hash-table-test
   #:make-vm-hash-table-values
   #:make-vm-hash-table-size
   #:make-vm-hash-table-rehash-size
   #:make-vm-hash-table-rehash-threshold
   #:make-vm-inc
   #:make-vm-integer-p
   #:make-vm-imagpart
   #:make-vm-intern-symbol
   #:make-vm-jump
   #:make-vm-jump-zero
   #:make-vm-keywordp
   #:make-vm-label
   #:make-vm-last
   #:make-vm-lcm
   #:make-vm-le
   #:make-vm-length
   #:make-vm-list-length
   #:make-vm-listp
   #:make-vm-lower-case-p
   #:make-vm-lt
   #:make-vm-make-array
   #:make-vm-make-closure
   #:make-vm-make-hash-table
   #:make-vm-make-list
   #:make-vm-make-obj
   #:make-vm-make-string-output-stream-inst
   #:make-vm-make-string-stream
   #:make-vm-make-symbol
   #:make-vm-max
   #:make-vm-member
   #:make-vm-min
   #:make-vm-mod
   #:make-vm-move
   #:make-vm-mul
   #:make-vm-mv-bind
   #:make-vm-makunbound
   #:make-vm-nconc
   #:make-vm-nreconc
   #:make-vm-nbutlast
   #:make-vm-neg
   #:make-vm-not
   #:make-vm-nreverse
   #:make-vm-nth
   #:make-vm-numerator
   #:make-vm-identity
   #:make-vm-constantly
   #:make-vm-complement
   #:make-vm-next-method-p
   #:make-vm-nthcdr
   #:make-vm-null
   #:make-vm-null-p
   #:make-vm-num-eq
   #:make-vm-number-p
   #:make-vm-oddp
   #:make-vm-open-file
   #:make-vm-or
   ;; ---- package-exports-3.lisp symbols ----
   #:make-vm-parse-integer
   #:make-vm-peek-char
   #:make-vm-phase
   #:make-vm-pop
   #:make-vm-progv-enter
   #:make-vm-progv-exit
   #:make-vm-prin1
   #:make-vm-prin1-sexp
   #:make-vm-princ
   #:make-vm-princ-sexp
   #:make-vm-print
   #:make-vm-print-inst
   #:make-vm-print-sexp
   #:make-vm-push
   #:make-vm-read-char
   #:make-vm-read-from-string-inst
   #:make-vm-read-from-string-rp
   #:make-vm-read-line
   #:make-vm-read-sexp
   #:make-vm-read-sexp-inst
   #:make-vm-reader-advance-rp
   #:make-vm-reader-peek-rp
   #:make-vm-reader-read
   #:make-vm-register-function
   #:make-vm-register-method
   #:make-vm-rational
   #:make-vm-rationalize
   #:make-vm-realpart
   #:make-vm-random
   #:make-vm-make-random-state
   #:make-vm-rem
   #:make-vm-remhash
   #:make-vm-remove-handler
   #:make-vm-remprop
   #:make-vm-rest
   #:make-vm-row-major-aref
   #:make-vm-ret
   #:make-vm-reverse
   #:make-vm-rplaca
   #:make-vm-rplacd
   #:make-vm-search-string
   #:make-vm-second
   #:make-vm-set-global
   #:make-vm-sethash
   #:make-vm-signal-error
   #:make-vm-slot-read
   #:make-vm-slot-write
   #:make-vm-stream-write-string-inst
   #:make-vm-string-capitalize
   #:make-vm-string-coerce
   #:make-vm-string-downcase
   #:make-vm-string-equal
   #:make-vm-string-greaterp
   #:make-vm-string-left-trim
   #:make-vm-string-length
   #:make-vm-string-lessp
   #:make-vm-string-not-equal
   #:make-vm-string-right-trim
   #:make-vm-string-trim
   #:make-vm-string-upcase
   #:make-vm-nstring-upcase
   #:make-vm-nstring-downcase
   #:make-vm-nstring-capitalize
   #:make-vm-string<
   #:make-vm-string<=
   #:make-vm-string=
   #:make-vm-string>
   #:make-vm-string>=
   #:make-vm-stringp
   #:make-vm-string-set
   #:make-vm-sub
   #:make-vm-subseq
   #:make-vm-subst
   #:make-vm-set-fill-pointer
   #:make-vm-set-symbol-plist
   #:vm-slot-boundp
   #:make-vm-slot-boundp
   #:vm-slot-exists-p
   #:make-vm-slot-exists-p
   #:vm-slot-makunbound
   #:make-vm-slot-makunbound
   #:make-vm-svref
   #:make-vm-svset
   #:make-vm-symbol-get
   #:make-vm-symbol-name
   #:make-vm-symbol-p
   #:make-vm-symbol-plist
   #:make-vm-symbol-set
   #:make-vm-sync-handler-regs
   #:make-vm-terpri-inst
   #:make-vm-third
   #:make-vm-throw
   #:make-vm-truncate
   #:make-vm-type-of
   #:vm-typep
   #:make-vm-typep
   #:make-vm-unread-char
   #:make-vm-upper-case-p
   #:make-vm-values
   #:make-vm-spread-values
   #:make-vm-values-to-list
   #:make-vm-vector-pop
   #:make-vm-vector-push
   #:make-vm-vector-push-extend
   #:make-vm-vectorp
   #:vm-simple-vector-p
   #:make-vm-simple-vector-p
   #:make-vm-warn
   #:make-vm-write-byte
   #:make-vm-write-char
   #:make-vm-write-line
   #:make-vm-write-string
   #:make-vm-write-to-string-inst
   #:make-vm-write-to-string-rp
   #:make-vm-princ-to-string-inst
   #:vm-princ-to-string-inst
   #:make-vm-streamp
   #:make-vm-input-stream-p
   #:make-vm-output-stream-p
   #:make-vm-open-stream-p
   #:make-vm-interactive-stream-p
   #:make-vm-stream-element-type-inst
   #:make-vm-read-byte
   #:make-vm-listen-inst
   #:make-vm-force-output
   #:make-vm-finish-output
   #:make-vm-clear-input
   #:make-vm-clear-output
   #:make-vm-load-file
   #:vm-cons
   #:vm-car
   #:vm-cdr
   #:vm-rplaca
   #:vm-rplacd
   #:vm-make-closure
   #:vm-make-closure-params
   #:vm-env-regs
   #:vm-closure-ref-idx
   #:vm-closure-reg
   #:vm-closure-index
   #:vm-program
   #:vm-program-instructions
   #:vm-program-result-register
   #:vm-state
   #:vm-state-registers
   #:vm-state-heap
   #:vm-heap-counter
   #:vm-call-stack
   #:vm-method-call-stack
   #:vm-closure-env
   #:vm-heap-alloc
   #:vm-heap-get
   #:vm-heap-set
   #:vm-reg-get
   #:vm-reg-set
   #:execute-instruction
   #:instruction->sexp
   #:sexp->instruction
   #:build-label-table
   #:vm-dst
   #:vm-src
   #:vm-lhs
   #:vm-rhs
   #:vm-name
   #:vm-label-name
   #:vm-reg
   #:vm-value
   #:vm-captured-vars
   #:vm-func-reg
   #:vm-args
   #:vm-var-name
   #:vm-null-p
   #:vm-select-cond-reg
   #:vm-select-then-reg
   #:vm-select-else-reg
   #:vm-neg
   #:vm-length
   #:vm-reverse
   #:vm-append
   #:vm-member
   #:vm-nth
   #:vm-nthcdr
   #:vm-first
   #:vm-second
   #:vm-third
   #:vm-fourth
   #:vm-fifth
   #:vm-sixth
   #:vm-seventh
   #:vm-eighth
   #:vm-ninth
   #:vm-tenth
   #:vm-rest
   #:vm-last
   #:vm-butlast
   #:vm-nbutlast
   #:vm-nreconc
   #:vm-identity
   #:vm-constantly
   #:vm-complement
   #:vm-list-length
   #:vm-endp
   #:vm-null
   #:vm-car-reg
   #:vm-cdr-reg
   #:vm-src-regs
   #:vm-item-reg
   #:vm-list-reg
   #:vm-index-reg
   #:vm-cons-reg
   #:vm-val-reg
   #:vm-io-state
   #:vm-open-files
   #:vm-file-counter
   #:vm-standard-input
   #:vm-standard-output
   #:vm-string-streams
   #:+stdin-handle+
   #:+stdout-handle+
   #:+eof-value+
   #:vm-get-stream
   #:vm-allocate-file-handle
   #:vm-stream-open-p
   #:run-compiled-with-io
   #:run-string-with-io
   #:vm-open-file
   #:vm-close-file
   #:vm-read-char
   #:vm-read-line
   #:vm-write-char
   #:vm-write-string
   #:vm-peek-char
   #:vm-unread-char
   #:vm-file-position
   #:vm-file-length
   #:vm-eof-p
   #:vm-make-string-stream
   #:vm-get-string-from-stream
   #:vm-file-handle
   #:vm-file-direction
   #:vm-char-reg
   #:vm-str-reg
   #:vm-position-reg
   #:vm-stream-direction
   #:vm-initial-string
   #:vm-read-sexp
   #:vm-print-sexp
   #:vm-prin1-sexp
   #:vm-princ-sexp
   #:vm-make-string-output-stream-inst
   #:vm-get-output-stream-string-inst
   #:vm-stream-write-string-inst
   #:vm-read-from-string-inst
   #:vm-read-sexp-inst
   #:vm-eval
   #:vm-type-of
   #:vm-make-list
   #:vm-alphanumericp
   #:vm-reader-read
   #:vm-string=
   #:vm-string<
   #:vm-string>
   #:vm-string<=
   #:vm-string>=
   #:vm-string-equal
   #:vm-string-lessp
   #:vm-string-greaterp
   #:vm-string-not-equal
   #:vm-string-length
   #:vm-char
   #:vm-char-code
   #:vm-code-char
   #:vm-char=
   #:vm-char<
   #:vm-subseq
   #:vm-string-upcase
   #:vm-string-downcase
   #:vm-string-capitalize
   #:vm-nstring-upcase
   #:vm-nstring-downcase
   #:vm-nstring-capitalize
   #:vm-string-trim
   #:vm-string-left-trim
   #:vm-string-right-trim
   #:vm-search-string
   #:vm-string-set
   #:vm-str1
   #:vm-str2
   #:vm-string-reg
   #:vm-index
   #:vm-char1
   #:vm-char2
   #:vm-start
   #:vm-end
   #:vm-char-bag
   #:vm-pattern
   #:vm-hash-table-object
   #:vm-hash-table-internal
   #:vm-make-hash-table
   #:vm-gethash
   #:vm-sethash
   #:vm-remhash
   #:vm-clrhash
   #:vm-hash-table-count
   #:vm-hash-table-p
   #:vm-hash-table-keys
   #:vm-hash-table-values
   #:vm-hash-table-test
   #:vm-hash-table-size
   #:vm-hash-table-rehash-size
   #:vm-hash-table-rehash-threshold
   #:vm-hash-test
   #:vm-found-dst
   #:vm-hash-key
   #:vm-hash-value
   #:vm-hash-table-reg
   #:vm-hash-default
   #:vm-hash-fn
   #:vm-class-def
   #:vm-class-name-sym
   #:vm-superclasses
   #:vm-slot-names
   #:vm-slot-initargs
   #:vm-class-slots
   #:vm-make-obj
   #:vm-class-reg
   #:vm-initarg-regs
   #:vm-slot-read
   #:vm-obj-reg
   #:vm-slot-name-sym
   #:vm-slot-write
   #:vm-value-reg
   #:vm-register-method
   #:vm-gf-reg
   #:vm-method-specializer
   #:vm-method-qualifier
   #:vm-method-reg
   #:vm-generic-call
   ;; ctx-global-classes, ctx-global-generics, ctx-global-generic-params
   ;; moved to :cl-cc/compile (compiler-context owns them)
   ;; Struct predicates auto-generated by define-vm-instruction / define-vm-unary-instruction
   ;; These are used in packages/engine/optimize/src/, packages/engine/compile/src/, packages/backend/emit/src/ files
   #:vm-closure-p
   #:vm-const-p
   #:vm-jump-p
   #:vm-label-p
   #:vm-ret-p
   #:vm-add-p
   #:vm-call-p
   #:vm-move-p
   #:vm-neg-p
   #:vm-array-adjustable-p
   #:vm-array-has-fill-pointer-p
   #:vm-input-stream-p
   #:vm-interactive-stream-p
   #:vm-next-method-p
   #:vm-open-stream-p
   #:vm-output-stream-p
   #:vm-alpha-char-p
   #:vm-digit-char-p
   #:vm-graphic-char-p
   #:vm-standard-char-p
   #:vm-lower-case-p
   #:vm-upper-case-p
   #:vm-both-case-p
   ;; Struct-generated slot accessors (prefixed: vm-NAME-SLOT) not yet exported
   #:vm-const-value       ; vm-const slot: value (auto-prefix vm-const-)
   #:vm-move-dst          ; vm-move slot: dst (auto-prefix vm-move-)
   #:vm-move-src          ; vm-move slot: src (auto-prefix vm-move-)
   #:vm-lbl-name          ; vm-label slot: name (custom :conc-name vm-lbl-)
   #:vm-gethash-default   ; vm-gethash slot: default (auto-prefix vm-gethash-)
   #:vm-make-array-fill-pointer  ; vm-make-array slot: fill-pointer
   #:vm-make-hash-table-test     ; vm-make-hash-table slot: test
   #:vm-typep-type-name          ; vm-typep slot: type-name (auto-prefix vm-typep-)
   #:vm-call-next-method-args-reg ; vm-call-next-method slot: args-reg
   #:vm-make-string-char          ; vm-make-string slot: char
   ;; Named readers (:reader ...) used in vm source code
   #:vm-closure-rest-stack-alloc-p  ; vm-closure slot reader
   #:vm-func-name                   ; vm-func-ref slot reader
   #:vm-parts                       ; vm-concatenate slot reader
   #:vm-size-reg                    ; vm-make-array slot reader
   #:vm-initial-element             ; vm-make-array slot reader
   #:vm-fill-pointer                ; vm-make-array slot reader
   #:vm-adjustable                  ; vm-make-array slot reader
   ;; Additional struct-generated accessors used in tests
   #:vm-make-array-adjustable       ; vm-make-array struct accessor for adjustable slot
   ;; Additional struct predicates
   #:vm-sub-p
   ;; Constructors for char comparison structs (defined via define-vm-char-comparison)
   #:make-vm-char>
   #:make-vm-char<=
   #:make-vm-char>=
   #:make-vm-char/=
   ;; Constructor for vm-make-string
   #:make-vm-make-string
   ;; VM instruction definition macros (used by emit/regalloc-allocate.lisp)
   #:define-vm-instruction
   #:define-simple-instruction
   #:define-vm-unary-instruction
   #:define-vm-binary-instruction
   #:define-vm-char-comparison
   ;; VM bitwise helpers used by the optimizer
   #:rotate-right
   #:bswap
   ;; VM execution entry points (defined in vm-run.lisp / io-runners.lisp)
   #:run-compiled
   #:run-program-slice
   ;; VM heap/object types (defined in vm.lisp)
   #:vm-heap-object
   #:vm-heap-address
   #:make-vm-heap-address
   #:vm-heap-address-value
   #:vm-heap-address-p
   #:vm-cons-cell
   ;; vm-program struct (defined in vm.lisp)
   #:make-vm-program
   #:vm-program-p
   ;; Struct type names used in typep/type-of lookups by optimizer/compiler
   ;; These must be the SAME symbol as the defstruct type in :cl-cc/vm
   #:vm-aref
   #:vm-aset
   #:vm-array-row-major-index
   #:vm-call-next-method
   #:vm-encode-universal-time
   #:vm-format-inst
   #:vm-fresh-line-inst
   #:vm-listen-inst
   #:vm-make-string
   #:vm-prin1
   #:vm-princ
   #:vm-print-inst
   #:vm-read-byte
   #:vm-terpri-inst
   #:vm-values-to-list
   #:vm-write-to-string-inst
   ;; Opcode name symbols stored in *opcode-name-table* and used as bigram hash keys
   ;; Only non-CL symbols are exported (CL package symbols are identical everywhere)
   ;; These are interned in :cl-cc/vm by defopcode forms in vm-opcodes-defs.lisp
   #:const
   #:load-const
   #:load-nil
   #:load-true
   #:load-fixnum
   #:const-halt2
   #:move
   #:neg
   #:inc
   #:dec
   #:fixnump
   #:make-vector
   #:vector-ref
   #:vector-set
   #:make-hash
   #:hash-ref
   #:hash-set
   #:get-global
   #:set-global
   #:add2
   #:sub2
   #:mul2
   #:div
   #:add-imm2
   #:sub-imm2
   #:mul-imm2
   #:num-eq2
   #:num-lt2
   #:num-gt2
   #:num-le2
   #:num-ge2
   #:num-eq-imm2
   #:num-lt-imm2
   #:num-gt-imm2
   #:num-le-imm2
   #:num-ge-imm2
   #:jump-if-nil
   #:jump-if-true
   #:recv-values
   #:return-nil
   #:halt2
   ;; vm.lisp: core vm state, instruction table, opcodes
   #:make-vm-state
   #:vm-output-stream
   #:vm-global-vars
   #:vm-profile-enabled-p
   #:vm-profile-call-stack
   #:vm-profile-samples
   #:*instruction-constructors*
   ;; vm-state-init.lisp: state initialization, misc accessors
   #:vm-falsep
   #:vm-program-leaf-p
   ;; vm-bridge.lisp: host bridge helpers (internal helpers)
   #:hash-table-values
   #:%class-slot-initargs-for-slot
   #:%class-slot-metadata
   #:%class-slot-definitions
   #:slot-definition-name
   #:slot-definition-initform
   #:slot-definition-initargs
   #:slot-definition-allocation
   #:generic-function-methods
   #:generic-function-method-combination
   #:%package-symbols
   #:%package-external-symbols
   #:%all-symbols
   ;; rt-plist-put is exported from :cl-cc/bootstrap (shared with :cl-cc/parse)
   #:resolve-hash-test
   ;; vm-dispatch.lisp: call frame, label table
   #:vm-label-table-lookup
   #:vm-label-table-store
   #:vm-push-call-frame
   #:vm-save-registers
   #:vm-restore-registers
   #:vm-save-registers-subset
   #:vm-restore-registers-subset
   ;; vm-dispatch-gf.lisp: GF dispatch helpers
   #:vm-classify-arg
   #:%eql-specializer-p
   #:%eql-specializer-matches-p
   #:%vm-extract-eql-specializer-keys
   #:%vm-gf-eql-methods
   #:%vm-resolve-single-dispatch
   ;; vm-dispatch-gf-multi.lisp: multi-dispatch
   #:%vm-gf-uses-composite-keys-p
   #:vm-try-dispatch-combinations
   #:vm-try-dispatch-sub
   ;; vm-clos.lisp: CLOS helpers
   #:collect-inherited-slots
   #:collect-inherited-initargs
   #:compute-class-precedence-list
   #:vm-class-registry
   ;; vm-clos-execute.lisp: CLOS execution helpers
   #:%resolve-combination-operator
   #:*method-combination-operators*
   ;; vm-run.lisp: vm execution
   #:vm-error-type-matches-p
   ;; vm-opcodes.lisp: opcode tables
   #:*opcode-dispatch-table*
   #:*opcode-encoder-table*
   #:*opcode-name-table*
   ;; vm-opcodes-defs.lisp: opcode constants (+OP2-*+ generated by defopcode)
   #:+op2-const+
   #:+op2-nop+
   #:+op2-load-const+
   #:+op2-load-nil+
   #:+op2-load-true+
   #:+op2-load-fixnum+
   #:+op2-const-halt2+
   #:+op2-move+
   #:+op2-neg+
   #:+op2-inc+
   #:+op2-dec+
   #:+op2-fixnump+
   #:+op2-consp+
   #:+op2-symbolp+
   #:+op2-functionp+
   #:+op2-stringp+
   #:+op2-cons+
   #:+op2-car+
   #:+op2-cdr+
   #:+op2-make-vector+
   #:+op2-vector-ref+
   #:+op2-vector-set+
   #:+op2-make-hash+
   #:+op2-hash-ref+
   #:+op2-hash-set+
   #:+op2-get-global+
   #:+op2-set-global+
   #:+op2-make-instance+
   #:+op2-eq+
   #:+op2-eql+
   #:+op2-equal+
   #:+op2-add2+
   #:+op2-sub2+
   #:+op2-mul2+
   #:+op2-div+
   #:+op2-mod+
   #:+op2-add-imm2+
   #:+op2-sub-imm2+
   #:+op2-mul-imm2+
   #:+op2-num-eq2+
   #:+op2-num-lt2+
   #:+op2-num-gt2+
   #:+op2-num-le2+
   #:+op2-num-ge2+
   #:+op2-num-eq-imm2+
   #:+op2-num-lt-imm2+
   #:+op2-num-gt-imm2+
   #:+op2-num-le-imm2+
   #:+op2-num-ge-imm2+
   #:+op2-jump+
   #:+op2-jump-if-nil+
   #:+op2-jump-if-true+
   #:+op2-values+
   #:+op2-recv-values+
   #:+op2-return+
   #:+op2-return-nil+
   #:+op2-halt2+
   ;; vm-opcodes-defs.lisp: opcode constants
   #:+vm-register-count+
   #:make-vm2-state
   #:vm2-state-p
   #:vm2-state-registers
   #:vm2-state-global-vars
   #:vm2-state-output-stream
   #:vm2-state-values-buffer
   #:vm2-reg-get
   #:vm2-reg-set
   #:run-vm
   #:run-vm-with-opcode-bigrams
   #:vm2-collect-opcode-bigrams
   #:vm2-fuse-immediate-superinstructions
   #:vm2-top-superoperator-candidates
   ;; vm-execute.lisp: execution helpers
   #:build-label-table
   ;; vm-execute-mv.lisp: multiple values
   ;; vm-extensions.lisp: extensions
   ;; conditions.lisp: condition system
   #:vm-signal-condition
   #:vm-find-handler
   #:vm-find-restart
   #:vm-add-restart
   #:vm-get-restarts
   #:vm-get-handler-stack
   #:vm-push-handler-to-stack
   #:vm-pop-handler-from-stack
   #:vm-clear-condition-context
   #:*active-restarts*
   ;; conditions-instructions.lisp: condition types
   #:vm-type-error
   #:vm-unbound-variable
   #:vm-undefined-function
   #:vm-division-by-zero
   #:vm-warning
   #:vm-error
   #:vm-datum
   #:vm-expected-type
   #:vm-variable-name
   #:vm-function-name
   #:vm-dividend
   #:vm-restart-name
   #:vm-handler-type
   #:vm-handler-entry-saved-regs
   ;; io.lisp / io-execute.lisp: I/O helpers
   #:vm-list-to-lisp-list
   #:vm-build-list
   #:vm-signal-condition
   ;; list.lisp / list-execute.lisp: list helpers
   #:vm-adjust-sequence
   #:vm-sequence-elt
   #:vm-sequence-length
   #:vm-make-sequence-like
   #:vm-hash-cons
   #:vm-clear-hash-cons-table
   ;; primitives.lisp: arithmetic/type helpers
   #:vm-falsep
   ;; primitives-typep.lisp: type predicate helpers
   ;; vm-bitwise.lisp: bitwise ops (already have rotate-right, bswap)
   ;; vm-transcendental.lisp: trig/transcendental constructors
   #:make-vm-sin-inst
   #:make-vm-cos-inst
   #:make-vm-tan-inst
   #:make-vm-acos-inst
   #:make-vm-asin-inst
   #:make-vm-atan-inst
   #:make-vm-atan2-inst
   #:make-vm-sinh-inst
   #:make-vm-cosh-inst
   #:make-vm-tanh-inst
   #:make-vm-exp-inst
   #:make-vm-log-inst
   #:make-vm-sqrt
   #:make-vm-expt
   #:make-vm-float-inst
   #:make-vm-decode-float
   #:make-vm-integer-decode-float
   #:make-vm-scale-float
   ;; vm-numeric.lisp: numeric ops
   #:make-vm-round-inst
   ;; vm-bitwise.lisp: bitwise ops constructors
   #:make-vm-ash
   #:make-vm-bswap
   #:make-vm-rotate
   #:make-vm-logand
   #:make-vm-logior
   #:make-vm-logxor
   #:make-vm-logeqv
   #:make-vm-lognot
   #:make-vm-logtest
   #:make-vm-logbitp
   #:make-vm-logcount
   #:make-vm-integer-length
   ;; Additional missing constructors/types
   #:make-vm-boundp
   #:make-vm-fboundp
   #:make-vm-char-equal
   #:make-vm-string
   #:make-vm-type-error
   #:make-vm-unbound-variable
   #:make-vm-undefined-function
   #:make-vm-division-by-zero
   ;; vm-clos-execute: condition-related vm types
   #:%documentation-table*
   #:*documentation-table*
   ;; vm-bridge: slot-def helpers
   ;; List operation predicates and helpers
   #:vm-arg-slot-name
   #:vm-bind-arg-slots
   #:vm-bind-closure-args
   #:vm-closure-optional-params
   #:vm-closure-key-params
   #:vm-closure-rest-param
   ;; io.lisp: additional
   #:vm-open-file-direction
   #:vm-make-string-stream-direction
   ;; vm-run.lisp additional
   #:vm-program-leaf-p
   ;; Type specifier symbols used as hash table keys in *vm-compound-type-handlers*
   ;; These must be accessible as cl-cc:: symbols (via use-package inheritance)
   #:refine
   ;; Hook variables for circular dependency resolution
   #:*vm-eval-hook*
   #:*vm-macroexpand-1-hook*
   #:*vm-macroexpand-hook*
   #:*vm-compile-string-hook*
   #:*vm-parse-forms-hook*
   ;; io.lisp: vm state snapshot
   #:clone-vm-state))

(in-package :cl-cc/vm)

;;; Hook variables for circular dependency resolution.
;;; These are set at load time by the respective upstream packages.
(defvar *vm-eval-hook* nil
  "Set by cl-cc/compile (pipeline.lisp). Called by the VM's vm-eval instruction.")
(defvar *vm-macroexpand-1-hook* nil
  "Set by cl-cc/expand (macro.lisp). Called by the VM's vm-macroexpand-1-inst instruction.")
(defvar *vm-macroexpand-hook* nil
  "Set by cl-cc/expand (macro.lisp). Called by the VM's vm-macroexpand-inst instruction.")
(defvar *vm-compile-string-hook* nil
  "Set by cl-cc/compile (pipeline.lisp). Called by run-string-with-io in io-runners.lisp.")
(defvar *vm-parse-forms-hook* nil
  "Set by cl-cc/parse (parser.lisp). Called by the VM's vm-read-sexp-inst instruction.")
