(in-package :cl-cc)

(eval-when (:compile-toplevel :load-toplevel :execute)
  (dolist (name '(
           "export"
           ;; cst-*, lexer-*, parse-cl-*, diagnostic-*, incremental-*, cache-*,
           ;; lower-cst-*, parse-and-lower-*, parse-source, parse-all-forms
           ;; moved to :cl-cc/parse — see cl-cc-parse.asd (Phase 2)
           ;; DCG symbols (already in :cl-cc/prolog, kept for backward compat):
           "def-dcg-rule"
           "phrase"
           "phrase-rest"
           "phrase-all"
           "dcg-fresh-var"
           "dcg-reset-counter"
           ;; cps-transform, cps-transform*, cps-transform-ast, cps-transform-ast*,
           ;; cps-transform-sequence, cps-transform-eval, compile-expression,
           ;; compile-string, emit-assembly, run-string, run-string-repl,
           ;; run-string-typed, reset-repl-state, *repl-vm-state*, our-load
           ;; moved to :cl-cc/compile — see cl-cc-compile.asd (Phase 2)
           ;; our-eval, binop/const/var/cmp, integer-type/boolean-type, env-lookup,
           ;; make-cst-token, lexer-token-{p,type,value} moved to :cl-cc/bootstrap.
           "run-compiled"
           "run-program-slice"
           ;; optimize-instructions moved to :cl-cc/optimize — see cl-cc-optimize.asd (Phase 2)
           "%get-instructions"
           "type-check-ast"
           "register-function-type"
           "*function-type-registry*"
           "logic-var-p"
           "unify"
           "unify-failed-p"
           "occurs-check"
           "logic-substitute"
           "substitute-variables"
           "def-fact"
           "def-rule"
           "query-all"
           "query-one"
           "query-first-n"
           "solve-goal"
           "solve-conjunction"
           "clear-prolog-database"
           "*prolog-rules*"
           "prolog-goal"
           "make-prolog-rule"
           "prolog-rule"
           "prolog-cut"
           "goal-predicate"
           "goal-args"
           "rule-head"
           "rule-body"
           "rename-variables"
           "apply-prolog-peephole"
           "*enable-prolog-peephole*"
           ;; expand symbols (macro-env, our-defmacro, our-macroexpand-*,
           ;; parse-lambda-list, dolist/dotimes/do/do*/case/typecase/loop)
           ;; moved to :cl-cc/expand — see cl-cc-expand.asd (Phase 2)
           "ast-node"
           "ast-source-file"
           "ast-source-line"
           "ast-source-column"
           "ast-location-string"
           "ast-error"
           "ast-compilation-error"
           "ast-children"
           "ast-bound-names"
           "ast-int"
           "make-ast-int"
           "ast-int-value"
           "ast-var"
           "make-ast-var"
           "ast-var-name"
           "ast-binop"
           "make-ast-binop"
           "ast-binop-op"
           "ast-binop-lhs"
           "ast-binop-rhs"
           "ast-if"
           "make-ast-if"
           "ast-if-cond"
           "ast-if-then"
           "ast-if-else"
           "ast-progn"
           "make-ast-progn"
           "ast-progn-forms"
           "ast-print"
           "make-ast-print"
           "ast-print-expr"
           "ast-let"
           "make-ast-let"
           "ast-let-bindings"
           "ast-let-body"
           "ast-lambda"
           "make-ast-lambda"
           "ast-lambda-params"
           "ast-lambda-optional-params"
           "ast-lambda-rest-param"
           "ast-lambda-key-params"
           "ast-lambda-body"
           "ast-lambda-env"
           "ast-function"
           "make-ast-function"
           "ast-function-name"
           "ast-flet"
           "make-ast-flet"
           "ast-flet-bindings"
           "ast-flet-body"
           "ast-labels"
           "make-ast-labels"
           "ast-labels-bindings"
           "ast-labels-body"
           "ast-call"
           "make-ast-call"
           "ast-call-func"
           "ast-call-args"
           "ast-block"
           "make-ast-block"
           "ast-block-name"
           "ast-block-body"
           "ast-return-from"
           "make-ast-return-from"
           "ast-return-from-name"
           "ast-return-from-value"
           "ast-tagbody"
           "make-ast-tagbody"
           "ast-tagbody-tags"
           "ast-go"
           "make-ast-go"
           "ast-go-tag"
           "ast-setq"
           "make-ast-setq"
           "ast-setq-var"
           "ast-setq-value"
           "ast-multiple-value-call"
           "make-ast-multiple-value-call"
           "ast-mv-call-func"
           "ast-mv-call-args"
           "ast-multiple-value-prog1"
           "make-ast-multiple-value-prog1"
           "ast-mv-prog1-first"
           "ast-mv-prog1-forms"
           "ast-values"
           "make-ast-values"
           "ast-values-forms"
           "ast-multiple-value-bind"
           "make-ast-multiple-value-bind"
           "ast-mvb-vars"
           "ast-mvb-values-form"
           "ast-mvb-body"
           "ast-apply"
           "make-ast-apply"
           "ast-apply-func"
           "ast-apply-args"
           "ast-catch"
           "make-ast-catch"
           "ast-catch-tag"
           "ast-catch-body"
           "ast-throw"
           "make-ast-throw"
           "ast-throw-tag"
           "ast-throw-value"
           "ast-unwind-protect"
           "make-ast-unwind-protect"
           "ast-unwind-protected"
           "ast-unwind-cleanup"
           "ast-handler-case"
           "ast-handler-case-form"
           "ast-handler-case-clauses"
           "ast-quote"
           "make-ast-quote"
           "ast-quote-value"
           "ast-the"
           "make-ast-the"
           "ast-the-type"
           "ast-the-value"
           "ast-defun"
           "ast-defun-name"
           "ast-defun-params"
           "ast-defun-optional-params"
           "ast-defun-rest-param"
           "ast-defun-key-params"
           "ast-defun-body"
           "ast-defvar"
           "ast-defvar-name"
           "ast-defvar-value"
           "ast-defmacro"
           "ast-defmacro-name"
           "ast-defmacro-lambda-list"
           "ast-defmacro-body"
           "ast-slot-def"
           "make-ast-slot-def"
           "ast-slot-name"
           "ast-slot-initarg"
           "ast-slot-initform"
           "ast-slot-reader"
           "ast-slot-writer"
           "ast-slot-accessor"
           "ast-slot-type"
           "ast-slot-allocation"
           "ast-defclass"
           "ast-defclass-name"
           "ast-defclass-superclasses"
           "ast-defclass-slots"
           "ast-defclass-default-initargs"
           "ast-defgeneric"
           "ast-defgeneric-name"
           "ast-defgeneric-params"
           "ast-defmethod"
           "ast-defmethod-name"
           "ast-defmethod-qualifier"
           "ast-defmethod-specializers"
           "ast-defmethod-params"
           "ast-defmethod-body"
           "ast-make-instance"
           "ast-make-instance-class"
           "ast-make-instance-initargs"
           "ast-slot-value"
           "ast-slot-value-object"
           "ast-slot-value-slot"
           "ast-set-slot-value"
           "ast-set-slot-value-object"
           "ast-set-slot-value-slot"
           "ast-set-slot-value-value"
           "ast-set-gethash"
           "ast-set-gethash-key"
           "ast-set-gethash-table"
           "ast-set-gethash-value"
           ;; parse-compiler-lambda-list, lambda-list-has-extended-p,
           ;; parse-slot-spec, slot-def-to-sexp
           ;; moved to :cl-cc/parse — see cl-cc-parse.asd (Phase 2)
           ;; compile-toplevel-forms, compilation-result, make-compilation-result,
           ;; compilation-result-program/-assembly/-globals/-type/-type-env/-cps/-ast/
           ;; -vm-instructions/-optimized-instructions
           ;; moved to :cl-cc/compile — see cl-cc-compile.asd (Phase 2)
           ;; lower-sexp-to-ast, ast-to-sexp moved to :cl-cc/parse — see cl-cc-parse.asd (Phase 2)
           "vm-heap-object"
           "vm-heap-address"
           "make-vm-heap-address"
           "vm-heap-address-value"
           "vm-cons-cell"
           ))
    (export (intern (string-upcase name) :cl-cc) :cl-cc)))
