name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Roswell
        run: curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh
        env:
          LISP: sbcl-bin
      - name: Run Test
        run: sbcl --dynamic-space-size 4096 --non-interactive --eval '(require :asdf)' --load cl-cc.asd --eval '(asdf:load-system :cl-cc/test)' --eval '(asdf:test-system :cl-cc/test)'
