;;;; cst.lisp — Concrete Syntax Tree node definitions
;;;;
;;;; CST nodes preserve ALL source information: comments, whitespace,
;;;; exact byte positions. This replaces the old AST system and serves
;;;; as the foundation for incremental parsing and precise diagnostics.

(in-package :cl-cc/parse)

;;; Trivia (not a CST node — attached to tokens/interiors)

(defstruct cst-trivia
  "A trivia item: whitespace, comment, or newline attached to a token."
  (kind       nil :type keyword)
  (text       ""  :type string)
  (start-byte 0   :type integer)
  (end-byte   0   :type integer))

;;; CST node hierarchy

(defstruct cst-node
  "Base struct for all CST nodes."
  (kind        nil :type (or keyword null))
  (start-byte  0   :type integer)
  (end-byte    0   :type integer)
  (source-file nil :type (or string null))
  (dirty-p     nil :type boolean))

(defstruct (cst-token (:include cst-node))
  "A leaf token: number, string, symbol, etc."
  (value  nil)
  (trivia nil :type list))

(defstruct (cst-interior (:include cst-node))
  "An interior/composite node with children."
  (children nil :type list)
  (trivia   nil :type list))

(defstruct (cst-error-node (:include cst-node))
  "An error recovery node for tokens that couldn't be parsed."
  (message    "" :type string)
  (raw-tokens nil :type list))

;;; Accessor helpers

(defun cst-child (node n)
  "Return the Nth child of an interior CST node."
  (nth n (cst-interior-children node)))

(defun cst-children (node)
  "Return children list of an interior CST node."
  (cst-interior-children node))

;;; cst-token-p, cst-interior-p, cst-error-node-p are auto-generated by defstruct.
;;; Alias for the error node predicate:
(defun cst-error-p (node)
  (cst-error-node-p node))

;;; Traversal

(defun cst-walk (node fn)
  "Walk the CST tree rooted at NODE, calling FN on each node (pre-order)."
  (funcall fn node)
  (when (cst-interior-p node)
    (dolist (child (cst-interior-children node))
      (cst-walk child fn))))

;;; Location

(defun cst-location-string (node &optional source)
  "Return a human-readable location string for NODE."
  (let ((byte (cst-node-start-byte node))
        (file (cst-node-source-file node)))
    (if source
        (let ((line 1) (col 0))
          (loop for i from 0 below (min byte (length source))
                do (if (char= (char source i) #\Newline)
                       (progn (incf line) (setf col 0))
                       (incf col)))
          (if file
              (format nil "~A:~D:~D" file line col)
              (format nil "~D:~D" line col)))
        (if file
            (format nil "~A:byte ~D" file byte)
            (format nil "byte ~D" byte)))))

(defun cst-collect-errors (tree)
  "Collect all cst-error-node instances from TREE."
  (let ((errors nil))
    (cst-walk tree (lambda (n)
                     (when (cst-error-p n)
                       (push n errors))))
    (nreverse errors)))

;;; CST -> S-expression conversion

(defun cst-to-sexp (node)
  "Convert a CST node back to an S-expression. Drops trivia/positions."
  (cond
    ((cst-token-p node)
     ;; Cons values in T-INT tokens (from #. or #n= labels) are literal data,
     ;; not code. Wrap them in (quote ...) so lower-sexp-to-ast treats them as constants.
     (let ((v (cst-token-value node)))
       (if (consp v) (list 'quote v) v)))
    ((cst-interior-p node)
     (let ((kind (cst-node-kind node))
           (children (cst-interior-children node)))
       (case kind
         (:quote             (list 'quote (cst-to-sexp (first children))))
         (:quasiquote        (list 'backquote (cst-to-sexp (first children))))
         (:unquote           (list 'unquote (cst-to-sexp (first children))))
         (:unquote-splicing  (list 'unquote-splicing (cst-to-sexp (first children))))
         (:function          (list 'function (cst-to-sexp (first children))))
         (:vector            (coerce (mapcar #'cst-to-sexp children) 'vector))
         (:dotted-list
          ;; Dotted pair: (a b c . d) → children are (a b c d), last is cdr
          (let ((sexps (mapcar #'cst-to-sexp children)))
            (if (null sexps)
                nil
                (let* ((reversed (reverse sexps))
                       (result (car reversed)))
                  (dolist (s (cdr reversed) result)
                    (setf result (cons s result)))))))
         (t                  (mapcar #'cst-to-sexp children)))))
    ((cst-error-p node) nil)
    (t node)))

;;; S-expression -> CST conversion (inverse of cst-to-sexp)

(defun sexp-to-cst (form)
  "Convert an S-expression FORM into a CST tree.
   Used to re-wrap expanded macro output back into CST for compile-cst."
  (cond
    ((null form)     (make-cst-token :kind :nil :value nil))
    ((integerp form) (make-cst-token :kind :int :value form))
    ((floatp form)   (make-cst-token :kind :float :value form))
    ((rationalp form)(make-cst-token :kind :ratio :value form))
    ((stringp form)  (make-cst-token :kind :string :value form))
    ((characterp form)(make-cst-token :kind :char :value form))
    ((vectorp form)  (make-cst-interior :kind :vector
                                        :children (map 'list #'sexp-to-cst form)))
    ((keywordp form) (make-cst-token :kind :keyword :value form))
    ((eq form t)     (make-cst-token :kind :t :value t))
    ((symbolp form)  (make-cst-token :kind :var :value form))
    ((consp form)
     (let ((head (car form)))
       (cond
         ((eq head 'quote)
          (make-cst-interior :kind :quote
                             :children (list (sexp-to-cst (second form)))))
         ((eq head 'function)
          (make-cst-interior :kind :function
                             :children (list (sexp-to-cst (second form)))))
         ((symbolp head)
          (make-cst-interior :kind (sexp-head-to-kind head)
                             :children (mapcar #'sexp-to-cst form)))
         ((and (consp head) (eq (car head) 'lambda))
          (make-cst-interior :kind :call
                             :children (mapcar #'sexp-to-cst form)))
         (t (make-cst-interior :kind :call
                               :children (mapcar #'sexp-to-cst form))))))
    (t (make-cst-token :kind :unknown :value form))))

(defun sexp-head-to-kind (sym)
  "Map a symbol in head position to its CST kind keyword."
  (case sym
    ((defun) :defun) ((defvar) :defvar) ((defparameter) :defparameter)
    ((defmacro) :defmacro) ((defclass) :defclass) ((defmethod) :defmethod)
    ((defgeneric) :defgeneric) ((lambda) :lambda)
    ((let) :let) ((let*) :let*) ((flet) :flet) ((labels) :labels)
    ((if) :if) ((when) :when) ((unless) :unless) ((cond) :cond) ((case) :case)
    ((progn) :progn) ((prog1) :prog1) ((prog2) :prog2)
    ((block) :block) ((return-from) :return-from)
    ((tagbody) :tagbody) ((go) :go)
    ((setq) :setq) ((setf) :setf)
    ((the) :the) ((declare) :declare) ((locally) :locally)
    ((handler-case handler-bind) :handler-case)
    ((unwind-protect) :unwind-protect) ((catch) :catch) ((throw) :throw)
    ((multiple-value-bind) :multiple-value-bind)
    ((multiple-value-call) :multiple-value-call)
    ((multiple-value-prog1) :multiple-value-prog1)
    ((values) :values) ((loop) :loop) ((do do*) :do)
    ((dolist) :dolist) ((dotimes) :dotimes)
    ((and) :and) ((or) :or) ((apply) :apply) ((funcall) :funcall)
    ((eval-when) :eval-when) ((progv) :progv)
    ((macrolet) :macrolet) ((symbol-macrolet) :symbol-macrolet)
    ((make-instance) :make-instance) ((slot-value) :slot-value)
    ((defstruct) :defstruct) ((in-package) :in-package) ((print) :print)
    (t :call)))
